### ISSUE TITLE
Get Page Source is ambiguous

### ISSUE THREAD

**Issue by shs96c** [w3c/webdriver#1003]
I imagine that the second choice (serializing the active document) is the correct approach. Just checking.

In [15.1 Getting Page Source](https://www.w3.org/TR/webdriver/#getting-page-source#h-getting-page-source):
> Let source be the result returned from the outerHTML IDL Attribute of the document element of the current browsing context active document.
> 
> Let source be the result of serializing to string the current browsing context active document, if source is null.

**Comment by jgraham** [comment]
Can `outerHTML` bu null there? There has to be a document element, even if there isn't a root, right?

But also, depending on the value of specific DOM attributes is bad spec writing; what if a page does 

```
document.outerHTML = function() {
    throw 1;
}
```

**Comment by shs96c** [comment]
Is there a way of calling the original `outerHTML` attribute?

**Comment by jgraham** [comment]
The textual definition is short:

> On getting, return the result of invoking the fragment serializing algorithm on a fictional node whose only child is the context object providing true for the require well-formed flag (this might throw an exception instead of returning a string). 

It seems like "Return a string that is the result of invoking the fragment serializing algorithm on a (fictional) node whose only child is the document root element." and some value for the require well-formed flag would cover it (idk if this should really be true).
