### ISSUE TITLE
stacktrace -> stackTrace

### ISSUE THREAD

**Issue by barancev** [w3c/webdriver#1006]
https://w3c.github.io/webdriver/webdriver-spec.html#processing-model

In https://github.com/SeleniumHQ/selenium/issues/3683 @AutomatedTester wrote:

"We're going to have to update the spec to do stackTrace."

**Comment by andreastt** [comment]
If the clients are changing anyway to look for `stacktrace`, why can’t this be a permanent change? I’m skeptical of making API breaking changes at this point because it hits Mozilla, as the first spec conforming implementor, quite hard.

**Comment by shs96c** [comment]
`stacktrace` is defined in the spec as an `implementation-defined string containing a stack trace report of the active stack frames at the time when the error occurred.`

`stackTrace` from the JSON Wire Protocol is a structured type, composed of a list of objects.

Making the spec use `stackTrace` will cause unexpected bugs with older selenium clients. I strongly suggest not making the spec change the casing of "stack trace"
