### ISSUE TITLE
It's not clear how to restore a window from minimized, maximized, or fullscreen state

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver#1007]
As noticed on https://github.com/mozilla/geckodriver/issues/860#issuecomment-321817587 the spec is not clear in how which command has to be executed to restore the window to it's previous state. All the three commands only specify the necessary steps to reach the target state.

I cannot find another command which easily let you restore the window state.

**Comment by andreastt** [comment]
In fact the specification is inconsistent for the different commands: calling Maximize Window or Fullscreen Window a second time does nothing (moves the window into either maximised or fullscreened state); calling Minimize Window restores the iconified window.

I think we have two options. Either we make each command perform the reverse action of itself when called the second time (calling Maximize Window after having maximized window restores the window to its original dimensions), which is similar to what a user would expect to happen when clicking the window manager’s maximize button again; or alternatively we remove all three commands and make the Set Window Rect command take a mutable `state` field describing the desired window state (it already returns state, so this would have some nice parity).

**Comment by shs96c** [comment]
My preference would be to use the `Set Window Rect` command alone.

**Comment by shs96c** [comment]
After discussion on the mailing list, the following is proposed:

* Remove `state` from `Get Window Rect` return value.
* Remove `Maximize Window`, `Minimize Window`, and `Fullscreen Window`.
* Add a `Get/Set Window State` function to handle the changing of window state commands.

This leaves us with no functional changes, but clarifies the difference between window state and window size.

**Comment by jgraham** [comment]
I oppose that change. I think it's too big a change to include without going to a second CR. I also don't see that it's a big improvement. Why can't we make Maximize, Minimize and Fullscreen idempotent, and if you want to restore to some other size then you have to explicitly set that? The only remaining issue is if the browser happens to open fullscreen, but in general if you are running some test that cares at all about the window size you should set it explicitly, so…

**Comment by shs96c** [comment]
The downside with the solution proposed is that it may kick off a new CR period. To bring some consistency to the commands:

- Minimize, Fullscreen, and Maximize Window should be idempotent --- calling them repeatedly is a no-op
- To restore a window from any of those states, call `Set Window Rect`. If there is a desire to return to the original size and location, these should be stored before calling any of the other window state management commands.

**Comment by shs96c** [comment]
With 1e1e590, it is now clear how to restore the state of a window: call `Set Window Rect`. Closing this issue.
