### ISSUE TITLE
Clarify which proxy capabilities are required for each proxy type

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver#1008]
Currently the spec is not clear about which proxy capabilities are required or optional depending on the type of proxy selected. 

Should we have another column in the [proxy caps table](https://w3c.github.io/webdriver/webdriver-spec.html#proxy) or better clarify with wording inside the remote steps?

@shs96c and @AutomatedTester what do you prefer?

**Comment by shs96c** [comment]
Sure it does. The spec tells us how to deserialize the proxy object, and then goes on to say:

> If the endpoint node does not allow the proxy it uses to be configured, or if the proxy configuration defined in value is not one that passes the endpoint node's implementation-specific validity checks, return success with data null.

So whether or not a proxy configuration is valid depends on the implementation.

**Comment by whimboo** [comment]
Well we have the following situations for different proxy types:

- direct/system/autodetect (no other keys are required)
- pac (only pac url is required, all other keys are optional)
- manual (hosts with optional port for each scheme may have to be defined, all other keys are optional)

Not everyone knows proxy configuration that well and it may help to give more details in what's needed and what's optional for each proxy type?

**Comment by shs96c** [comment]
I have no idea how different browsers handle the "manual" section, and don't feel comfortable attempting to standardise it. Feel free to submit a PR to help address it.

**Comment by whimboo** [comment]
We clarified the remaining changes on IRC yesterday, and the updated PR should cover everything now.
