### ISSUE TITLE
Add endpoint for {Get,Set} Window State

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver#1023]
As discussed in issue #1007 it was too late to add an end-point for such a command given that it would have been triggered another CR period.

So we don't forget about it, I'm filing this issue for level 2 already now.

**Comment by shs96c** [comment]
This PR will close #1023

**Comment by whimboo** [comment]
@shs96c which PR do you mean? You are referencing the same issue here. Thanks.

**Comment by shs96c** [comment]
I thought that there was a PR for this already. Huh.

**Comment by whimboo** [comment]
Here the resolution from TPAC ([minutes](https://www.w3.org/2018/10/26-webdriver-minutes.html#item04)):

> We will not add a Get Window State command because not all remote end implementations have a notion of maximized window state. This means the tests for Maximize Window will be weak and that we will have to introduce a thread suspend to make sure the window size doesn’t keep changing after the command has returned.

The minutes miss the part where @andreastt described a possible test to check for the maximized state. Is that something we still want? 

Otherwise this issue can be closed as wontfix.

**Comment by andreastt** [comment]
I am actually implementing the discussed assertion for Maximize Window in https://bugzilla.mozilla.org/show_bug.cgi?id=1505142, so this can be closed now.
