### ISSUE TITLE
Clarify where URI template variables originate from

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#1035]
It is unclear from reading the specification where definitions of the URI template variables are made. Instead of passing the URI variables from the processing section as a vararg-esque structure, it is arguably clearer to pass _a dictionary_ of URI variables to each command’s remote end steps.

The specification isn’t functionally wrong the way it is written, but for the casual reader and implementor, it might be clearer that variables from URI template parsing are passed in its own structure to commands.

This is similar to previous proposals by @vkatsikaros.

**Comment by andreastt** [comment]
@vkatsikaros Is this something you’d be willing to take on?

**Comment by vkatsikaros** [comment]
@andreastt happy to give it a go if there is interest.

I recall when I first laid eyes on the spec: the arguments passed from the URI templates were visible (such as "/session/{session id}/element/{element id}/element"), but I found less visible the variables passed through _parameters_. Do you refer to both URI template and body parameters, or just the ones in URI template?

Regarding the body parameters, in several APIs they are explicitly listed in some kind of form (table/JSON).
https://cloud.google.com/container-builder/docs/api/reference/rest/v1/projects.builds/create & 
https://cloud.google.com/container-builder/docs/api/reference/rest/v1/projects.builds#Build
![1](https://user-images.githubusercontent.com/1138992/29680232-a02760f4-890c-11e7-905f-e67f978212d1.jpg)
https://developers.digitalocean.com/documentation/v2/#create-a-new-block-storage-volume
![2](https://user-images.githubusercontent.com/1138992/29680233-a02bb3e8-890c-11e7-9070-a67511722e55.jpg)

**Comment by andreastt** [comment]
The current way in which the remote end steps are invoked is this:

> Let _response result_ be the return value obtained by running the remote end steps for _command_ with one named argument for each entry in _url variables_ and an additional argument named _parameters_ whose value is _parameters_. 

The instead of passing a variable list of arguments (“with one named argument for each entry in _url variables_”) we want the dispatch to each commands’ remote end steps to be explicit so that each command can be invoked with the exact same number of arguments.

For that we could pass _url variables_ directly to the remote end steps along with _parameters_. This would be the least invasive way to fix this.

Whilst I think it is a good idea to be more formal about input and output types in the WebDriver specification, this isn’t either input or output from the spec. I think tables like the ones you show above would be more useful for the _JSON input_ to the command and the _JSON output_ response. For this specifically, I think we can get away with the following strawman:

> Let _response result_ be the return value obtain by running the remote end steps for _command_, giving _parameters_ and _url variables_ as arguments.

Then each set of remote end steps needs to be updated to not pick the URI variables out of thin air.

**Comment by vkatsikaros** [comment]
@andreastt I apologize for the delay :/ I did the first step to introduce the dictionary.

If this looks good like a good start I can tweak the remote end steps that need it.

**Comment by andreastt** [comment]
There’s no rush on this (-:
