### ISSUE TITLE
WebDriver Specs doesn't mentions id, name and className as accepted Locator Strategies

### ISSUE THREAD

**Issue by Debanjan-B** [w3c/webdriver#1042]
In chapter [12. Element Retrieval](https://w3c.github.io/webdriver/webdriver-spec.html#locator-strategies#x12.-element-retrieval), section [12.1 Locator Strategies](https://w3c.github.io/webdriver/webdriver-spec.html#locator-strategies#x12.1-locator-strategies):
> Locator Strategies

WebDriver Specs doesn't mentions `id`, `name` and `className` as accepted Locator Strategies.

Several performance tests involving all the locators resonates that locating elements through `id` and `name` locators are way ahead in terms of performance.

Is there a reason not to prefer those?

**Comment by andreastt** [comment]
This keeps the specification simple as these can be implemented using the CSS selector, which maps down to `querySelector`/`querySelectorAll`.

**Comment by Auto81** [comment]
Digging this up as It's the only place I can find with reasoning behind those locators not making it into the spec. 

Interesting to know the reasoning behind the decisions, i'm sure others may find the same as W3C spec is becoming more enforced

Moved slightly in the spec [12.3.1 Locator strategies](https://w3c.github.io/webdriver/#locator-strategies)
