### ISSUE TITLE
Text error under section "15.2 Executing Script"

### ISSUE THREAD

**Issue by emanlove** [w3c/webdriver#1052]
Under section "15.2 Executing Script" within step "2. Jump to..." the third item reads as

```
If value if value is an Array object or an Object object: 
```

for which I think it is supposed to read as

```
If value is an Array object or an Object object: 
```

removing the second `if value` text.

**Comment by shs96c** [comment]
I think this got fixed when @AutomatedTester rewrote the execute script section
