### ISSUE TITLE
Link to JSON Serialize for WindowProxy and Element is wrong/misleading.

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#1078]
In chapter [15. Document Handling](https://w3c.github.io/webdriver/webdriver-spec.html#executing-script#x15.-document-handling), section [15.2 Executing Script](https://w3c.github.io/webdriver/webdriver-spec.html#executing-script#x15.2-executing-script):
> a WindowProxy object
> 
>     If the associated browsing context of the WindowProxy object in value has been discarded, return error with error code stale element reference.
> 
>     Otherwise return success with the JSON serialization of value. 

This should link to "The JSON serialization of the WindowProxy object" directly. Expecting implementors to work out that we are patching the JSON serializer beyond the referenced ECMAScript spec is too much. Similarly for Element.

**Comment by shs96c** [comment]
The link is meant to go there, but doesn't. I'll fix.

**Comment by andreastt** [comment]
Thanks for fixing, Simon. This was an omission on my part.
