### ISSUE TITLE
"get a known element" doesn't specify which list of known elements

### ISSUE THREAD

**Issue by gsnedders** [w3c/webdriver#1080]
Current text:

> Each browsing context has an associated list of known elements. When the browsing context is discarded, the list of known elements is discarded along with it.
>
> To get a known element with argument reference, let element be the known element which web element reference matches reference. If there are none, return error with error code no such element. If element is stale, return error with error code stale element reference. Otherwise return success with element.

Notably, "get a known element" doesn't define which list of known elements needs to be searched for `reference`. As such, one (e.g., me) could argue you could "get a known element" from any extant browsing context. ☺️

We probably want something like, "let element be the current browsing context's known element".

As I understand it from @shs96c we also want the following to be true: 'Basically, if "Find Element" could return the element, then it's valid'. This would imply we want something like, "If the element is not [connected](https://dom.spec.whatwg.org/#connected) to the current browsing context's active document, return error with error code no such element." I think we'd want that in addition to the previous "let" amendment (because that tells us what list we're looking in).

**Comment by shs96c** [comment]
Closed via efc891d192bd4f4efc360b07a6d6bab15506cc50

**Comment by andreastt** [comment]
I think it’s fine to change it to say “the current browsing context’s known element”, but I’d just like to point out that an web element reference is supposed to be unique across _all_ browsing contexts, so an implementation can technically have a single store of known elements.

**Comment by shs96c** [comment]
It is correct to say that, but using an element shouldn't mysteriously change the command context.
