### ISSUE TITLE
JSON List reference to ECMAScript is misleading

### ISSUE THREAD

**Issue by Debanjan-B** [w3c/webdriver#1082]
[WebDriver W3C Candidate Recommendation 01 September 2017](https://w3c.github.io/webdriver/webdriver-spec.html#get-window-handles) mentions `The Get Window Handles command returns a` **`list of window handles`** `for every open top-level browsing context. The order in which the window handles are returned is` **`arbitrary.`** Next it is mentioned `Let handles be a JSON List` which have a reference to [ECMAScript® Language Specification](http://www.ecma-international.org/ecma-262/5.1/#sec-8.8) which mentions `Values of the List type are simply` **`ordered`** `sequences of values`

In chapter [10. Command Contexts](https://w3c.github.io/webdriver/webdriver-spec.html#get-window-handles#x10.-command-contexts), section [10.4 Get Window Handles](https://w3c.github.io/webdriver/webdriver-spec.html#get-window-handles#x10.4-get-window-handles):
> 
> 

So it seems there is a mismatch between `WebDriver W3C Candidate Recommendation` and the referenced document `ECMAScript® Language Specification` , regarding what should be the return type of `getWindowHandles()` method, whether **`an arbitrary List`** or a **`ordered List`**.

**Comment by andreastt** [comment]
ECMAScript does not actually define JSON at all, even if they share many of the same data types. For example a JSON List is represented by an Array in ES. I think referencing ECMAScript here is probably not the best idea.

Can [RFC7159](https://tools.ietf.org/html/rfc7159) be trusted?

**Comment by shs96c** [comment]
While the datatype used for storing the list of handles may be ordered by insertion, the order in which the WebDriver implementation iterates over the window handles to insert them has no requirement to be stable. The ordering is arbitrary.

**Comment by Debanjan-B** [comment]
Thanks a lot @andreastt  and @shs96c  for the quick clarification.
