### ISSUE TITLE
Make clear that window.print user prompt 

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver#1090]
Via https://github.com/mozilla/geckodriver/issues/925 we got a report that geckodriver doesn't work for `window.print` dialogs. And that is expected because we cannot handle this OS-wide dialog. Interestingly our spec mentions this as a valid user prompt. I think we should get this clarified or removed.

https://w3c.github.io/webdriver/webdriver-spec.html#user-prompts

**Comment by andreastt** [comment]
I can’t find a reference to `window.print` as a “valid user prompt”?

**Comment by whimboo** [comment]
```
The current user prompt is said to be the active user prompt, which can be one of the entries on the table of simple dialogs, or the window.print dialog.
```

**Comment by andreastt** [comment]
Sorry, I see the example to `window.print` further down. We should remove that.
