### ISSUE TITLE
question about minimizing windows

### ISSUE THREAD

**Issue by jlipps** [w3c/webdriver#1098]
In chapter [10. Command Contexts](https://w3c.github.io/webdriver/webdriver-spec.html#maximize-window#x10.-command-contexts), section [10.7 Resizing and Positioning Windows](https://w3c.github.io/webdriver/webdriver-spec.html#maximize-window#x10.7-resizing-and-positioning-windows):
> Return success with the JSON serialization of the current top-level browsing context’s window rect.

I'm just curious: after a window has been minimized, I'm assuming it is no longer the "current top-level browsing context". Is that correct? If so, what about the scenario where there is no longer any current top-level browsing context. For example, I can minimize my Chrome browser window and still have the Chrome app active, and yet browserless (until I open a window). What should this command return then? What would the rect look like?

**Comment by shs96c** [comment]
We never change the command context unless the user requests it. That is,
the minimised window remains the "current top-level browsing context".

The returned rect is window manager specific in this case. I'd imagine it's
likely to have zero height. There's an open issue about being able to get
the current window state.

**Comment by andreastt** [comment]
The _current top-level browsing context_ is a WebDriver state associated with the session, and it is only updated when the user explicitly switches to another top-level browsing context.

I think you will find that most WMs will not resize the window when it is iconified as to not trigger repaints–the window is simply hidden from view. I would be surprised if the returned rect isn’t what it was before the window got minimised, but as Simon points out, this is WM specific. The specification assumes different systems have different characteristics.

(By the way, in the past we made a decision to keep discussions and questions to the mailing list and use the GitHub issue tracker for issues, so I’m closing this.)

**Comment by jlipps** [comment]
makes sense! thanks. i'll use the mailing list for things i'm not sure are issues moving forward.
