### ISSUE TITLE
question about locator strategy table

### ISSUE THREAD

**Issue by jlipps** [w3c/webdriver#1099]
In chapter [12. Element Retrieval](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-find#x12.-element-retrieval), section [12.1 Locator Strategies](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-find#x12.1-locator-strategies), there is a table with a `State` column. The same word appears in the description:

> The following table of location strategies lists the keywords and states defined for this attribute

I am curious what "state" is supposed to mean here. After reading through the "Element Retrieval" section, I couldn't find any other reference to this term, and nothing to indicate that there is actually any state being saved to do with a locator strategy.

So I wanted to ask if this is a simple typo and should be "strategy"? If not, can someone help me understand what it means for this attribute to have a "state"? Is it just a way of labeling the keyword?

**Comment by andreastt** [comment]
It is an [enumerated attribute](https://html.spec.whatwg.org/#enumerated-attribute), which you can read more about in the HTML specification. Keywords are mapped to a state if they are found, but the default element location strategy state is a [missing value default](https://html.spec.whatwg.org/#missing-value-default). Additionally, if the locator strategy can not be found, it will be an [invalid value default](https://html.spec.whatwg.org/#invalid-value-default).

**Comment by jlipps** [comment]
wow! ok. thanks for the explanation.
