### ISSUE TITLE
question about 'locator strategies' section header

### ISSUE THREAD

**Issue by jlipps** [w3c/webdriver#1100]
In chapter [12. Element Retrieval](https://w3c.github.io/webdriver/webdriver-spec.html#locator-strategies#x12.-element-retrieval), section [12.1 Locator Strategies](https://w3c.github.io/webdriver/webdriver-spec.html#locator-strategies#x12.1-locator-strategies), the heading is "Locator Strategies". However this term is never used in the text itself; instead "location strategy" or "element location strategy" is used in the body. Should the heading be updated to reflect this usage so readers are not left wondering if there is a reason for the difference? (Or perhaps a note about how both terms are in use and mean the same thing?)

**Comment by andreastt** [comment]
The header talks about the idea in plural, which I don’t find so odd. This is in line with other sections such as ‘User Prompts’, ‘Cookies’, ‘Resizing and repositioning windows’, et al.

In any case, patches accepted for making the text more stylistically coherent.

**Comment by jlipps** [comment]
fair enough! i don't mind it myself (in fact i use "locator strategy" when i talk, not "location strategy"), just wasn't sure if part of being an official spec was a requirement for this sort of thing. if there's no spec-level motivation to change it, i like it how it is anyway.
