### ISSUE TITLE
Extend spec to allow working with SameSite cookies

### ISSUE THREAD

**Issue by aldaris** [w3c/webdriver#1134]
Currently the web driver spec does not expose SameSite cookies in any way. Given that the flag isn't supported by all web browsers, I wonder if it would be possible to at least expand the spec to allow optional representation of the SameSite flag in cookie requests/responses.

**Comment by whimboo** [comment]
Here just a link to the I think latest draft:
http://httpwg.org/http-extensions/draft-ietf-httpbis-cookie-same-site.html

**Comment by aldaris** [comment]
The above link no longer seems to work, see https://tools.ietf.org/html/draft-west-first-party-cookies-07 instead.

**Comment by christian-bromann** [comment]
This landed in #1473. The issue can be closed.

**Comment by whimboo** [comment]
Note that there is still an open issue, but that got moved to #1474.
