### ISSUE TITLE
Clarify the expected behavior when an alert is shown in the middle of a script execution

### ISSUE THREAD

**Issue by carlosgcampos** [w3c/webdriver#1153]
The spec says:

> The rules to execute a function body are as follows. The algorithm will return success with the JSON representation of the function’s return value, or an error if the evaluation of the function results in a JavaScript exception being thrown or at any point during its execution an unhandled user prompt appears.

> If at any point during the algorithm a user prompt appears, the user prompt handler must be invoked. If its return value is an error, it must immediately return with that error and abort all subsequent substeps of this algorithm.

It explicitly says the subsequent substeps, so the current step that is the script execution itself should not be aborted according to the spec. So, for example:

<pre>
execute_script("window.alert(\"Hello World\");window.alert(\"Good bye\");"
switch_to_alert().accept()
</pre>

is showing the second alert in both firefox and chrome. If the expected behavior was to abort the script execution too then the second alert should not be shown.

**Comment by andreastt** [comment]
This should be fixed by https://github.com/w3c/webdriver/pull/1248.

**Comment by shs96c** [comment]
The spec doesn't say anything about what should happen to the JS engine in the browser, so this behaviour is currently undefined. The most inclusive way of implementing this is to say that the underlying script behaves as if the user had handled the prompt, which implies we'll need to handle both of the alerts.

**Comment by whimboo** [comment]
During TPAC we discussed this issue. Here an overview: https://www.w3.org/2018/10/26-webdriver-irc#T14-35-50

Most of the drivers (geckodriver, chromedriver, safaridriver, and probably Edge) support immediately aborting the currently running script if a user prompt appears, and as such seem to currently fail running the `webdriver` test because it was written for the IE driver:

https://wpt.fyi/results/webdriver/tests/execute_script/execute.py?label=experimental

As @shs96c already mentioned above we should make it more clear in the spec that the script has to be aborted immediately when a user prompt opens.

**Comment by whimboo** [comment]
Also CC'ing @JohnChen0 who actually works on the chromedriver code. Maybe he can have a look at my last comment and run the check with chromedriver and Chrome? Thanks

**Comment by JohnChen0** [comment]
The behavior of Chrome/ChromeDriver is similar to geckodriver/Marionette. Calling `window.alert` from JavaScript code causes `execute_script` to return immediately. Once `alert.accept()` closes the user prompt, the JavaScript code continues executing from the point of `window.alert` call.

**Comment by andreastt** [comment]
@whimboo It sounds to me like this warrants a change to the WebDriver prose.

cc @jimevans

**Comment by whimboo** [comment]
Thanks @JohnChen0! This is helpful feedback. So yes, we want to get this addressed in the spec, and I will see that I can do it the next days.

**Comment by whimboo** [comment]
Fixed by PR #1572.
