### ISSUE TITLE
Typo in section 9.1 Go

### ISSUE THREAD

**Issue by mtrea** [w3c/webdriver#1175]
In chapter [9. Navigation
    ](https://www.w3.org/TR/webdriver/#get-current-url#h-navigation), section [9.1 Go
      ](https://www.w3.org/TR/webdriver/#get-current-url#h-go):
> are to be hinder

This should say "are to hinder", e.g. "If the session is not in a secure TLS state, no certificate errors that would normally cause the user agent to abort and show a security warning are to hinder navigation to the requested address."

**Comment by tomhukins** [comment]
This was fixed in 029e605

**Comment by whimboo** [comment]
@andreastt can you please close this issue based on the last comment? Thanks.
