### ISSUE TITLE
Element Click allows <option disabled> to be selected

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#1187]
It was reported to us in https://github.com/mozilla/geckodriver/issues/1107 that the [Element Click](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-element-click) command lets you select `<option disabled>`.

It’s not clear to me what the expected behaviour is. Since we don’t check disabled/readonly for any other elements when clicking, I’m guessing WebDriver should return silently and not change the element’s selectedness?

**Comment by barancev** [comment]
A user can't select a disabled option, neither with the mouse nor with the keyboard. So I suppose Selenium should not be able to select it too. Yes, a user can click a disabled option, but this action does not change the selected element, it's effectively a no-op.

**Comment by andreastt** [comment]
Thanks for the clarification on behaviour. Just checking it is not meant to return an error when trying to click a disabled element.

**Comment by whimboo** [comment]
Please note that there is a difference between a select with and without the multiple flag. For multiple selects a disabled option can receive focus, while for the others it doesn't work. Here an example jsbin: https://jsbin.com/zebisixudu/1

**Comment by barancev** [comment]
@whimboo In this sample the disabled option can take focus but it still can't be selected.

(By the way, in Chrome and IE it can't take focus even in multi-select, it's Firefox specific behavior)

**Comment by whimboo** [comment]
Interesting. I filed a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1429350) for that.
