### ISSUE TITLE
Element Interaction commands do not handle user prompts

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver#1191]
The following commands do not list handling of user prompts:

https://w3c.github.io/webdriver/webdriver-spec.html#element-click
https://w3c.github.io/webdriver/webdriver-spec.html#element-clear

**Comment by andreastt** [comment]
I vaguely remember there was a reason why they don’t, but I can’t think OTOH why that was.

**Comment by whimboo** [comment]
If even Element retrieval commands (issue #1121) will get this check, element interaction commands should really have it. With a user prompt open both commands wouldn't work at all.

**Comment by andreastt** [comment]
Summoning @shs96c.

**Comment by whimboo** [comment]
Can someone please adjust the labels? I don't have the permission.
