### ISSUE TITLE
syntax issue: ellided > elided

### ISSUE THREAD

**Issue by kool79** [w3c/webdriver#1198]
In chapter [7. Capabilities
    ](https://www.w3.org/TR/webdriver/#dfn-merging-capabilities#h-capabilities), section [7.2 Processing Capabilities
      ](https://www.w3.org/TR/webdriver/#dfn-merging-capabilities#h-processing-capabilities):
> ellided,

**Comment by jugglinmike** [comment]
This was resolved via gh-1224

**Comment by whimboo** [comment]
Can someone please close the issue? I don't the permissions. Thanks.
