### ISSUE TITLE
Error: unknown command: /session/{session id}/element/{element id}/screenshot

### ISSUE THREAD

**Issue by tuyetngo** [w3c/webdriver#1200]
1. Between source about API elementIdScreenshot [https://github.com/webdriverio/webdriverio/blob/master/lib/protocol/elementIdScreenshot.js](url) and the document on the http://webdriver.io/api/protocol/elementIdScreenshot.html
-> I think the document is missing argument ID for that API
2. Execute test with API elementIdScreenshot, it returns an error:

**The script:**
> const screenshootFolder = images/${page}
>   prepareFolderSync(screenshootFolder)
>   const result = this._browser.element(elements[ele])
>   this._browser.elementIdScreenshot(result.value.ELEMENT)

**The error:**
`Error: unknown command: session/b42d1638c70a2aed80c8003398eb4c5a/element/0.9460012670892941-21/screenshot
    at elementIdScreenshot("0.9460012670892941-21") - index.js:307:3`

**Comment by andreastt** [comment]
This repo tracks the WebDriver standard, not the WebDriverIO client.
