### ISSUE TITLE
Integer values in timeouts and cookie expiry time

### ISSUE THREAD

**Issue by carlosgcampos** [w3c/webdriver#1202]
Timeout values and cookies expiry time are expected to be positive integer numbers less than 2^64. This can cause problems in the implementations when parsing those values from JSON, since browsers don't allow such a big values. We should set a limit that browsers can handle, like for example 2^53 - 1, which is the maximum safe integer defined by ECMA. This is already covered by test  create_alwaysMatch.py::test_valid[timeouts-value10] that is currently failing in Firefox and WebKit.

**Comment by jgraham** [comment]
Sounds reasonable.
