### ISSUE TITLE
Example of possible "actions" objects in specs?

### ISSUE THREAD

**Issue by mercmobily** [w3c/webdriver#1206]
This is not an issue with the specs. I  was just hoping somebody could please lend a hand.
I am nearly finished implementing a simplified API for the webdriver, since I feel that the current implementations are over-engineered.

I am stuck at [actions](https://w3c.github.io/webdriver/webdriver-spec.html#actions). I am trying to figure out what my library should send, and am getting really quite confused. My next step is to look at the code of existing libraries, or going as far as getting one of those libraries to make a call on a server.

But... is anybody here aware of some examples of *actual* data that would be sent to the endpoint `POST /session/{session id}/actions`, to give me at least the hint of practical data sent to the driver? I think adding such information would be _immensely_ beneficial too...

Sorry about the noise. I am just banging my head against a wall and have been for quite some time...!

**Comment by andreastt** [comment]
I think the spec text could do with better examples of the action payload but unfortuantely I don’t have time to write them. Maybe a mediocre substitute would be to look at the [action tests](https://github.com/w3c/web-platform-tests/tree/master/webdriver/tests/actions) in WPT or at the output of geckodriver (pass `--webdriver-arg='-vv'` to wptrunner).

**Comment by mercmobily** [comment]
I just hacked Selenium a little so that it shows any request it makes, and ran the full tests. I think I got what I was looking for :D 

Now it's a matter of re-read the specs, trying to make sense of them, and then find the easiest, most down-to-earth way of getting a developer to create a set of actions easily!

(If you have any pointers to documentation that explains the nitty-gritty of the parallel timing,  I will build a statue :D )

I will make sure I make a Pull Request with simple examples as soon as I actually understand all of this.

Closing it to avoid pollution, since it doesn't add to the project. Thanks for answering and for the inspiration...

    REQUEST: Request {
      method: 'POST',
      path: '/session/22aeab17-11bc-482c-acd2-34ca1f429cc1/actions',
      data: 
       { actions: 
          [ { actions: 
               [ { type: 'pause', duration: 0 },
                 { type: 'pause', duration: 0 },
                 { type: 'pause', duration: 0 },
                 { type: 'keyDown', value: 'f' },
                 { type: 'keyUp', value: 'f' },
                 { type: 'keyDown', value: 'o' },
                 { type: 'keyUp', value: 'o' },
                 { type: 'keyDown', value: 'o' },
                 { type: 'keyUp', value: 'o' },
                 { type: 'keyDown', value: 'b' },
                 { type: 'keyUp', value: 'b' },
                 { type: 'keyDown', value: 'a' },
                 { type: 'keyUp', value: 'a' },
                 { type: 'keyDown', value: 'r' },
                 { type: 'keyUp', value: 'r' } ],
              type: 'key',
              id: 'default keyboard' },
            { actions: 
               [ { type: 'pointerMove',
                   origin: 
                    { 'element-6066-11e4-a52e-4f735466cecf': 'b4def06e-66bc-4fe7-9190-a128b920479d',
                      ELEMENT: 'b4def06e-66bc-4fe7-9190-a128b920479d' },
                   duration: 100,
                   x: 0,
                   y: 0 },
                 { type: 'pointerDown', button: 0 },
                 { type: 'pointerUp', button: 0 },
                 { type: 'pause', duration: 0 },
                 { type: 'pause', duration: 0 },
                 { type: 'pause', duration: 0 },
                 { type: 'pause', duration: 0 },
                 { type: 'pause', duration: 0 },
                 { type: 'pause', duration: 0 },
                 { type: 'pause', duration: 0 },
                 { type: 'pause', duration: 0 },
                 { type: 'pause', duration: 0 },
                 { type: 'pause', duration: 0 },
                 { type: 'pause', duration: 0 },
                 { type: 'pause', duration: 0 } ],
              parameters: { pointerType: 'mouse' },
              type: 'pointer',
              id: 'default mouse' } ] }
