### ISSUE TITLE
URL blocking / ad blocking

### ISSUE THREAD

**Issue by alexanderadam** [w3c/webdriver#1234]
The webdriver standard represents a part of the web testing activity. And developers want to test things that are common things that happen in the real life.

One of the most common things in the web is, that people control is the display of ads (or other elements / scripts such as webminers) with the help of adblockers like [uBlock Origin](https://en.wikipedia.org/wiki/UBlock_Origin) and similar ones. Browsers like [Firefox](https://www.mozilla.org/en-US/firefox/features/adblocker/), [Google Chrome and Chromium](https://www.chromium.org/testing-chrome-ad-filtering), [Brave](https://support.brave.com/hc/en-us/articles/360022973471-What-is-Shields-), Safari or [Opera](https://www.opera.com/de/features/ad-blocker) even have functionality like this integrated natively (the same goes for many testing solutions, [i.e. when using Chrome 84 or newer](https://developers.google.com/web/updates/2020/05/heavy-ad-interventions) or [puppeteer](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-adblocker#puppeteer-extra-plugin-adblocker---)).

Since this is so common, it should obviously be tested properly. Developers want to know how an application or website reacts when people are visiting it with adblock functionality enabled.
That is why I believe it should be integrated in the webdriver standard as well.

**Comment by alexanderadam** [comment]
I guess defining a standardized way of blocking elements in user agents.

I'm not sure how this would look like as well but [@barancev suggested](https://github.com/SeleniumHQ/selenium/issues/5532#issuecomment-368319636) opening an issue for webdriver regarding content blocking and I thought you guys might rather know what to do. :wink:

**Comment by andreastt** [comment]
We can certainly consider it, but I’m not sure there’s a good way of defining what it means to block a URL in web platform terms. It might be possible for resources loaded in HTML, but not generally for any UA resource.

**Comment by shs96c** [comment]
I'm not sure how meaningful this is. Most of the drivers out there allow you to install extensions (such as adblockers), so there's no need to bake it into this specification. There are some browsers implementing some form of cookie control or adblocking, and the developers of those browsers can use this spec "as is".

**Comment by hugobast** [comment]
Going to add to this conversation with the _why?_ (for me). I think [this blog post from ThoughtBot](https://robots.thoughtbot.com/speed-up-javascript-capybara-specs-by-blacklisting-urls#a-better-way) does a really good job of explaining why we might want this feature.

**Comment by black-snow** [comment]
As for me the **WHY** is to not generate $$ for Google when testing pages containing google maps.
*IMHO* this is a must.

**Comment by alexanderadam** [comment]
> Most of the drivers out there allow you to install extensions (such as adblockers), so there's no need to bake it into this specification.

1. Well, Selenium is following the the W3C webdriver and doesn't integrate it, because it's not specified.
2. I would also be open for a specification that describes the integration of extensions. But I have the feeling that this might be much more complex.

**Comment by JG127** [comment]
What I could imagine is that the driver would map urls to different resources. This way the test could use a test version of JS, download lighter static content from a local source, similar to mocking by simulation of an external source...

**Comment by StephanBijzitter** [comment]
This would also make testing of offline functionality in PWAs much more easy. In my specific case, I've wrapped all my `fetch` calls into a helper function that looks a lot like: `return window.__offline ? new Response(...) : fetch(...)`, but that doesn't stop external scripts, images or the service worker from using the network, so it's a bit... meh.

**Comment by Dr10s** [comment]
Just use --host-resolver-rules  for chrome.

**Comment by alexanderadam** [comment]
> Just use --host-resolver-rules for chrome.

This repository is _not_ about certain ways to achieve this with a particular driver.
This repository is about the WebDriver standard and describes [a platform- and language-neutral wire protocol to remotely instruct the behaviour of web browsers](https://github.com/w3c/webdriver#webdriver-standard).

**Comment by alexanderadam** [comment]
It's 2024 now and I stopped using Selenium in all of my projects and switched to other drivers.
However, I think that this issue is still relevant — maybe now more than ever —  especially since blocking ads is nowadays a widely used feature in pretty much every user agent.

Or how it's put [in this article](https://www.theregister.com/2024/03/27/america_ad_blocker/):

> According to a survey of 2,000 Americans conducted by research firm Censuswide, on behalf of Ghostery, a maker of software to block ads and online tracking, [52 percent of Americans](https://www.ghostery.com/blog/privacy-report-advertisers-and-adblockers) now use an ad blocker, up from 34 percent according to 2022 Statista data.

And while blocking ads was mainly just supported via extensions [when I created this issue in 2018](https://github.com/w3c/webdriver/issues/1234#issue-300054299), it is nowadays even integrated natively in certain user agents.

**Comment by whimboo** [comment]
@alexanderadam In WebDriver BiDi we allow to [add network interceptions](https://w3c.github.io/webdriver-bidi/#command-network-addIntercept) which can be used to block certain network requests and as such for blocking elements to be loaded at all. Does that satisfy your needs?

Please note that such a feature cannot be done for the WebDriver classic protocol due to limitations of the protocol.

**Comment by whimboo** [comment]
I'm going to close this issue in favor of the mentioned network interception feature of WebDriver BiDi. If that doesn't fit your needs please explain what's missing. Thanks.

**Comment by alexanderadam** [comment]
It might be relevant for others that this might also overlap with [webdriver bidi issue 403](https://github.com/w3c/webdriver-bidi/issues/403), which is about extensions and this is the usual way of having adblocking functionality in users browser.

It's still a pity that it took so long although browser extension were introduced with Firefox in 2004, there was no real webdriver specification for most of its existence until [this PR in 2023](https://github.com/w3c/webdriver-bidi/pull/421).

But I guess better late than never. :wink:

**Comment by whimboo** [comment]
Please note that there is also a way for WebDriver classic to install addons. It's just not part of the specification and each vendor handles it via extension commands. So the benefit with BiDi is that the command is now officially spec'ed.
