### ISSUE TITLE
Should WebDriver return from a navigate that causes a download before the download is finished

### ISSUE THREAD

**Issue by InstyleVII** [w3c/webdriver#1244]
Right now both Firefox/Edge will wait for a download to finish before returning from a navigate command that forces a download while Chrome will close the browser. There are two questions from my perspective:

1. Should the navigate command return once the download has kicked off?
2. Should quit cancel any in-progress downloads?

**Comment by andreastt** [comment]
I don’t think Firefox waits for the download to finish, but we may have a bug to deal with a link potentially triggering the download dialogue.

Whether ending the session should cancel downloads is outside the scope of the spec, but I would find it surprising if asking for the session to be deleted would pend on a potentially indefinite download in-progress.

**Comment by InstyleVII** [comment]
Why would it be outside the scope of the spec? It appears from my perspective to be an interop issue that could cause failures between browsers so it would be worth adding some verbiage like "cancel any remaining downloads" to the Delete Session command.

**Comment by InstyleVII** [comment]
@AutomatedTester Thoughts on this? I feel like we should define some expected behavior for browsers to conform to.

**Comment by AutomatedTester** [comment]
I don't think we need to add anything since this is roughly covered under the privacy considerations as this about being under a profile. There is also a lot of best practises telling people to never download during webdriver session I think we can leave this as undefined.
