### ISSUE TITLE
Need a browser.frame() variant that uses getSVGDocument() instead of contentDocument to work with svg embedded documents; no way to click on elements in an <svg> inside an <embed> tag

### ISSUE THREAD

**Issue by osmolyar** [w3c/webdriver#1266]
## The problem

There is currently no way (with webdriverio) to click on elements inside an <svg> element inside of a #document in an \<svg\>  \<embed\> tag, wuth html as seen in example #3 at http://srufaculty.sru.edu/david.dailey/javascript/frames/objectTest.html.

The elements inside the svg are not accessible to Selenium/Webdriverio because they are not in the main document DOM but are relative to the #document inside the embed tag.  Any attempt to access them normally results in 'element not found'.

Trying to use browser.execute as described in examples #2 or #4 at http://aksahu.blogspot.com/2015/05/dealing-with-object-tags-in-selenium-webdriver.html doesn't work for webdriverio either (using getSVGDocument() in place of .contentDocument); any variant of example #2, using a JS click() inside the execute script, results in a "***.click() is not a function" error, even though the element the click is being called on is retrieved successfully either manually in the console via the same command or at runtime.

Trying to use variant #4, first retrieving the element into a variable and then calling browser.elementIdclick() on its .value.ELEMENT results in a "Element is no longer attached to the DOM" error, I assume because it is looking for the element relative to the main document again.

Trying to use browser.frame to switch to the 2nd 'document' as if it's a frame doesn't work either, giving  the error  "no such frame: element is not a frame" Error: A request to switch to a frame could not be satisfied because the frame could not be found.[chrome #0-0]     at frame([object Object])".

This should be supported via an analog to browser.frame() that allows switching to a document that is not defined inside an IFrame, e.g., using "getSVGDocument()" to switch to the internal document frame instead of "contentDocument" (or some other way).

My understanding is that Webdriverio depends on WebDriver's browser.frame command, hence submitting the request here.

See also https://github.com/webdriverio/webdriverio/issues/2753 

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 8.9.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):  standalone
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

## Details

Describe in more detail the problem you have been experiencing, if necessary.

In addition to the above information, here are examples of the code used in the described attempts. 

html is like:
 `<embed` style="overflow:hidden;" id="frame_15" type="image/svg+xml" src="%25ZEN.SVGComponent.svgPage.cls?$HEIGHT=100%25&$NAMESPACE=%25SYS&$PAGECLASS=%25CSP.UI.Portal.User&$PARENTIDX=15&$SVGCLASSES=%25ZEN.SVGComponent.tabBar%2C%25CSP.UI.Portal.User&$USERSVGPACKAGES=&$WIDTH=100%25" height="32" width="1300">
#document== $0
xml-stylesheet
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="zenRoot" x="0" y="0" width="1300" height="32" onload="zenLoad();" onunload="zenUnload();" zoomAndPan="disable">`

Example browser.execute command used:
browser.execute("return (document.getElementById('frame_15').getSVGDocument().getElementsByTagName('g')[8]).click()")

(says "document.getElementById('frame_15').getSVGDocument().getElementsByTagName('g')[8]).click() is not a function" even though typing document.getElementById('frame_15').getSVGDocument().getElementsByTagName('g')[8] into the console correctly retrieves the element, and the correct element id is output if logged while running script)

var tab =browser.execute("return (document.getElementById('frame_15').getSVGDocument().getElementsByTagName('g')[8])",this.elements.embedFrame);
       var  tabValueId=tab.value.ELEMENT;
       console.log(JSON.stringify(tabValueId));
       browser.elementIdClick(tabValueId);

(says "Error: An element command failed because the referenced element is no longer attached to the DOM.")

Or: 

var myFrame=browser.execute("return (document.getElementById('frame_15').getSVGDocument())");
console.log(JSON.stringify(myFrame));
browser.frame(myFrame.value);
  //      Error: An element command failed because the referenced element is no longer attached to the DOM.
  //          at frame([object Object])

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
I think we should align the solution we decide in https://github.com/w3c/webdriver/pull/1320 for this too. These usecases look similar.

**Comment by jgraham** [comment]
Implementation-wise `<embed>` works much more like `<iframe>`; the content is an actual nested browsing context, not a "shadow" tree that's actually part of the same DOM. That has meaningful consequences, notably that you can navigate the document in `<embed>` but navigations in shadow dom apply to the entire page.

Therefore I think the request to treat this like other child browsing contexts is the correct approach.

**Comment by osmolyar** [comment]
This works in webdriver I believe, but not in webdriverio.  E.g., this works in Webdriver

SingletonInstancesRepo.getCurrentWebDriver().switchTo().frame(element);

where element is the embed element in the svg frame.  

Updating original webdriverio ticket https://github.com/webdriverio/webdriverio/issues/2753 accordingly.

**Comment by osmolyar** [comment]
For the record, this attempt at a 'jQuery click', which according to https://github.com/FuckTheWorld/chromedriver/issues/427#issuecomment-123233293 is a workaround to the ```Cannot read property 'scrollLeft' of null``` seen when clicking on any elements inside the svg frame after switching to the embed frame

```$('circle').click();```

 results in the same error, ```"Cannot read property 'scrollLeft' of null"``` as variants of  

```browser.click('circle')``` 
or 
```browser.elementIdClick(tabValueId)```
[svg.zip](https://github.com/webdriverio/webdriverio/files/3247838/svg.zip)

{"ELEMENT":"0.7111316441544397-1"}

https://github.com/admc/wd/issues/182#issuecomment-25242142

https://github.com/admc/wd/issues/182#issuecomment-25226537
