### ISSUE TITLE
Specifying the same file more than once for <input type=file multiple> should be an invalid input

### ISSUE THREAD

**Issue by burg** [w3c/webdriver#1268]
In chapter [14. Element Interaction](https://w3c.github.io/webdriver/#element-send-keys#x14-element-interaction), section [14.3 Element Send Keys](https://w3c.github.io/webdriver/#element-send-keys#x14-3-element-send-keys):
> if multiple is false and the length of files is not equal to 1, return an error with error code invalid argument.

In every UA I've ever used, the file selection dialog does not allow to select the same file more than once for <input type=file multiple>. There is no validation that the file names have no duplicates. I think trying to set the same file more than once should be considered an invalid input (HTTP 400). This validation would happen on every Element Send Keys, so it could be triggered by sending the input 'foo.txt\nfoo.txt' or separate Element Send Keys commands (i.e., to append the same file twice).

**Comment by andreastt** [comment]
I can be sympathetic to adopting this check.

**Comment by whimboo** [comment]
Given that we want to have a new command for uploads (see issue #1355) should we still add this to the `Element Send Keys` implementation?

**Comment by andreastt** [comment]
I don’t think we do. Let’s make sure we do add a check or a de-duper as part of the new command though.
