### ISSUE TITLE
WebDriver Specs doesn't mentions about defaultContent() 

### ISSUE THREAD

**Issue by Debanjan-B** [w3c/webdriver#1272]
In chapter [10. Command Contexts](https://w3c.github.io/webdriver/#switch-to-parent-frame#x10-command-contexts), section [10.5 Switch To Frame](https://w3c.github.io/webdriver/#switch-to-parent-frame#x10-5-switch-to-frame):
> Switch To Frame

The following two endpoints are covered:

- `/session/{session id}/frame`
- `/session/{session id}/frame/parent`

Where as in the Java Docs of [WebDriver.TargetLocator](http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebDriver.TargetLocator.html) apart from:

- [`WebDriver parentFrame()`](http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebDriver.TargetLocator.html#parentFrame--)
- [`WebDriver frame(int index)`](http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebDriver.TargetLocator.html#frame-int-)
- [`WebDriver frame(java.lang.String nameOrId)`](http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebDriver.TargetLocator.html#frame-java.lang.String-)
- [`WebDriver frame(WebElement frameElement)`](http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebDriver.TargetLocator.html#frame-org.openqa.selenium.WebElement-)

The following is also documented:

- [`WebDriver defaultContent()`](http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebDriver.TargetLocator.html#defaultContent--)

So `WebDriver defaultContent()` should be in the specs too or are we going to deprecate it?

**Comment by andreastt** [comment]
Switching to the current top-level browsing context is handled by passing null to Switch To Frame. See the first substep under step 5 here: https://w3c.github.io/webdriver/#switch-to-frame

Does that answer your question?

**Comment by Debanjan-B** [comment]
Thanks @andreastt Well, that is a point. But I think there is still a **void** while relating `id is null` to `defaultContent()`

**Comment by andreastt** [comment]
You are confusing the Java client’s API and the primitives of the WebDriver protocol. `defaultContent()` in the API translates to a Switch To Frame with `{id: null}` body on the wire level.

**Comment by Debanjan-B** [comment]
@andreastt `defaultContent()` in the API translates to a Switch To Frame with `{id: null}` body on the wire level. This statement is what I am looking for. But neither the current Specs nor the Java/API Docs speaks about this. But this info is absolutely necessary. 

@shs96c @barancev @AutomatedTester @lmtierney @jimevans  Should this info be accommodated at client level?

**Comment by AutomatedTester** [comment]
This info should be accomodated in the client documentation and not in this specification. 

Please raise a bug on https://github.com/SeleniumHQ/selenium/issues

**Comment by Debanjan-B** [comment]
Thanks for the clarification and conclusion @andreastt @AutomatedTester !!!

**Comment by andreastt** [comment]
FWIW I’m not sure if it is useful to expose wire protocol level specifics in the API documentation of the client. How the client API maps down to the WebDriver primitives is an exercise for the client author.
