### ISSUE TITLE
strict find element

### ISSUE THREAD

**Issue by joerg1985** [w3c/webdriver#1278]
The current find element command behaves like a find first element command, this might be a good solution for most testing scenarious.
With the growing populaity of the webdriver protocoll this behaviour could not fit for all clients. Espacially if people are starting to build reliable automation solutions based upon the webdriver protocoll or testautomation of bussines critical applications.
In this (and maybe others) usecases there should be an option to make the webdriver fail, if there is more than one element found using find element command.

There are several possible changes to the protocoll to achieve this.
a) add a setting to change the behaviour of find element to throw a AmbiguiusException
b) rename find element to find first element and add a new find element which throws a AmbiguiusException
c) add a new strict find element command which throws a AmbiguiusException
d) don't change anything, this could be done by the client by only using find elements, check the result and throw an exception

What are your thoughts about this?
Kind regards

**Comment by andreastt** [comment]
If your concern is about the naming of _Find Element_, you are free to name the client API functions whatever you want. This specification does not put any constraints on the design of local ends.

**Comment by joerg1985** [comment]
Sorry for the late response, it is not about the naming. It is about people starting to use the protocol to automate business processes and might hit this trip hazard inside the protocol.
