### ISSUE TITLE
Proposal: Set Value of hidden <input/> elements

### ISSUE THREAD

**Issue by SetTrend** [w3c/webdriver#1281]
For automated tests across different machines, particularly for tests inspecting the robustness of malicious input, it is necessary to set hidden input fields' values on the fly during a web test.

As a side effect, hidden `<input type="file"/>` elements could also gracefully be set to local file paths.
<br/>

#### Please consider adding a feature to WebDriver, providing for setting arbitrary input elements' values.

```
POST /session/{session id}/element/{element id}/
```
```json
{ "value": "{value}" }
```

#### ... or even for setting arbitrary elements' attributes.

```
POST /session/{session id}/element/{element id}/attribute
```
```json
{ "{attribute name #1}": "{value #1}"
, "{attribute name #2}": "{value #2}"
, "{attribute name #3}": "{value #3}"
}
```

**Comment by andreastt** [comment]
The hidden `<input type=file>` problem is discussed and tracked in https://github.com/w3c/webdriver/issues/1230.

Setting other input element’s values can be done through Execute Script.
