### ISSUE TITLE
Proposal: Add facility to take a screenshot of whole document

### ISSUE THREAD

**Issue by SetTrend** [w3c/webdriver#1283]
Currently, WebDriver only allows to take a screenshot of the current viewport.

This is not sufficient when testing CSS (cascading style sheets).

Changes to a CSS rule may affect regions anywhere on the document. Even regions that have not been in the focus while performing a test recording.
<br/>

#### Please concider to add an action for taking a screenshot of the whole document (= Take Document Shot).

Following is the suggested workflow of taking a screenshot of the whole document:

1. Create a second, hidden viewport (= v²)
1. Enlarge v² horizontally to the minimum width required to avoid a horizontal scrollbar ([`Element.scrollWidth`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollWidth))
1. Enlarge v² vertically to the minimum height required to avoid a vertical scrollbar ([`Element.scrollHeight`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight))
1. Take screenshot of v²
1. Purge v²

**Comment by andreastt** [comment]
Whilst it is possible to take screenshots of the full document in certain drivers (e.g. geckodriver), we can’t standardise this because not all browsers can feasibly implement it.

**Comment by SetTrend** [comment]
@andreastt :

Why shouldn't they be able to? The second, hidden viewport - certainly - would be required to be implemented first by browsers. However, since it's hidden and only exists in memory, every browser can easily implement it. In fact, I don't know of any browser that couldn't.

As a fall-back in the - really unlikely - case of a browser not being able to render a document in memory on a second canvas, `TakeDocumentShot` could just mirror `TakeScreenShot`.

Please re-open for discussion.

**Comment by whimboo** [comment]
Isn't that just a dupe of issue #893?

**Comment by andreastt** [comment]
I don’t know why Chrome can’t support full document screenshots, but I have it on good authority that we can’t support it cross-browser.

**Comment by SetTrend** [comment]
**@whimboo:**

No, I don't think so. #893 is different.

It deals with determining the right moment to take a normal screenshot of a fully loaded page. The moment after any JavaScript/CSS animations have done their job.

IMHO, #893 is something that cannot be computed, because there is no "moment of final load". Think of rotating ads or carussels. With these, the page will never be finally loaded. See this example:

![never ending rotation](https://user-images.githubusercontent.com/9283914/43686469-e3f3a9e4-98c6-11e8-925d-122f536934ca.gif)

**Comment by SetTrend** [comment]
**@andreastt :**

The Chrome team actually is considering my suggestions:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2527

So I feel they also believe it's possible to create and save an off-screen image of whole documents.

Please re-open this issue for consideration.

<hr>

## I'd like to elaborate on the user stories here:

### User Story (1)

Testing large enterprises' web sites, you usually have a large number of test cases to test.

However, you don't want to have the tester record each and every test case over and over again on each and every device on the market. That would be a waste of time and manpower because test cases are identical for each device. They (should) only differ in screenshots and built-in file upload / file download functionality.

So in order to create a reasonable and streamlined web site test automation for testing web sites, this is the suggested workflow:

1. The tester will be recording test cases only once, on some arbitrary device:

   ![test cases](https://user-images.githubusercontent.com/9283914/43687085-d6df4958-98cf-11e8-9cb6-99f8abbfc116.png)

1. A WebDriver application will replay these recorded test cases on many devices (no matter whether it's a desktop device or mobile or whatever):

   ![devices matrix](https://user-images.githubusercontent.com/9283914/43687108-150562bc-98d0-11e8-8fcf-2799fccf77d6.png)

   In the course of doing this, the WebDriver application is supposed to take whole document images/screenshots on the corresponding device, thereby covering all parts of the rendered document on that particular device without any need to scroll the document parts into view.

   _(Without the ability to take a screenshot of a whole document this is not possible. On desktop devices, no scrolling may be required because the page fits the screen, whereas on mobile devices scrolling may be required because the page doesn't fit. In step <span>#</span>1, however, the tester recorded the test case on some arbitrary device. So the recorded test case is agnostic about any kind of scrolling.)_

1. The document images taken in step <span>#</span>2 are supposed to be saved in an ordered fashion on disk (e.g. "`${TestCaseId}/${DeviceId}/${RecordingIndex}.png`" for later reference.

1. Finally, test cases and reference images are then copied to the CI/CD pipeline. The WebDriver test runner there runs the same test cases on the same number of devices and compares the document images it takes with the reference document images taken in step <span>#</span>2. If they differ, the test fails.
## &nbsp;

### User Story (2)

A tester is supposed record a login process on a device. Currently, a screenshot may look like this:

![news-website-fake cropped screenshot galaxy s9](https://user-images.githubusercontent.com/9283914/43687373-1cdc4060-98d4-11e8-9db2-06fb6ded2173.png)&nbsp;&nbsp;&nbsp;...&nbsp;or&nbsp;like&nbsp;this&nbsp;...&nbsp;&nbsp;&nbsp;![news-website-fake cropped screenshot iphone 6](https://user-images.githubusercontent.com/9283914/43687374-205421c2-98d4-11e8-9d5f-a9abbb2d6301.png)
<br/>

#### In the course of testing the login functionality of the website, the tester is not interested or even aware of the remainder of the page.
<br/>

This is what the same page screenshot looked like if it would be taken by WebDriver using the suggested Take Whole Document Image functionality:

![news-website-fake small](https://user-images.githubusercontent.com/9283914/43687417-0f1c7692-98d5-11e8-9564-00d8a4e01afb.png)
<br/>

Later on, some design guy adds a CSS rule to the website, accidentally changing the footer's color to light green (only) on IPhones:

![news-website-fake small altered](https://user-images.githubusercontent.com/9283914/43687459-b6641bc6-98d5-11e8-9ba0-a83b12b74ca7.png)
<br/>

#### Without the requested full document screenshot ability, the designer's mistake will never be recognized. The website gets deployed and is run untils randomly some user reports its inability to read the footer.
<hr/>
