### ISSUE TITLE
Proposal: Add action to download and validate/assert document

### ISSUE THREAD

**Issue by SetTrend** [w3c/webdriver#1284]
In order to create repeatedly stable automated web tests it's crucial to be able to download and validate/assert documents from e.g. clicking a hyperlink.

#### Please concider to add an action for being able to download and compare (i.e. validate/assert) documents.

For security reasons, only a hash of the document may be returned. (A capability may control whether a whole document or only a hash will be returned for validation.)

**Comment by andreastt** [comment]
I don’t think I understand your proposal. Can you be more specific what you mean by “validation” and “comparing” documents?

WebDriver’s philosophy is to emulate user interactions with the browser as closely as possible, and getting into other functional areas that share more similarity with debugging immediately strikes me as  a scope creep, but it is possible I misunderstand what you’re after.

**Comment by SetTrend** [comment]
You may be right here. I may not draw the correct line between WebDriver and the results it retrieves.

However, there is an action called [`Get Page Source`](https://www.w3.org/TR/webdriver1/#get-page-source), delivering a serialized DOM of the current web page. This method only works for SGML documents, but not for any other content that's being retrieved by a web browser's HTTP action. When a user action results in a binary file being downloaded, I need to verify that the correct file got downloaded by the action.

This is particularly true for JavaScript MVVM frameworks, where hyperlinks are generated on the fly by JavaScript that may behave differently on different browsers.

**Comment by barancev** [comment]
Selenium does not operate "documents" or "resources", it deals with the "current page", that is the result of browser's job of downloading resources and rendering the view.

The best approach to handle interaction between a browser and a server (including assertion or modification or mocking requests) is injection of a proxy.

**Comment by SetTrend** [comment]
I understand.
