### ISSUE TITLE
HTTP status code 408 causes clients to retry

### ISSUE THREAD

**Issue by barancev** [w3c/webdriver#1287]
[Section 6.6](https://w3c.github.io/webdriver/#handling-errors) contains two error codes "script timeout"and "timeout" mapped to HTTP status code 408 Request Timeout.

It might be logically correct to use this error code, but we have a collision with HTTP semantics implemented in HTTP clients. To support keep-alive we allow retries in HTTP clients, and if a client sees code 408 it thinks that the server has gone and attempts to retry the request. As a results, we have executeScript or get/refresh duplication after timeout.

What can we do?

1) Stop using keep-alive, and hit the famous port exhaustion problem.
2) Stop using code 408 and replace it with a more neutral one that does not cause retries.

**Comment by andreastt** [comment]
Which HTTP code do you propose?

**Comment by barancev** [comment]
Unfortunately there is no HTTP code that would perfectly fit the purpose. We can use 400, as we do for the most other errors.

**Comment by barancev** [comment]
Or 500, because timeout is a server error, not a client one.

**Comment by andreastt** [comment]
I would prefer 500 over 400, since the latter gives the impression of a problem with the client’s request (e.g. malformed data or invalid arguments).

Can we get some input from @kereliuk, @burg, and @jimevans?

**Comment by andreastt** [comment]
Sorry, forgot @InstyleVII.

**Comment by burg** [comment]
I would prefer 500 over 400, per Andreas' argument.

**Comment by jimevans** [comment]
I don't know that I have a preference, but @andreastt makes a good argument. I'm perfectly happy using 500.

**Comment by andreastt** [comment]
For the interested, I also wrote a blog post about this change: https://sny.no/2018/08/webdriver-keepalive
