### ISSUE TITLE
"File a bug" link is broken

### ISSUE THREAD

**Issue by foolip** [w3c/webdriver#1288]
In https://w3c.github.io/webdriver/, the "File a bug" link points to https://github.com/w3c/issues/ (404) instead of https://github.com/w3c/webdriver/issues or https://github.com/w3c/webdriver/issues/new.

**Comment by andreastt** [comment]
It appears ReSpec defauls to gh-pages for the GitHub configuration branch, and I submitted https://github.com/w3c/webdriver/pull/1289 to correct it to master, from where we publish this specification.

In any case it didn’t fix the problem with the link. I’ve filed https://github.com/w3c/respec/issues/1803 with ReSpec.

**Comment by andreastt** [comment]
Apparently the trick is to add a slash at the end, and I’ve updated my PR to do that.

**Comment by whimboo** [comment]
I just tested it and it works fine. Can this issue be closed now?

**Comment by foolip** [comment]
Yep, someone fixed it.

**Comment by andreastt** [comment]
I fixed this in https://github.com/andreastt/webdriver/commit/a8e7c33349324ef3dc89e7b3409a1e1bad2eba5b.

Then a patch was applied upstream to ReSpec in https://github.com/w3c/respec/pull/1805.
