### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by anukodali83** [w3c/webdriver#1291]
WebDriver not able to locate elements on w3c payment sheet

**Comment by anukodali83** [comment]
Not able to move focus from the payment checkout page to w3c payment sheet page

**Comment by andreastt** [comment]
Read more about reporting actionable bugs in our [contribution guidelines].

[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs
