### ISSUE TITLE
Expose Same-Site policy in Cookie objects if present

### ISSUE THREAD

**Issue by burg** [w3c/webdriver#1304]
Several major browsers now support the Same-Site cookie property, as described here:

https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-02#section-5.3.7

 I suggest we expose in WebDriver API similarly to other cookie fields like secure or httpOnly.

New row in §16 Cookies would be as follows:

Concept | RFC 6265 Field | JSON Key | Attribute Key | Optional | Description
Cookie Same-Site policy | same-site | sameSitePolicy | 'Same-Site' | X | The same-site policy applied to this cookie. Must not be set if omitted when adding a cookie.
 Supported values in that spec are 'Strict' or 'Lax'. If it's not explicitly provided when creating a new cookie, it should not be set internally: both 'Strict' and 'lax' differ in behavior from having no attribute at all.

**Comment by aldaris** [comment]
Looks to be a duplicate of #1134

**Comment by christian-bromann** [comment]
@burg do you agree with the spec change that landed in #1473? If not I am happy to make necessary adjustments.

**Comment by burg** [comment]
I left comments on #1473, this can be closed now.
