### ISSUE TITLE
Brackets mixed up

### ISSUE THREAD

**Issue by pyfisch** [w3c/webdriver#1313]
In chapter [17. Actions](https://w3c.github.io/webdriver/#dfn-shifted-character#x17-actions), section [17.4 Dispatching Actions](https://w3c.github.io/webdriver/#dfn-shifted-character#x17-4-dispatching-actions):
> "["	"{"	"BracketLeft"
> "}"	"]"	"BracketRight"

This should be

> "["	"{"	"BracketLeft"
> "]"	"}"	"BracketRight"

**Comment by andreastt** [comment]
Yes, thanks! 👍 This appears to just be a bug.
