### ISSUE TITLE
wrong definition of "top" of in-view center point

### ISSUE THREAD

**Issue by codingphil** [w3c/webdriver#1314]
In chapter [11. Elements](https://www.w3.org/TR/webdriver/#dfn-center-point#x11-elements), section [11.1 Element Interactability](https://www.w3.org/TR/webdriver/#dfn-center-point#x11-1-element-interactability):
> Let top be (max(0, min(y coordinate, y coordinate + width dimension))).

In my opinion there should be height be used instead of width in the second argument of min().

Suggested changed line:
*Let top be (max(0, min(y coordinate, y coordinate + height dimension))).*

**Comment by andreastt** [comment]
Yes, this seems to be in line with what the implementations are doing:
https://searchfox.org/mozilla-central/rev/80ac71c1c54af788b32e851192dfd2de2ec18e18/testing/marionette/element.js#1164
