### ISSUE TITLE
/date null/data null

### ISSUE THREAD

**Issue by pyfisch** [w3c/webdriver#1326]
In chapter [10. Command Contexts](https://w3c.github.io/webdriver/#dfn-get-window-handles#x10-command-contexts), section [10.3 Switch To Window](https://w3c.github.io/webdriver/#dfn-get-window-handles#x10-3-switch-to-window):
> Return success with date null. 

While I am glad that `null` goes to a date it should be:

> Return success with data null.

**Comment by christian-bromann** [comment]
PR for this in #1330
