### ISSUE TITLE
"Switch To Frame" throws inappropriate "No Such Frame" error for out of bounds frame id number values

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver#1389]
This issue is similar to #1387 but I missed that also out of bounds values of correct data types are throwing "no such frame" errors instead of "invalid argument".

Sorry, that I haven't noticed that earlier. It came up now while implementing the tests.

**Comment by whimboo** [comment]
How should we handle the case when the frame id is a WebElement, but doesn't actually reference a `frame` or `iframe`? Should we also throw an `invalid argument` error, or should it stay with `no such frame`? Personally I would prefer a change here to stay in sync with type checks.

**Comment by jgraham** [comment]
So, in your scheme, when would `no such frame` ever get thrown? I can see it makes sense to throw invalid argument if you fail to convert the input into the correct type, but if you get a valid input value I would expect `no such frame` to be thrown (I also thing this probably doesn't matter too much either way).

**Comment by whimboo** [comment]
The question might have been phrased the other way around, which is shorter to answer. In the following cases we should throw an invalid argument error:

- When the frame id is a Number, but is lower than 0 or higher than 2^16-1
- If the web element isn't a frame or iframe element

All the other cases should still throw a "no such frame" error, including when the frame index is not valid anymore. As such the used description of the issue might not be completely adequate. Sorry.

**Comment by jgraham** [comment]
I agree with that summary.

**Comment by whimboo** [comment]
I'm actually unsure about the following assessment, and if that is really something we want to change:

> If the web element isn't a frame or iframe element

Lets also get the feedback from @andreastt, and @JohnChen0.

**Comment by andreastt** [comment]
@whimboo Sorry, I don’t understand what you mean?

**Comment by whimboo** [comment]
@andreastt please see https://github.com/w3c/webdriver/issues/1389#issuecomment-452291573.

**Comment by andreastt** [comment]
Are you talking about the third substep of the “_id_ represents a web element” branch?

In that case the input is valid, but the web element you’re trying to set as the current browsing context doesn’t represent a frame element. It’s analogous to substep 3 of “_id_ is a `Number` object”, where we are guaranteed that all the list entries are frames (so we don’t bother with the element instance check) but a frame by that index doesn’t exist, e.g. the search for the frame failed.

**Comment by whimboo** [comment]
@andreastt, ok. So it means the only change needed here is for the bounds check of id in case of a Number. If it is lower than 0 or bigger than 2^16-1 it's clearly an `invalid argument` error.
