### ISSUE TITLE
Clarify what browsing context pageLoadStrategy applies to

### ISSUE THREAD

**Issue by gsfraley** [w3c/webdriver#1401]
We encountered an issue where GeckoDriver and ChromeDriver interpret pageLoadStrategy differently.

GeckoDriver checks the main page for document.readyState.  ChromeDriver checks the main page, _as well as all of the child frames._  This results in two different behaviors on a page that, e.g., uses iframes for background resource loading.

For such pages, ChromeDriver will hang indefinitely and GeckoDriver will get to work immediately, interacting with the page as soon as the main page is loaded.

Ideally, this behavior would be standardized so that setting it will result in the same behavior across different drivers.

**Comment by barancev** [comment]
The current edition says:

"Let readiness target be the document readiness state associated with the current session’s page loading strategy, which can be found in the table of page load strategies.

Wait for the current browsing context’s document readiness state to reach readiness target, or for the session page load timeout to pass, whichever occurs sooner."

It seems to be clear that it does not apply to frames.

**Comment by gsfraley** [comment]
Okay, in that case, I'm fine with closing the issue.  Thanks!

**Comment by whimboo** [comment]
In such a case it might make sense to file a bug against chromedriver. CC'ing @JohnChen0.

**Comment by gsfraley** [comment]
I did open up an issue here: https://bugs.chromium.org/p/chromedriver/issues/detail?id=2809.  I don't know if I was able to provide enough detail, so I'll continue hunting for public examples of what I'm seeing, but I do feel like it adequately describes the issue.
