### ISSUE TITLE
Maximum value of timeouts is too small

### ISSUE THREAD

**Issue by JohnChen0** [w3c/webdriver#1403]
In chapter [9. Timeouts](https://w3c.github.io/webdriver/#timeouts), the timeout duration values are required to be no greater than 2^16 – 1. This is equivalent to about 65 seconds, or barely longer than a minute, and would be too low for some application. In fact, the default value of page load timeout (300,000) is above this maximum, so if an application changes the page load timeout to some other value, it would have no way to change it back to the default.

Earlier versions of this standard allowed timeout duration values up to the maximum safe integer. The WPT webdriver tests are still written based on that older requirement. Recommend reverting the range to maximum safe integer, or at least to a value much larger than one minute.

**Comment by praveen4463** [comment]
Can this be looked into please? The specs seems to have this as a bug because even if I set 2^36 to script or page load timeout, drivers accept them happily, there is no driver exception. 2^16 – 1 should be a typo in the spec, and it's confusing.

**Comment by whimboo** [comment]
As it looks like this has been regressed by the timeouts rewrite (https://github.com/w3c/webdriver/pull/1394) early last year.

**Comment by whimboo** [comment]
Fixed by merge of #1548.
