### ISSUE TITLE
Selenium webdriver can't load activeX？

### ISSUE THREAD

**Issue by submergerock** [w3c/webdriver#1407]
Selenium webdriver can't load activeX？
![image](https://user-images.githubusercontent.com/2242678/54973084-5be0f100-4fc9-11e9-890d-95a84bab1583.png)
![控件](https://user-images.githubusercontent.com/2242678/54973132-8a5ecc00-4fc9-11e9-8fab-27c0a46cba00.jpg)

**Comment by andreastt** [comment]
As far as I understand, don’t you need to use Internet Explorer to load ActiveX components? Firefox turned off support for native extensions (such as Java applets) some time ago.
