### ISSUE TITLE
fix dead link to implementation report

### ISSUE THREAD

**Issue by waldenn** [w3c/webdriver#1413]
Hi,

This page: https://www.w3.org/TR/webdriver/

Links to:   Implementation report: https://github.com/w3c/webdriver/blob/master/implementation-report.md

That URL should corrected to: https://github.com/w3c/webdriver/blob/master/ImplementationReport.md

Kind regards.

**Comment by andreastt** [comment]
Thanks for the bug report. The [Editor’s Draft](https://w3c.github.io/webdriver/) has the correct link, but the Echnida tool that publishes EDs to /TR is broken, causing the document not to get uploaded correctly to w3.org.

@sideshowbarker reported this earlier today and is working on a fix, I believe.

**Comment by waldenn** [comment]
Ok, great. Thanks!

**Comment by waldenn** [comment]
Ok, great. Thanks!

**Comment by andreastt** [comment]
Let’s keep this open to track the issue. (-:

**Comment by andreastt** [comment]
Fixed by https://github.com/w3c/webdriver/pull/1415.
