### ISSUE TITLE
"instant" is not valid scrollIntoView behavior

### ISSUE THREAD

**Issue by mtrea** [w3c/webdriver#1449]
In chapter [12. Elements](https://w3c.github.io/webdriver/#dfn-scrolls-into-view#x12-elements):
> "behavior"
> "instant"

However, per https://drafts.csswg.org/cssom-view/#enumdef-scrollbehavior ScrollBehavior only has values "auto" and "smooth".

**Comment by mtrea** [comment]
Some browsers such as Chrome do support "instant" but it is not part of the CSSOM View spec.

**Comment by andreastt** [comment]
Indeed, `smooth` was defined in CSSOM View at the time we wrote this into the WebDriver spec, but it appears to have been removed for reasons I don’t understand.

We should probably change the specification to use `auto`.

**Comment by Boscop** [comment]
@andreastt Do you know if other browsers will use `auto` if you specify `instant` behavior?
And how fast is `auto` compared to `instant` in chrome? 
If smooth scrolling is disabled in user settings, is `auto` equal to `instant`? 
And it smooth scrolling is enabled, it's equal to `smooth`?

**Comment by AutomatedTester** [comment]
> @andreastt Do you know if other browsers will use `auto` if you specify `instant` behavior?
> And how fast is `auto` compared to `instant` in chrome?
> If smooth scrolling is disabled in user settings, is `auto` equal to `instant`?
> And if smooth scrolling is enabled, it's equal to `smooth`?

Reading CSSOM-View it would appear that auto is the default so if it gets a value that is incorrect it will likely use the default
