### ISSUE TITLE
add to spec of Element Interaction: Element Insert Keys

### ISSUE THREAD

**Issue by jvanoosterom** [w3c/webdriver#1469]
Request to add to the specification a way to insert keys at the current caret position.

We want to test insertion of keys at the current caret position.
This is impossible with the current specification of 14.3 Element Send Keys
Since the spec requires that the caret is moved to the last position, this is currently not possible to test.

testcase and scenario:
An editor with a bold button.
You want to remember the caret position. Click the bold button en continue inserting bold text
The html will be:
`before click of bold<b>after click on bold</b>`

example angularJs and failing protractor test:
https://stackoverflow.com/questions/58075306/how-to-test-angularjs-with-protractor-contenteditable-with-bold-modifier-bro

**Comment by andreastt** [comment]
This is possible to achieve with the [Actions API](https://w3c.github.io/webdriver/#actions) which gives more fine-grained control over user input.

Element Send Keys is considered a “high level” API that also runs a series of other convenience checks and assertions to make interaction simple.
