### ISSUE TITLE
SameSite cookie missing normative reference

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#1474]
https://github.com/w3c/webdriver/pull/1473 added the `samesite` parameter to the Add Cookie command, but it doesn’t define what the variants "`Lax`" and "`Strict`" mean.

Same-site cookies is defined in [draft-west-first-party-cookies-07](https://tools.ietf.org/html/draft-west-first-party-cookies-07), which I understand is meant to update [RFC 6265](https://tools.ietf.org/html/rfc6265). Since it doesn’t appear to have made it there yet my guess would be that [Specref](https://www.specref.org/?q=first-party) would need to have this added so we can refer to the draft.

**Comment by andreastt** [comment]
Actually, the above appears to have been superseded by [RFC6265bis](https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00).

I got this from https://web.dev/samesite-cookies-explained/.

**Comment by AutomatedTester** [comment]
added reference to RFC6265bis in https://github.com/tobie/specref/pull/595

**Comment by foolip** [comment]
I added it to `localBiblio` in https://github.com/w3c/webdriver/pull/1507, unaware of this issue and https://github.com/tobie/specref/pull/595.

**Comment by whimboo** [comment]
@AutomatedTester with https://github.com/w3c/webdriver/pull/1490 merged, is that fixed now?
