### ISSUE TITLE
Level 2 publication broken

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#1475]
@plehegar submitted https://github.com/w3c/webdriver/pull/1460 to enable publication of the living document as https://www.w3.org/TR/webdriver2/.

Immediately following the change I noticed the following two emails to public-tr-notifications@:

1. [2019-11-24 19:53 GMT](https://www.w3.org/mid/b5fad890-cc72-ba03-cd98-8982797df649@w3.org)
2. [2019-11-25 09:50 GMT](https://www.w3.org/mid/117e297e-e77e-d95b-fcbe-d702dc5230a1@w3.org)

The first successful update seems to originate from before https://github.com/w3c/webdriver/pull/1460, which leads me to believe it was published manually. The second update corresponds to when I merged https://github.com/w3c/webdriver/pull/1460 onto master, but it failed this way:

```
✗ Echidna failed to publish https://w3c.github.io/webdriver/echidna-manifest.txt
 for the following reasons:

   The file has been retrieved.
   The metadata have been extracted.
   The document passed the transition checker.
   The document passed Specberus.
   You are not authorized to publish
 👎 not-authorized
```

Are we lacking some kind of authorisation token?

@AutomatedTester @sideshowbarker

**Comment by AutomatedTester** [comment]
@plehegar Has this been fixed?

**Comment by sideshowbarker** [comment]
paging in @deniak

**Comment by deniak** [comment]
Looking at the recent builds (eg. https://travis-ci.com/github/w3c/webdriver/builds/155683732), the environment variable configured in travis wasn't the right one (`ECHNIDA_TOKEN` instead of `ECHIDNA_TOKEN`).
https://github.com/w3c/webdriver/pull/1491 should fix the issue and simplify the CI configuration a bit.

**Comment by sideshowbarker** [comment]
Thanks @deniak!
