### ISSUE TITLE
This will not create a new window. This will create a new tab in Chrome

### ISSUE THREAD

**Issue by KitoCoding** [w3c/webdriver#1478]
In chapter [11. Contexts](https://w3c.github.io/webdriver/#new-window#x11-contexts), section [11.5 New Window](https://w3c.github.io/webdriver/#new-window#x11-5-new-window):
> /session/{session id}/window/new

A couple issues with this feature.

Since the feature will create a new tab and not a new window, we cannot create a new window if the window does not exist. For example, if we call the Close Window End Point, then the New Window End Point it fails because it doesn't have a session id anymore, which isn't true.  Second, it should create a new window and not a new tab.

**Comment by andreastt** [comment]
The session is closed implicitly when the last window closes, which would explain why the driver would complain it doesn’t have a session ID. The only way to recover from this is to start another session.

Am I missing some big, glaring detail?

**Comment by KitoCoding** [comment]
yes. you mentioned the glaring detail. i close the window, and it assumes to close the session. i am maintaining the session on purpose, i want to close the window and reopen a new one. Also, the issue i pointed out, it creates a new tab and not a new window. If a new tab is implyed then we can do that, but it should be documented with another way to create a new window

**Comment by andreastt** [comment]
The [New Window](https://w3c.github.io/webdriver/#new-window) command takes a `type` hint that you can use to request either a tab or a window. There’s however no obligation for the driver to respect the hint, as certain browsers may not be able to support windows.

It’s usually not possible to have a browser session without having at least one window open, which is why WebDriver makes the simplification to end the session on closing the last window.

**Comment by KitoCoding** [comment]
I believe it can be dangerous to build assumptions for single command is unique circumstances. A command should do what you tell the command to do, and nothing more.  I suppose the same argument can be said about the New Session Command. If the close window command shouldn't be assuming functionality then the new session command also shouldn't be creating a new window. 

However, I could be alone on this. If this is intended behavior I can try my best to work around it.

**Comment by KitoCoding** [comment]
@andreastt I noticed something else but it might be a chromedriver specific issue. 

When creating a new window, it doesn't adhere to the capabilities linked to the original window. For example: I build a new session with capabilities of starting a its window maximized. I then create a new window (not a new tab). And the new window does not start maximized. Should new windows not follow the same capabilities as the original window?

**Comment by andreastt** [comment]
I sympathise that sessions ought have a lifetime independent from that of the browser window, but WebDriver operates within certain historical constraints. For certain browser configurations it is not possible to have “windowless” browsers, and some configuration specific uniqueness is consequently papered over to provide a consistent API for all browsers.

WebDriver doesn’t say anything specific about window maximisation, so whatever feature you’re relying on to force new windows to be maximised must be specific to Chromium. After a new window has been opened, you can in any case use the [Maximize Window](https://w3c.github.io/webdriver/#maximize-window) command to achieve the same effect cross-browser.

**Comment by KitoCoding** [comment]
Yes sorry I was using the maximize window option as an example to show that new windows are not sharing capabilities as the original window. I'll bring this concern to chromedrivers discussion board
