### ISSUE TITLE
Finding the top should use the height dimension instead of width

### ISSUE THREAD

**Issue by abhishekgoyal1994** [w3c/webdriver#1479]
In chapter [11. Elements](https://www.w3.org/TR/webdriver1/#dfn-pointer-interactable-paint-tree#x11-elements), section [11.1 Element Interactability](https://www.w3.org/TR/webdriver1/#dfn-pointer-interactable-paint-tree#x11-1-element-interactability):
> (max(0, min(y coordinate, y coordinate + width dimension)))

**Comment by andreastt** [comment]
Thanks for reporting. This indeed seems like an editorial oversight, because I believe the tests for this are doing the right thing.

**Comment by andreastt** [comment]
Would you like to try fix the issue? Otherwise I can pick it up.

**Comment by abhishekgoyal1994** [comment]
I won't be able to fix this, so probably you can pick it up.

**Comment by andreastt** [comment]
It looks like this is already fixed in the living document.
