### ISSUE TITLE
[Discussion] New Session creations are slow

### ISSUE THREAD

**Issue by KitoCoding** [w3c/webdriver#1480]
In chapter [8. Sessions](https://w3c.github.io/webdriver/#new-session#x8-sessions), section [8.1 New Session](https://w3c.github.io/webdriver/#new-session#new-session):
> New Session

I have been trying to wrap my head around as to why this might be slow. I have created a request to launch, in this case Chrome. The actual window launch is instant, no problem at all. However it hangs there for a good 4 seconds before returning a Success response. 

If possible could we discuss what is happening in the background, and why it may be taking 4 seconds after launching the browser to give a success response?

**Comment by christian-bromann** [comment]
@KitoCoding I am not sure if this can be discussed on protocol level. It is up to the implementer (in this case Chromedriver) how it establishes the session with the browser. This is out of scope of WebDriver. I think it is a better idea to create this issue in the Chromedriver project.

**Comment by whimboo** [comment]
Yes, please take that issue over to the [chromedriver project](https://chromedriver.chromium.org/). Nevertheless I will cc @JohnChen0 here to make him aware of it.
