### ISSUE TITLE
While selecting any text "file issue" button is showing 

### ISSUE THREAD

**Issue by shrikanttellawar** [w3c/webdriver#1481]
In chapter [8. Sessions](https://www.w3.org/TR/webdriver/#status#x8-sessions), section [8.3 Status](https://www.w3.org/TR/webdriver/#status#x8-3-status):
>  Status

**Comment by andreastt** [comment]
This is expected, but we should probably be publishing a stripped version of the specification to https://www.w3.org/TR/webdriver2/.
