### ISSUE TITLE
Hello from JavaScript WebDriver implementation 👋

### ISSUE THREAD

**Issue by mucsi96** [w3c/webdriver#1483]
Hello WebDriver community! I am big fan of you work. I love WebDriver so much. I would like to share a [project ](https://mucsi96.gitbook.io/w3c-webdriver) I have been working for last 3 years (in free time 😊 ) mostly for fun. This project provides JavaScript bindings that conform to the W3C WebDriver standard for controlling web browsers. Some key ideas behind it:

- Minimalistic promise based REST client.
- One-to-one mapping to WebDriver API endpoints
- Written in TypeScript for type safety, autocomplete and IntelliSense documentation
- Full feature coverage over 55 WebDriver endpoints
- 100% test coverage in real browsers (Chrome, Firefox, Safari, Internet Explorer)
- Tested on Ubuntu, Windows and MacOS on CI server

Now the project became more mature achieved 100% feature coverage of the WebDriver spec and it reached a stable state. Docs now are in quite good shape I would say. Sure we will do further improvements on docs by adding more examples and some tutorials. I would be more that happy if you can use it anyhow in future, provide some feedback or contribute to it 😊 I was thinking what if we could do some collaboration. What if this project could be one day the official JavaScript implementation of the protocol. Similarly to most public APIs the companies provide official JavaScript clients which is a huge help for spreading of the technology. Would be great to have some base implementation others can build upon instead of implementing everything from scratch. As JavaScript is the language of the web It make a lot of sense to have an official client in JavaScript. 

Please let me know what you think. I am open to transfer the repository to other organization.

**Comment by AutomatedTester** [comment]
Thanks for letting us know, unfortunately this repository does not have anything to do with client bindings. I suggest poking the SeleniumHQ/selenium group
