### ISSUE TITLE
Generic cookie attribute handling

### ISSUE THREAD

**Issue by rogerdc** [w3c/webdriver#1484]
I'm not familiar with the direct WebDriver interfaces. I use them through Selenium. 

That said, could the attributes of cookies be handled in a generic way so that as the attributes of cookies are extended over time, WebDriver would be future-proofed against these extensions? 

For example, if a Set-Cookie header is sent to the browser with a name, value, and these attributes (semicolon-delimited as specified in RFC6265):

`Set-Cookie: <name>=<value>; path=/mypath; secure; samesite=none; httponly
`

could WebDriver provide a way to retrieve all values sent in a generic way, rather than querying only for specific attributes? It could return an array of string pairs, like these:

| AttributeName | AttributeValue |
| --- | --- |
| path | /mypath |
| secure | (Empty string) |
| samesite | none |
| httponly | (Empty string) |

**Comment by AutomatedTester** [comment]
This is heavily dependent on the client bindings and how they are done things. You will likely get a dictionary or map or a class with ability to move to a dictionary/map and work with that. 

If the client bindings aren't offering that I suggest raising an issue with them as the spec describes returning the details in the cookie jar back to the client.
