### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by tulasirm** [w3c/webdriver#1508]
In chapter [Status of This Document](https://www.w3.org/TR/webdriver1/#status-of-this-document):
> implementation report

Please see the Working Group's **implementation report**.

**Comment by foolip** [comment]
The link should be to https://github.com/w3c/webdriver/blob/master/ImplementationReport.md. But that capitalization is funny, might rename the file instead.

**Comment by foolip** [comment]
Oh, actually, the link in question is gone from the current spec. So to fix this https://www.w3.org/TR/webdriver1/ would have to be published again.

**Comment by AutomatedTester** [comment]
@sideshowbarker can you help with the republishing?

**Comment by sideshowbarker** [comment]
fixed now

**Comment by tulasirm** [comment]
Thank you.
