### ISSUE TITLE
"Switch To Parent Frame" has to check for top-level browsing context before the parent browsing context open check

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver#1544]
This is a follow-up from issue #1539.

If the currently selected browsing context is already the top-level browsing context the call to "Switch To Parent Frame" should be a no-op. That's how the Chromedriver behaves currently. But right now when reading the spec the first step of the remote steps will actually error out:

https://w3c.github.io/webdriver/#switch-to-parent-frame

> If the current parent browsing context is no longer open, return error with error code no such window. 

If the current browsing context is already the top browsing context, the parent will be `null`. As such the command should return a "no such window" error.

CC'ing @jgraham for his opinion.

**Comment by jgraham** [comment]
Oh I misunderstood this when you mentioned it on matrix; I was looking at the later steps. This is clearly a spec bug, "no longer open" isn't a state that `null` can have. So I don't think the spec really says one way or another what should happen it's just broken.

**Comment by whimboo** [comment]
Ok, so for the upcoming tests I will keep the behavior of current webdriver clients that is just a no-op. We can refine the tests later whenever we have made a change here.

**Comment by whimboo** [comment]
Fixed by #1556.
