### ISSUE TITLE
element rect returns wrong y when page is scrolled

### ISSUE THREAD

**Issue by matti** [w3c/webdriver#1553]
See video here: https://www.youtube.com/watch?v=XSbBMNR04YI&feature=youtu.be

`el.getBoundingClientRect(); ` returns correct y (not changed) while webdriver rect returns wrong y

**Comment by matti** [comment]
....in chromedriver atleast

**Comment by matti** [comment]
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3623

**Comment by whimboo** [comment]
This repository is for issues / requests regarding the webdriver specificationj, but not for individual webdriver implementations. As such you did the right thing in filing an issue against chromedriver. But that also means we can close this issue.
