### ISSUE TITLE
Getting parameters of GET requests makes no sense

### ISSUE THREAD

**Issue by jginsburgn** [w3c/webdriver#1568]
In chapter [17. Screen capture](https://www.w3.org/TR/webdriver/#take-screenshot#x17-screen-capture), section [17.2 Take Element Screenshot](https://www.w3.org/TR/webdriver/#take-screenshot#x17-2-take-element-screenshot):
> getting the property scroll from parameters

GET Requests are not semantically empowered with payloads. The specification of the Take Element Screenshot is confusing in that it instructs the implementing agent to get a parameter `scroll` from the payload, but its corresponding endpoint is specified with the GET verb.

**Comment by whimboo** [comment]
You are looking at an outdated version of the spec. The part you are referencing here got already removed via issue #1245. The current version of the spec can be found at https://w3c.github.io/webdriver.
