### ISSUE TITLE
"Navigation" is incorrectly linked in multiple places

### ISSUE THREAD

**Issue by foolip** [w3c/webdriver#1574]
@jtnord pointed this out in https://github.com/w3c/webdriver/pull/1518#pullrequestreview-596598134.

Many links with the link text "navigation" lead to https://w3c.github.io/webdriver/#dfn-navigating which is the definition of "navigate" in HTML. Some of these should probably link to https://w3c.github.io/webdriver/#navigation or https://w3c.github.io/webdriver/#navigate-to instead.

**Comment by whimboo** [comment]
@foolip would you have the time to fix those broken entries?

**Comment by foolip** [comment]
@whimboo I'm really not sure which specific links should be changed, since in https://github.com/w3c/webdriver/pull/1518#pullrequestreview-596598134 @jgraham thinks it's now correct.

**Comment by foolip** [comment]
I've looked at all links I find by searching for "navigat" in the current spec and can't find anything *I* consider to be wrong, so closing this.

**Comment by jtnord** [comment]
> @whimboo I'm really not sure which specific links should be changed, since in #1518 (review) @jgraham thinks it's now correct.

Oh my...  did he state that with this information in hand, 
I thaught he was saying he thinks it was correct before this analysis.

If someone can explain to be otherwise how the section there makes any sense...
