### ISSUE TITLE
Add Cookie method doesn't account for redirects

### ISSUE THREAD

**Issue by chlily1** [w3c/webdriver#1593]
The [Add Cookie method](https://w3c.github.io/webdriver/#add-cookie) only allows setting a cookie with a domain equal to the current browsing context's document. This means that if a domain always redirects cross-origin, there's no way to set a cookie on the domain.

For example, let's say a company has an internal site `acme-corp.com`, and accessing any page on `acme-corp.com` results in a cross-origin redirect to `login.acme.com`. It becomes impossible to set any cookie with domain `acme-corp.com`.

Can this be changed so that any domain in the current browsing context's redirect chain is valid?

(For context, this issue came up after Chrome [tightened up](https://crbug.com/chromedriver/3734) enforcement of the domain matching rule. We started getting bug reports about Add Cookie failing due to the cookie domain mismatching, in particular when  adding a cookie on domain A immediately after navigating to a page that does an A->B cross-origin redirect.)

**Comment by whimboo** [comment]
Thanks for filing the issue @chlily1. There is already #1238 open for the exact same situation. As such I would like to close this issue in favor of the other one. If you feel that some details are missing please add it to the other issue. Thanks.
