### ISSUE TITLE
Remove setWindowRect Capability

### ISSUE THREAD

**Issue by titusfortner** [w3c/webdriver#1606]
In chapter [7. Capabilities](https://w3c.github.io/webdriver/#capabilities#x7-capabilities):
> Window dimensioning/positioning

I propose we remove this capability as unnecessary and confusing.

Spec says this capability is:
```
Boolean indicating whether the remote end supports all of the resizing and positioning commands.
```

There aren't any implementations that do not support these commands according to [wpt set_window_rect tests](https://wpt.fyi/results/webdriver/tests/set_window_rect/set.py) 

Further, there aren't any wpt tests for the capability itself, only the endpoint: (`POST | /session/{session id}/window/rect`)

Finally, the spec does not match what is in the Selenium documentation for it, so it is already confusing users/devs:
https://www.selenium.dev/documentation/en/driver_idiosyncrasies/shared_capabilities/#setwindowrect

**Comment by shs96c** [comment]
Implementations of webdriver that automate devices with fixed-size viewports (eg. mobile OSs, TVs, etc) may not implement the window resizing commands. As such, it's best to leave this in the spec to allow local ends to determine which commands can be sent.

> Finally, the spec does not match what is in the Selenium documentation for it, so it is already confusing users/devs:
https://www.selenium.dev/documentation/en/driver_idiosyncrasies/shared_capabilities/#setwindowrect

The documentation links to the command for setting the window dimensions. Local ends can determine whether this command should be offered at all by looking at the capability. I'm not quite sure where the confusion is arising. 

There are also already established cases where the type of the capability when sent differs from the value when returned (eg. profiles) Ideally, local ends will shield users from this kind of complexity.

> Further, there aren't any wpt tests for the capability itself, only the endpoint

We should add some.
