### ISSUE TITLE
Get Element Shadow Root returns a raw shadow root identifier

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#1613]
https://w3c.github.io/webdriver/#get-element-shadow-root looks like it's going to create a return value like `{value: <shadow root id>}`. In contrast, Element-returning commands e.g. [Find Element](https://w3c.github.io/webdriver/#find-element) always use the [JSON Serialization of element](https://w3c.github.io/webdriver/#dfn-json-serialization-of-an-element) which returns aan object of the form `{value: {element-6066-11e4-a52e-4f735466cecf: <web element id>}}`.

It's not clear if this was intended or not; the [JSON Serialization of Shadow Root](https://w3c.github.io/webdriver/#dfn-json-serialization-of-a-shadow-root) is defined, but is unused throughout the document.

The [test](https://github.com/web-platform-tests/wpt/blob/master/webdriver/tests/get_element_shadow_root/get.py) seems to include the shadow root identifier, so I think the spec is wrong and should refer to the JSON serialization of shadow root.

**Comment by jgraham** [comment]
https://github.com/w3c/webdriver/pull/1616 has a fix for this

**Comment by whimboo** [comment]
> #1616 has a fix for this

@jgraham can we close given that #1616 has been merged, or is more work needed?
