### ISSUE TITLE
Get Element Shadow Root appears to only work with open shadow roots.

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#1614]
https://w3c.github.io/webdriver/#get-element-shadow-root gets the `shadowRoot` property from `Element`. That means that it will fail if the shadow root is closed. It can also produce an unexpected result if a user overwrites the `shadowRoot` property on a given element.

Spec wise we want to change it to say `let |shadow root| be |element|'s [shadow root](https://dom.spec.whatwg.org/#concept-element-shadow-root)`. If we still want to only work for open shadow roots we can then check if the mode is closed, but I think we should expect this to also work for closed shadow roots.

**Comment by jgraham** [comment]
https://github.com/w3c/webdriver/pull/1616 has a fix for this

**Comment by annevk** [comment]
It seems like this can be closed?
