### ISSUE TITLE
 browser.keys(`\uE009`) is not working ,it is not performing the any aciton.

### ISSUE THREAD

**Issue by muralikpujari** [w3c/webdriver#1629]
In chapter [16. Actions](https://w3c.github.io/webdriver/webdriver-spec.html#keyboard-actions#x16-actions), section [16.4 Dispatching Actions](https://w3c.github.io/webdriver/webdriver-spec.html#keyboard-actions#x16-4-dispatching-actions):
> Control

**Comment by whimboo** [comment]
@muralikpujari can you please be more specific? Is that an issue with a particular driver only? What's the code that you are trying to run. And why do you think that this is an issue with the WebDriver specification?

**Comment by whimboo** [comment]
Seems to be a dupe of issue #1628.
