### ISSUE TITLE
Element displayedness in webdriver2

### ISSUE THREAD

**Issue by mercmobily** [w3c/webdriver#1633]
I am aware of #1285.
I wrote a WebDriver, https://mobily-enterprises.github.io/best-webdriver/, which is 100% w3c compatible and _nothing_ else. I am about to write extensive tests for a complex SPA, and would like to only use w3c standard calls.

The section 'Element displayedness' is a little confusing in the webdriver specs. I read that the webdriver2 specs will possibly include a /displayed endpoint (I might be wrong). 

What is the status of this? Will /displayed be included in the second version of the specs?

**Comment by jgraham** [comment]
I think it's unlikley that anything for displayedness will be added to the HTTP WebDriver spec.

In practice it was difficult to come to an agreeable definition of whether an element is "displayed" that matched the behaviour of the Selenium code, which was considered important for compatibility with existing tests. So the "solution" is basically to delegate displayedness to clients, requiring them to run a blob of js code which matches their local definition of displayedness. Some implementations additionally ship the code from Selenium to provide some kind of built-in solution, but it's unlikely we're going to standardise that.

Unless something happens at the platform layer to give us a crisp definition of displayed that matches the requirements of authors, I expect we'll continue to defer to clients to provide their own implementation (or reuse an existing one) here.

**Comment by mercmobily** [comment]
Thank you for taking the time to answer my question James @jgraham 

> Unless something happens at the platform layer to give us a crisp definition of displayed that matches the requirements of 
> authors, I expect we'll continue to defer to clients to provide their own implementation (or reuse an existing one) here

This is a shame.  However, I do realise that it's very difficult to _actually_ know if an element is displayed. And I agree that it must come from the platform, really.

> Some implementations additionally ship the code from Selenium to provide some kind of built-in solution, but it's unlikely 
> we're going to standardise that.

I am thinking of biting the bullet and do the same. However, the code is very closures-specific and difficult to pinch.
Would I be abusing your patience, if I asked you which tools out there are adapting Selenium code for it?
