### ISSUE TITLE
[🚀 Feature]: WaitForNavigation method

### ISSUE THREAD

**Issue by dahanj95** [w3c/webdriver#1636]
Feature and motivation
Just like in puppeteer, a `WaitForNavigation` method would be really useful because currently there's no way to wait for navigation and know when a page has been fully loaded.

having options like `NetworkIdle2` and `Load` would also be great.

Usage example
`driver.Navigate().WaitForNavigation()`

another one would accept parameters such as `NetworkIdle2` and `Load`, `DOMContentLoaded` and so on.

**Comment by jgraham** [comment]
Webdriver already allowed waiting for navigations in a global way using the `pageLoadStrategy` capability. The ability to specify on a per-navigation basis will be part of [WebDriver-BiDi](https://github.com/w3c/webdriver-bidi/). Currently conditions that don't correspond to a specific DOM event, e.g. `NetworkIdle2`, aren't supported there, because no one has specified the semantics of those conditions.

**Comment by dahanj95** [comment]
> Webdriver already allowed waiting for navigations in a global way using the `pageLoadStrategy` capability. The ability to specify on a per-navigation basis will be part of [WebDriver-BiDi](https://github.com/w3c/webdriver-bidi/). Currently conditions that don't correspond to a specific DOM event, e.g. `NetworkIdle2`, aren't supported there, because no one has specified the semantics of those conditions.

Yeah, but the problem is this isn't in the [Spec](https://github.com/SeleniumHQ/selenium/issues/w3c.github.io/webdriver/) yet. Would it be possible to add it to the spec?

**Comment by jgraham** [comment]
I don't know what specifically you're asking for:
* [Page load strategies](https://w3c.github.io/webdriver/#dfn-table-of-page-load-strategies) are in the WebDriver spec.
* [Navigation in WebDriver-BiDi](https://w3c.github.io/webdriver-bidi/#command-browsingContext-navigate) allows specifying a `wait` parameter.
* `NetworkIdle2` isn't well understood enough to specify. If you can explain, in enough detail to write an interoperable specificaion, when `NetworkIdle2` is reached, I think we'd be open to adding something similar to that.

**Comment by titusfortner** [comment]
The thing that interests me about this concept is that it can be made available in more than just the navigation context. Most synchronization issues come from clicking an element to go to a new page.

**Comment by jgraham** [comment]
With BiDi you can subscribe to all the navigation-related events, so it's pretty straightforward to implement that in a client (exactly like Puppeteer does with CDP). I doubt we'd implement `wait`-like functionality as command parameters in the protocol for commnds that might incidentially cause a navigation (which is pretty much anything) without some compelling use cases.

**Comment by titusfortner** [comment]
I'm not necessarily looking for something automatic (that seems like a lot of overhead), but a command I can execute that does more than check the Document Ready State. I'm not familiar with what Puppeteer does, just thinking about what would be useful to testers.
