### ISSUE TITLE
URLs don't perform post navigation checks in case of file:///c:/test/NotExistenFile.html

### ISSUE THREAD

**Issue by mlipok** [w3c/webdriver#1638]
I came to an issue where I try to use chromedriver.exe to navigate to a file.
When I use an not existen file for example `file:///c:/test/NotExistenFile.html` then of course browser try's to navigate and returns `ERR_FILE_NOT_FOUND` but currently chromedriver.exe returns `{"value":null}` on navigation.

So I checked the documentation for implementation here:
https://www.w3.org/TR/webdriver2/#navigate-to

And I do not see any requirmentes for checking if local file exist.
Was it intentional ?

**Comment by Danp2** [comment]
```
    8. If url is special except for file and current URL and URL do not have the same absolute URL :

        1. Try to wait for navigation to complete.

        2. Try to run the post-navigation checks.
```
Why are `file` URLs excluded from the post-navigation checks?

**Comment by whimboo** [comment]
Please note that this repository is about the WebDriver specification but not about misbehavior of specific drivers. Please [file a bug for chromedriver](https://bugs.chromium.org/p/chromedriver/issues/list) instead.

**Comment by Danp2** [comment]
@whimboo It would be appreciated if someone could address this question regarding the specs --
> Why are file URLs excluded from the post-navigation checks?

**Comment by mlipok** [comment]
please add here tag `awaiting feedback`

**Comment by mlipok** [comment]
I hope that after such a long time someone will find a moment to take a look at this issue.
