### ISSUE TITLE
Feature Request: parity support for HasSessionDetails 

### ISSUE THREAD

**Issue by helenren** [w3c/webdriver#1655]
There is no way to query the detail for the current session. Wondering if we can support HasSessionDetails same as JWP.

**Comment by whimboo** [comment]
Could you please explain why such a feature would be needed? When a new session is created all the session capabilities are sent beside its id. To interact with the session you will always have to include its id in the URL, which means that the session id has to be stored on the client side. The same should happen for the capabilities and means that session details are known.

So what kind of parity you are referring to with this request?

**Comment by helenren** [comment]
For some automation system, the part that creates the session and the part that uses the active session are separated. So, the created instance of a driver will be one to be shared among them. In this case,  need to from the driver to get more session info when needed, which has been supported in JWP via hasSessionDetails.

**Comment by jgraham** [comment]
We aren't going to provide this in geckodriver; the fact that you can't enumerate sessions is part of the security surface (if, for example, we provided an endpoint that allowed you to do `GET` `/sessions` and return a list of sessions, a page running in a web browser might be able to do a cross-origin request to get a list of active sessions and then further `GET` requests to get further information about the document under test).

If you want to share session ids between different components of a larger system you need to provide some out-of-band method of doing that.
