### ISSUE TITLE
bug report [:post, 'session/:session_id/function'] gives a unknown command

### ISSUE THREAD

**Issue by juliokr** [w3c/webdriver#1657]
My function is simple:
```
def print_pdf
  @driver.save_print_page("doc.pdf")
end
```
But i get this messagem back:
`Selenium::WebDriver::Error::UnknownCommandError Exception: POST /session/{session_id}/print did not match a known command`
According to web-driver documentation, method print supposed to be a POST request but seems like the endpoint doesn't reconize it.

I'm using selenium webdriver 4.1.0 and ruby

**Comment by whimboo** [comment]
This has been clarified in the Selenium channel and was caused by using an outdated geckodriver release that hadn't this feature implemented yet.
