### ISSUE TITLE
Finding the coordinates of the browser alerts

### ISSUE THREAD

**Issue by RajapriyaRadhakrishnan** [w3c/webdriver#1658]
Hi Team,

I have a query specific to browser user prompts - alert, confirm and prompt. Section - [https://w3c.github.io/webdriver/#user-prompts](url)

**Query:** As the height of the user prompt is set dynamically w.r.t. the description length, I need to find out the dimension and origin points of the prompts. How can I get the origin points (x, y) and dimension(width and height) of such user prompts?

Please take a look at the attached file - 
![firefox_confirm_dialog_box](https://user-images.githubusercontent.com/69154828/170971478-c30dd435-9c20-4feb-8af1-4d03199c4587.png)

**Comment by jgraham** [comment]
The display of any alert is specific to the platform and browser combination and doesn't necessarily take the form of a popup; for example it could be a browser "doorhanger" or full screen overlay or something else entirely. 

I don't really understand your use case, but this seems unlikely to be something we add to the WebDriver spec without a compelling reason. In the meantime if you have a specific browser/os configuration you're targeting it might be possible to use the platform APIs to figure out the dimensions of any window that's created as part of an alert.
