### ISSUE TITLE
Living Draft and spec in this repo have diverged

### ISSUE THREAD

**Issue by shs96c** [w3c/webdriver#1661]
https://w3c.github.io/webdriver/webdriver-spec.html and the contents of this spec have diverged. This can be seen most clearly in the example for errors.

**Comment by whimboo** [comment]
The [last merge](https://github.com/w3c/webdriver/commit/a99633b13312bdbf6afd47c5c3c314d606fa5442) was on May 25th and that's what the referenced spec page also shows at the top.

As given in the source we should have content like the following:

```
 <p><a>Errors</a> are represented in the WebDriver protocol
 by an <a>HTTP response</a> with an <a>HTTP status</a> in the 4xx or 5xx range,
 and a JSON body containing details of the <a>error</a>.
 The body is a JSON <a>Object</a>
 and has a field named "<code>value</code>"
 whose value is an object bearing three, and sometimes four, fields:
 ```

But it shows up as:
```
Errors are represented in the WebDriver protocol with a HTTP response with a HTTP status in the 4xx or 5xx range, and a JSON body containing details of the error. This JSON body has three fields: error, containing a string indicating the error type; message, containing an implementation-defined string with a human readable description of the kind of error that occurred; and stacktrace, containing an implementation-defined string with a stack trace report of the active stack frames at the time when the error occurred. 
```

As it looks like the living draft has the correct content: https://www.w3.org/TR/webdriver/#errors

So is there something busted with publishing to gh-pages? @jgraham do you have an idea? Not sure where www.w3.org gets the updates from...

**Comment by gsnedders** [comment]
https://github.com/w3c/webdriver/tree/gh-pages shows [webdriver-spec.html](https://github.com/w3c/webdriver/blob/gh-pages/webdriver-spec.html) hasn't been modified in six years, while `index.html` is up-to-date.

I think only parts of the `gh-pages` branch gets automatically updated? We probably want to update the `webdriver-spec.html` on `gh-pages` like we did on `master`: https://github.com/w3c/webdriver/blob/master/webdriver-spec.html

#1585 changed this, and @sideshowbarker may be the one to ask.

**Comment by whimboo** [comment]
We discussed that on IRC and here the reply from @jgraham:

```
I'm not sure, but I don't think it works like that. I think what's going on is that we build the spec to some directory (e.g. build_output), then we checkout the gh-pages branch into some other directory (e.g. gh-pages) and then we effectively copy the files from build_output to gh-pages. So if webdriver_spec.html isn't in build_output it won't get updated even if we change it.
What might work is just checking out the gh-pages branch, updating webdriver_spec.html and pushing the result
```

I've now updated the `webdriver_spec.html` file on the `gh-pages` branch to correctly redirect to the index.html. 

As such we should close the issue as fixed.
