### ISSUE TITLE
Unable to use Spacebar key in WebdriverIO

### ISSUE THREAD

**Issue by ChintanMehta0510** [w3c/webdriver#1756]
I used different ways to use spacebar key but none seem to be working:

browser.keys("\uE00D");
browser.keys("\ue00d");
browser.keys(" ");

My tsconfig.json:

`{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "es2020",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "ES2022",
    "typeRoots": [
      "node_modules",
      "node_modules/@types",
      "node_modules/@wdio",
      "node_modules/async"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "types": [
      "node",
      "jasmine-framework",
      "expect-webdriverio",
      "webdriverio/async",
      "types"
    ],
    "paths": {
      "links there"
      ]
    },
    "useDefineForClassFields": false
  },
  "angularCompilerOptions": {
    "strictTemplates": true
  }
}
`

**Comment by whimboo** [comment]
This seems to be an issue with WebDriver IO. As such please file a new one at: https://github.com/webdriverio/webdriverio. This repository is only for WebDriver specification issues. Thanks.
