### ISSUE TITLE
Error 405 when trying to run a simple swipe test

### ISSUE THREAD

**Issue by LeohsPaixao** [w3c/webdriver#1770]
> 	The requested command matched a known URL but did not match any method for that URL.

![image](https://github.com/w3c/webdriver/assets/42840902/5cb090f0-dd09-41d1-b670-59056703b31f)

Hello guys.

I have a problem in a test swipe for App Android, always what run this test, is return that error: "ERROR webdriver: Request failed with status 405 due to unknown method: Not implemented". And I've already been in some forums and nothing. Please, can someone help me?

My capabilities:
```
"default-capabilities": {
            "platformName": "Android",
            "appium:platformVersion": "13",
            "appium:deviceName": "AppiumAVD",
            "appium:deviceOrientation": "portrait",
            "appium:automationName": "UiAutomator2",
            "appium:appPackage": "com.wdiodemoapp",
            "appium:appActivity": "com.wdiodemoapp.MainActivity"
          },
```

**Versions:**

- Node: 18.0.0
- Appium: 2.2.1
- WebdriverIo: 8.22.1

**Code:**

```
it('Should be able to swipe horizontally', async () => {
        // Elemento alvo para verificar após o swipe
        const targetElement = await $('//android.widget.TextView[@text="GREAT COMMUNITY"]');

        // Obtenha a posição inicial e final para o swipe
        const startX = 0.8; // Porcentagem da largura da tela
        const endX = 0.2; // Porcentagem da largura da tela
        const y = 0.5; // Porcentagem da altura da tela

        const { height, width } = await driver.getWindowSize();

        // Calcula as coordenadas reais
        const startCoords = { x: width * startX, y: height * y };
        const endCoords = { x: width * endX, y: height * y };

        // Realiza o swipe
        await driver.touchPerform([
            { action: 'press', options: startCoords },
            { action: 'wait', options: { ms: 1000 } }, // Pode ajustar o tempo conforme necessário
            { action: 'moveTo', options: endCoords },
            { action: 'release', options: {} },
        ]);

        // Verifica se o elemento alvo está visível após o swipe
        const isTargetVisible = await targetElement.isDisplayed();
        assert.isTrue(isTargetVisible, 'O swipe horizontal falhou ou o elemento alvo não está visível após o swipe');
    });

```

**Comment by LeohsPaixao** [comment]
> > The requested command matched a known URL but did not match any method for that URL.
> 
> ![image](https://user-images.githubusercontent.com/42840902/283536327-5cb090f0-dd09-41d1-b670-59056703b31f.png)
> 
> Hello guys.
> 
> I have a problem in a test swipe for App Android, always what run this test, is return that error: "ERROR webdriver: Request failed with status 405 due to unknown method: Not implemented". And I've already been in some forums and nothing. Please, can someone help me?
> 
> My capabilities:
> 
> ```
> "default-capabilities": {
>             "platformName": "Android",
>             "appium:platformVersion": "13",
>             "appium:deviceName": "AppiumAVD",
>             "appium:deviceOrientation": "portrait",
>             "appium:automationName": "UiAutomator2",
>             "appium:appPackage": "com.wdiodemoapp",
>             "appium:appActivity": "com.wdiodemoapp.MainActivity"
>           },
> ```
> 
> **Versions:**
> 
> * Node: 18.0.0
> * Appium: 2.2.1
> * WebdriverIo: 8.22.1
> 
> **Code:**
> 
> ```
> it('Should be able to swipe horizontally', async () => {
>         // Elemento alvo para verificar após o swipe
>         const targetElement = await $('//android.widget.TextView[@text="GREAT COMMUNITY"]');
> 
>         // Obtenha a posição inicial e final para o swipe
>         const startX = 0.8; // Porcentagem da largura da tela
>         const endX = 0.2; // Porcentagem da largura da tela
>         const y = 0.5; // Porcentagem da altura da tela
> 
>         const { height, width } = await driver.getWindowSize();
> 
>         // Calcula as coordenadas reais
>         const startCoords = { x: width * startX, y: height * y };
>         const endCoords = { x: width * endX, y: height * y };
> 
>         // Realiza o swipe
>         await driver.touchPerform([
>             { action: 'press', options: startCoords },
>             { action: 'wait', options: { ms: 1000 } }, // Pode ajustar o tempo conforme necessário
>             { action: 'moveTo', options: endCoords },
>             { action: 'release', options: {} },
>         ]);
> 
>         // Verifica se o elemento alvo está visível após o swipe
>         const isTargetVisible = await targetElement.isDisplayed();
>         assert.isTrue(isTargetVisible, 'O swipe horizontal falhou ou o elemento alvo não está visível após o swipe');
>     });
> ```

**Comment by whimboo** [comment]
Dear @LeohsPaixao. This repository is basically for the spec work and not around issues with webdriver clients. If there is such an issue please use the webdriver client's issue tracker.

Otherwise please note that `/session/<id>/touch/perform` is not a valid WebDriver classic command. Touch actions are routed through [Perform Actions](https://w3c.github.io/webdriver/#perform-actions) as well.
