### ISSUE TITLE
`Dispatch a pointer down action` has invalid parameters

### ISSUE THREAD

**Issue by ChernyshevDS** [w3c/webdriver#1817]
[`Dispatch a pointerDown action`](https://www.w3.org/TR/webdriver2/#dfn-dispatch-a-pointerdown-action) does not accept input source as a parameter. It seems that `input source` is mixed up with `input state`, because following items do not make sense because `input source` does not have expected properties:

> 3. If the input state's pressed property contains button return [success](https://www.w3.org/TR/webdriver2/#dfn-success) with data [null](https://www.w3.org/TR/webdriver2/#dfn-null).

> 4. Let x be equal to input state's x property.

> 5. Let y be equal to input state's y property.

> 6. Add button to the set corresponding to input state's pressed property, and let buttons be the resulting value of that property.

**Comment by whimboo** [comment]
@ChernyshevDS thanks for reporting the issue. Checking the [table of action algorithms and how to dispatch those](https://www.w3.org/TR/webdriver2/#ref-for-dfn-dispatch-a-pointerdown-action-1) it is clear that the second argument indeed has to be the `source`. You can see this as well for the `[Dispatch a pointerUp action](https://www.w3.org/TR/webdriver2/#dfn-dispatch-a-pointerup-action)` case.

Would you be interested to fix this bug in the specification? We would appreciate.

**Comment by ChernyshevDS** [comment]
@whimboo Sure, I've created a PR: https://github.com/w3c/webdriver/pull/1820

**Comment by whimboo** [comment]
Fixed by #1820.
