### ISSUE TITLE
Blaze

### ISSUE THREAD

**Issue by Higlison** [w3c/webdriver#1845]
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# Configuração do driver do navegador (exemplo com Chrome)
driver = webdriver.Chrome(executable_path='CAMINHO_PARA_SEU_CHROMEDRIVER')

# Acessa o site da Blaze
driver.get("https://blaze.com/pt/games/double")

# Loop para capturar os últimos resultados
while True:
    resultados = driver.find_elements(By.CLASS_NAME, 'entry')
    for resultado in resultados:
        print(resultado.text)  # Captura e exibe os resultados
    time.sleep(60)  # Captura a cada minuto

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines]. Also please provide your answer in English. Thanks.

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by whimboo** [comment]
If you have issues with chromedriver or automating a specific scenario this is not the right place to report. This repository is for specification issues only. Instead use the chromedriver or Selenium issue tracker. Thanks.
