### ISSUE TITLE
Investigate defining what a response is

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#336]
We define what a _command_ is but we are only loosely talking about responses. In fact, we talk about two different type of responses: those that are results of executing WebDriver commands, and those that are returned as part of running the _navigate_ algorithm from HTML.

**Comment by shs96c** [comment]
I think the spec is pretty clear about what to return to the local end (in the `send a response` definition) and we link to the relevant specs where we're talking about navigation responses. 

Closing, but feel free to reopen if you disagree.
