### ISSUE TITLE
Switch to Window doesn't specify what to do with the current browsing context

### ISSUE THREAD

**Issue by juangj** [w3c/webdriver#338]
It sets the current top-level browsing context, but not the current browsing context.

The only real ambiguity comes when "Switch to Window" is called with the handle of the current top-level browsing context (i.e., is a no-op):
* Marionette does not change the current browsing context.
* All other driver implementations I'm aware of (including Microsoft WebDriver and Apple SafariDriver) set the current browsing context to the top-level context, which seems to me like the right approach.

**Comment by andreastt** [comment]
The correct behavour is to (re)set the current browsing context.

**Comment by juangj** [comment]
OK, I'll file a Marionette bug about this, then.

**Comment by andreastt** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1305822

**Comment by shs96c** [comment]
https://github.com/w3c/webdriver/pull/339
