### ISSUE TITLE
Update timeouts to have a GET HTTP Verb to return details

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#348]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=25012

Marc Fisher:

> I believe this was discussed at the F2F, but regardless, it would be useful to be able to get the current value for a timeout.

**Comment by andreastt** [comment]
David Burns :automatedtester
> Action is described in http://www.w3.org/2014/07/07-testing-minutes.html#action10

**Comment by andreastt** [comment]
David Burns :automatedtester:
> This will be added

**Comment by AutomatedTester** [comment]
This has already been added
