### ISSUE TITLE
Proposal: Shadow DOM support in WebDriver

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#350]
Marc Fisher:

> The current proposal for dealing with Web Components and their corresponding Shadow DOMs in WebDriver treats them similarly to frames; at any point in time the WebDriver session is operating within a particular DOM, either the top-level DOM or one of the Shadow DOMs of a particular Web Component. However, this makes interacting with pages that use Web Components extremely taxing, as the current DOM will have to be switched on a regular basis, and it is unclear over what time frame an element id found within a particular DOM will be considered valid. Instead I propose that the WebDriver wire protocol be extended with commands to get the list of attached Shadow DOMs for an elements as opaques IDs and to support new element and elements commands that are scoped to a particular DOM.  Additionally, element IDs from Shadow DOMs be completely accessible as long they are the corresponding element attached to the Shadow DOM and the Shadow DOM is attached to the page.
> 
> For a more thorough description see:
> https://docs.google.com/document/d/1qP7Se3MDUac5P0V1Kfm2yaj3fFhBOFCyWyXLcsVwkTA/edit?usp=sharing

**Comment by andreastt** [comment]
chrisgao@google.com:
>  Do we want to make it explicit in spec which commands are supported with Shadow DOM roots?
eg.: FindElement, FindElements, ExecuteScript, ExecuteAsyncScript, GetActiveElement and the like.

**Comment by andreastt** [comment]
Marc Fisher:
> Of the current commands that take a WebElement:
>
> findElement and findElements: Search scoped to the Shadow DOM.
>
> execute[Async]Script: if a Shadow DOM root is passed as parameter it should be resolved to the correct ShadowRoot instance (http://www.w3.org/TR/shadow-dom/#shadow-root-object).
>
> Any other command that takes an element id (e.g. isSelected, getElementAttribute, getText) should throw an exception if passed a Shadow DOM root. None of the current set of status codes seem appropriate, so maybe add a new one "operation not supported on shadow dom root".
>
> It may be reasonable to add an optional element id parameter to the following commands:
>
> getActiveElement: returns ShadowRoot.activeElement
>
> getSource: returns ShadowRoot.innerHTML
>
> If added, these commands should probably throw an exception if the element id doesn't correspond to a shadow dom root: "operation only supported on shadow dom root".

**Comment by andreastt** [comment]
chrisgao:
> Update the patch for shadow dom according to the discussion in the F2F meeting at TPAC 2013.

Attachment: https://gist.github.com/andreastt/dcf4be00273f8ea55e37ef7c65d48881

**Comment by TakayoshiKochi** [comment]
Hi, I'm coming from w3c/webcomponents, and this issue seems relevant...

From a glance at the spec, the commands seem not at all aware of shadow roots or shadow trees:
https://w3c.github.io/webdriver/#list-of-endpoints

Is this still any of the interest from webdriver community?
This has been left for 1.5 years, but there are definitely interests from web testing community to access shadow trees, e.g. https://github.com/GoogleChrome/puppeteer/issues/858 or https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/ScMLN_Hj52E/discussion.

The main painpoint is that finding a specific element in the whole document including shadow trees, such as finding elements with class `foo`.

Is there anyone else who is interested in moving this forward?

**Comment by AutomatedTester** [comment]
switch to shadow dom proposal in #1320

**Comment by aslushnikov** [comment]
> The main painpoint is that finding a specific element in the whole document including shadow trees, such as finding elements with class foo.

@TakayoshiKochi we think we found a nice approach to deal with Shadow DOM in Puppeteer: ["JS Path"](https://github.com/GoogleChrome/puppeteer/issues/858#issuecomment-438540596). It's pretty light-weight and had a very positive initial feedback from our clients.

**Comment by AutomatedTester** [comment]
@aslushnikov That appears to only work for open Shadow DOM. With WebDriver we could just evaluate script and work with the returned element and it would work the same as it does in puppeteer.

**Comment by jgraham** [comment]
I think we can close this issue now we have basic shadow dom support. Any additional feature requests should go in new issues.
