### ISSUE TITLE
Touch gestures API doesn't provide a way to do slow swipe

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#355]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=25293

Andrey Botalov:

> Take a look at https://github.com/appium/appium/blob/master/docs/gestures.md.
> 
> It provides two different API calls: swipe and flick.
> 
> It seems that flick is just a quick swipe (not sure). The spec doesn't currently provide a way to do a slow swipe.

**Comment by andreastt** [comment]
Andrey Botalov:
> Also both swipe and flick seem to be a different thing than a combination of tap + moveTo (not sure).

**Comment by andreastt** [comment]
David Burns :automatedtester:
> Unfortunately swipe and flick on some OSes mean the exact same thing, which allowing a "speed" may solve. This will probably be on the move() method. Still to be determined

**Comment by shs96c** [comment]
The Actions commands give us a nice place to build from here.

**Comment by andreastt** [comment]
I believe this is addressed through pointerDown taking a duration argument.
