### ISSUE TITLE
Close window should define which content is active after window closes

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#358]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26486

Andreas Tolfsen:
> The close window section doesn't define which default content (strange term I think, why isn't this “context”?) is active when the current default content is closed.

**Comment by shs96c** [comment]
The user is expected to issue a "Switch To Window" command after closing a window.

**Comment by andreastt** [comment]
I think it does now. Closing.
