### ISSUE TITLE
Element location strategies for link text and partial link text references example

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#359]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26487

Andreas Tolfsen:
> The element location strategies for link text [1] and partial link text [2] references examples in pseudo code which doesn't make any sense.  Besides this is uses the very misleading term “visible text” which is not further defined.
>
> It clearly borrows the algorithm used for getting an element's text [3], so perhaps this algorithm should be generalized? 
>
> 1. https://dvcs.w3.org/hg/webdriver/raw-file/tip/webdriver-spec.html#link-text
> 2. https://dvcs.w3.org/hg/webdriver/raw-file/tip/webdriver-spec.html#partial-link-text
> 3. https://dvcs.w3.org/hg/webdriver/raw-file/tip/webdriver-spec.html#widl-WebElement-getElementText-DOMString

**Comment by shs96c** [comment]
No longer valid.
