### ISSUE TITLE
Closing a window refers to "quit" which doesn't exist

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#361]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26496

Andreas Tolfsen:
> The section on DELETE /session/{sessionId}/window, that is for closing a window, refers to calling the function "quit", which (a) isn't defined and (b) isn't relevant anymore.
>
> Instead it should point to DELETE /session/{sessionId}.
>
> See also [bug 26495](https://www.w3.org/Bugs/Public/show_bug.cgi?id=26495).

**Comment by shs96c** [comment]
No longer valid.
