### ISSUE TITLE
POST /session/{id}/timeouts should take an array of timeouts

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#363]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26613

Andreas Tolfsen:

> Currently POST /session/{id}/timeouts takes a hash map of {"type": TYPE, "ms": N} which allows setting individual timeouts.
> 
> If we consider a local end client binding that wants to set them all at once (pseudo code):
> 
> ```
> driver.timeouts = [{type: "page load", ms: 123},
>                    {type: "implicit", ms: 456},
>                    {type: "script", ms: 789}]
> ```
> 
> This will currently require them to make three individual calls to the endpoint.
> 
> An optimization is to allow the endpoint to take an array of dicts instead:
> 
> ```
> [{"type": TYPE, "ms": N}, …]
> ```

**Comment by shs96c** [comment]
No longer an issue with the way that `Set Timeouts` is defined in the spec now.
