### ISSUE TITLE
Ordering of array of web elements returned is undefined

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#364]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26706

Andreas Tolfsen:
> The only element location strategy that mentions ordering of the returned web elements is the CSS selector in section 9.2.1, and it uses a reference to querySelectorAll.  If drivers choose to implement this differently it feels to me that we should define the sorting order explicitly or reference the ECMAScript specification's.
>
> This is further complicated by the other location strategies not having ordering defined.
>
> Link to relevant section:
>
> https://dvcs.w3.org/hg/webdriver/raw-file/tip/webdriver-spec.html#element-location-strategies

**Comment by shs96c** [comment]
Elements should be returned in the order in which they appear in the DOM.

**Comment by andreastt** [comment]
I think this is sufficiently defined.
