### ISSUE TITLE
Describe data structures coming over the wire with a JSON schema instead of WebIDL

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#365]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26707

Andreas Tolfsen:

> The WindowSize dictionary [1] uses the data type double for height/width but this isn't supported in JSON which only has a number type [2] (which may be extracted to an integer or float in the local end).
>
> (Furthermore ElementRect may use floats for the positioning of elements in the DOM, e.g. .5px, but WindowSize uses integers as no window managers support half pixels.)
>
> 1. https://dvcs.w3.org/hg/webdriver/raw-file/tip/webdriver-spec.html#dictionary-windowsize-members
> 2. http://www.ietf.org/rfc/rfc4627.txt

**Comment by andreastt** [comment]
David Burns :automatedtester:
> *** [Bug 26704](https://www.w3.org/Bugs/Public/show_bug.cgi?id=26704) has been marked as a duplicate of this bug. ***

**Comment by andreastt** [comment]
David Burns :automatedtester:
> This is because WebIDL does not have a number type so updating bug to what the real issue is

**Comment by shs96c** [comment]
Everything is now being described by hand. Closing.
