### ISSUE TITLE
Getting window position isn't defined

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#366]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26708

Andreas Tolfsen:
> There is no way currently to get a window's position, you can only set it [1].
>
> 1. https://dvcs.w3.org/hg/webdriver/raw-file/tip/webdriver-spec.html#resizing-and-positioning-windows

**Comment by shs96c** [comment]
No longer valid
