### ISSUE TITLE
Unclear what happens if maximizeWindow maximizes window and is called again

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#368]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26710

Andreas Tolfsen:
> If maximizing the browser window is supported and the window gets maximized upon calling maximizeWindow or the window is somehow already maximized and maximizing the window is supported, it's unclear from reading the spec what happens if it's called again.
>
> Should calling it again de-maximize it, that is defer to the window manager what position and dimensions to set the window to?  In this case, should the command really be called “maximize” when what it does is toggling?

**Comment by shs96c** [comment]
The spec clearly says "Maximize Window command invokes the window manager-specific “maximize” operation". The result of multiple calls is specific to the window manager, and cannot be mandated by the spec. Closing.
