### ISSUE TITLE
maximizeWindow needs an algorithm

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#370]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26712

Andreas Tolfsen:
> The maximize window section needs an algorithm as it's currently very confusing how it should be implemented by the driver.
>
> Specifically the first paragraph talks about whether the window manager understands the concept of maximization; presumably the driver should return with an error if this isn't supported by the WM.
>
> (It also talks about the return type void which isn't accurate.  Also [bug 26711](https://www.w3.org/Bugs/Public/show_bug.cgi?id=26711).)

**Comment by shs96c** [comment]
It now has one. Closing.
