### ISSUE TITLE
Ability to take screenshots of containers like flash/java

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#373]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27177

Alexei Barantsev:
> It should be explicitly claimed ability or inability to take screenshots of "external" elements like Java applets, Flash/Flex objects, may be canvas too.

**Comment by shs96c** [comment]
Reading the text for "drawing a bounding box from the frame buffer" (https://www.w3.org/TR/webdriver/#dfn-draw-a-bounding-box-from-the-framebuffer) it's already stated that how this is done is implementation specific. This implies that the spec can't be explicit about what's captured and what's not.
