### ISSUE TITLE
Need clarification on JavaScript execution when Content Security Policy is in place

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#374]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27223

Jim Evans:

> If a page has a Content Security Policy applied (spec: https://w3c.github.io/webappsec/specs/content-security-policy/), it may prevent the execution of user-supplied JavaScript via the executeScript command. This is because the injected JavaScript would have no source which could be validated by the policy. The WebDriver spec should have language describing how a driver should behave in this event.

**Comment by shs96c** [comment]
This came up recently in the web driver user list. Apparently we need this to be clear.
