### ISSUE TITLE
Default value of parameters in command is array

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#376]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27765

Andreas Tolfsen:
> In section 2.1 it says that the default value of the parameters field should be an empty array, but the type is an object.  Also an array cannot be named:
>
> “The parameters attribute is a map of named parameters to objects representing the value of the parameter. The default value is an empty array and this field MUST NOT be null.”

**Comment by shs96c** [comment]
I don't think that this valid any more.
