### ISSUE TITLE
Clarify whether sessionId is optional from the perspective of the local end before newSession

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#377]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27766

Andreas Tolfsen:
> Section 2.1 says that sessionId by default is null, but the WebIDL marks it as optional.
>
> It's called out explicitly on the other parameters to the command object which are to be provided by the local end, but it's unclear if this applies to sessionId.
>
> The question is whether sessionId should be undefined or null when calling newSession.
>
> Since the spec allows a passing in a sessionId to newSession, it follows that local ends shouldn't send null to mean “undefined” since that (in section 4.1.1) talks about whether the field is “set” or not.

**Comment by shs96c** [comment]
No longer valid
