### ISSUE TITLE
Script timeout should also apply for synchronous scripts

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#378]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27949

Andreas Tolfsen:

> Section 13.1.1 says the script timeout set only applies for executeAsyncScript.  It should also apply for executeScript.

**Comment by shs96c** [comment]
It's tempting to rephrase "execute script" as being a call to "execute async script" that blocks on the remote end until the callback is called. Removing the synchronous endpoint isn't going to play well with the Selenium As A Service options out there.

**Comment by AutomatedTester** [comment]
It's heavily used and I would rather not create a potential footgun between implementors and the selenium project at this late stage.
