### ISSUE TITLE
executeScript and executeAsyncScript algorithms should respect the script timeout

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#379]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27950

Andreas Tolfsen:

> The executeScript and executeAsyncScript algorithms make no mention of the script timeout global.  They should timeout when this is reached, or run indefinitely if -1 (negative integer) is given.
> 
> Section 13.1.1 mentions that "script timeout" can be used in this way, but the algorithms don't reflect this.

**Comment by andreastt** [comment]
jleyba:
> executeAsyncScript does reference timeout (step 1 in the algorithm in 10.3.1). Link to the timeout command needs to be updated though.

**Comment by AutomatedTester** [comment]
merging this with #380
