### ISSUE TITLE
Use null to indicate unlimited script timeout

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#380]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27951

James Graham:

> Since we are using JSON we don't have to pack magic values into integers. null seems like a sensible choice for unsetting the script timeout (or, rather, setting it to an indefinite value), and negative values should cause an error.

**Comment by andreastt** [comment]
Andreas Tolfsen:
> +1

**Comment by AutomatedTester** [comment]
@jgraham what is the use case for this?

The thing I am trying to get my head around is what should we do if we get to the HTTP timeout. The local ends are likely to have timed out after ~60 seconds which will leave the remote end in a undefined state.

**Comment by jgraham** [comment]
Well that's always a problem, right? There's no guarantee that the HTTP timeout has any specific value.

The use case is "having a script that might run for an indefinite amount of time" (e.g. I have used execute_script("") with a very long timeout to check if the browser was closed by a human).
