### ISSUE TITLE
send "invalid argument" error if value for POST /session/{sessionId}/element/{id}/value isn't an array

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#382]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28344

Andreas Tolfsen:
> POST /session/{sessionId}/element/{id}/value should return an "invalid argument" error if the type of value isn't a sequence/array.
>
> We should probably also figure out what to do with illegal content inside the sequence.

**Comment by shs96c** [comment]
No longer valid.
