### ISSUE TITLE
Send "invalid argument" error if file does not exist

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#383]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28382

Andreas Tolfsen:

> On sending keys to an <input type=file> element we should send back an "invalid argument" error with a helpful message if the file you try to set doesn't exist.  
> 
> As there may be guards against setting invalid/non-existing files in UAs, we should avoid doing so as it may cause the driver to have an internal error.

**Comment by shs96c** [comment]
This is in "Element Send Keys"
