### ISSUE TITLE
implicit timeout does not return a timeout response

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#384]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28756

John Jansen:

> CURRENTLY 
> "implicit - Set the amount of time the driver should wait when searching for elements. When searching for a single element, the driver should poll the page until an element is found or the timeout expires, whichever occurs first. When searching for multiple elements, the driver should poll the page until at least one element is found or the timeout expires, at which point it should return an empty list."
> 
> EXPECTED:
> implicit - Set the amount of time the driver SHOULD wait when searching for elements. When searching for a single element, the driver should poll the page until an element is found or the timeout expires, whichever occurs first. When searching for multiple elements, the driver should poll the page until at least one element is found or the timeout expires. If the timeout expires before the driver has finished polling the page, the driver MUST return a "<code><a href="#status-timeout">timeout</a></code>" response.

**Comment by shs96c** [comment]
I don't think that this is valid any more. Closing.
