### ISSUE TITLE
Order window handles

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#386]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=29003

Andreas Tolfsen:
> Quoting thephilwells from https://github.com/w3c/webdriver/issues/39:
>
> Using the Java API, one should be able to do this
>
> List<String> handles = driver.getWindowHandles();
> driver.switchTo().window(handles[1]);
>
> ..and able to reliably expect that they are viewing the second-oldest open window. This matters most when more than two windows are open, as when one needs to open more than one new window from the original window.

**Comment by shs96c** [comment]
The Java API being quoted uses a set with undefined ordering, and no selenium implementation has ever guaranteed that window handles are returned in the order in which they're open.

The correct way to detect a new window is open is to collect the set of window handles before an operation, perform the operation, and then get the difference of the new set of window handles.

Closing this issue.
