### ISSUE TITLE
executeScript and execureAsyncScript don't specify how to handle alerts that can appear during execution

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#387]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=29134

Alexei Barantsev:

> executeScript and execureAsyncScript don't specify how to handle alerts that can appear during execution

**Comment by AutomatedTester** [comment]
Currently Selenium does not handle this case either. I am tempted to just leave a note that if one appears the next command may fail unless the local end sends a command to handle the modal.

**Comment by AutomatedTester** [comment]
This is handled already in https://w3c.github.io/webdriver/webdriver-spec.html#dfn-execute-a-function-body
