### ISSUE TITLE
Does it make sense to require the use of "unknown error"?

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#389]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=29168

juangj:

> From 8. Invalid SSL Certificates:
> 
> "In this case, implementations may choose to make accessing a site with bad HTTPS configurations cause a WebDriverException to be thrown. Remote end implementations must return an unknown error error code in this case."
> 
> It seems odd to say that the remote end MUST return an "unknown error" in a case where we know exactly what the error is. There doesn't seem to be any other fitting error code, though.
> 
> Is "unknown error" intended to just be the catch-all for errors that don't fit any of the other error codes?

**Comment by andreastt** [comment]
James Graham:
> For the SSL case we'll implement a new error.

**Comment by shs96c** [comment]
No longer valid, as the case that @jgraham mentions has been handled. Closing.
