### ISSUE TITLE
getWindowHandles() should return a list of windows ordered by window age

### ISSUE THREAD

**Issue by thephilwells** [w3c/webdriver#39]
Using the Java API, one should be able to do this

```
List<String> handles = driver.getWindowHandles();
driver.switchTo().window(handles[1]);
```

..and able to reliably expect that they are viewing the second-oldest open window.  This matters most when more than two windows are open, as when one needs to open more than one new window from the original window.

**Comment by andreastt** [comment]
As I understand it, limitations in UAs and backwards compatibility with Selenium are the reasons the order of [Get Window Handles](https://w3c.github.io/webdriver/webdriver-spec.html#getwindowhandles) is left at the discretion of the UA.

**Comment by andreastt** [comment]
Filed this as https://www.w3.org/Bugs/Public/show_bug.cgi?id=29003 in the bug tracker so the WG can discuss it.

**Comment by andreastt** [comment]
@AutomatedTester We should probably close this issue tracker.
