### ISSUE TITLE
Element Click should specify how to handle multi selects

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#393]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=29503

clmartin:

> Currently the spec doesn't specify how Click() should work on a multi-select option. In Chrome and Firefox, they perform a toggle instead of a click command. This means the option that has been "clicked" actually just toggles that option on/off. In Edge an actual click happens, which in a multi-select means the same element is clicked and the selection is never cleared.

**Comment by andreastt** [comment]
John Jansen:
> note: dom event discussion with select lists as well...

**Comment by andreastt** [comment]
Simon Stewart:
> Chrome and Firefox are doing the Right Thing, IMO. "Click" is a "do what I mean" API.

**Comment by andreastt** [comment]
clmartin:
> I'm curious why Chrome/Firefox's implementation is thought to be the right thing? A user cannot reproduce what Chrome/Firefox do in this case. If a user clicks an item in a multi-select it selects that item. If they click it again it doesn't deselect that item. If the goal is to be true to what a browser/user would actually do/see when clicking a mouse on a multi-select then Firefox/Chrome wouldn't actually be doing what's right.
>
> Here is a jsfiddle example:
> https://jsfiddle.net/oxen65bj/
>
> Click once: Selects that option
> Click same option 2nd time: Selects that option
> Ctrl + Click same option: Deselects that option
> Ctrl + Click other options: Selects those options in addition to the original option
> Shift + Click: Select a range from the currently selected option to the clicked option
>
> The appropriate way to deselect an option is to hold Ctrl and then Click the option you had selected. I would argue that this should be the approach. It would also offer other ways for users to do selections (seen above using Ctrl/Shift to select multiple).
>
> If one of the goals is to have WebDriver truly implemented as how the browser would do a click or send a key and fire events and such, I'd argue this is the route we should take. Otherwise we have a one-off functionality for clicking when it's a multi-select that doesn't actually do a click but instead some magic behind the scenes.

**Comment by shs96c** [comment]
The reason is two-fold:

1. This is how Selenium WebDriver has worked for a long time, and it's a user expectation.
2. More importantly, there's no way to clear a single entry in a multiple select using any existing APIs. We don't believe that the advanced user interaction APIs are sufficient for this given the many ways that selects are implemented.

The alternative would be for the clear command to be used, and for the user to select each item in the select uniquely each time. My preference is to maintain existing behaviour where possible.

**Comment by shs96c** [comment]
Closed by 189e57daaf67df03676273c208feb08ef681ed07
