### ISSUE TITLE
Specific error code doesn't exist for blocked element not being clickable

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#395]
James Reed:

> There is no entry in https://w3c.github.io/webdriver/webdriver-spec.html#handling-errors for an error code that is specific for an element not being clickable because it is blocked by another element being in front of it. I currently have a pull request open (https://github.com/SeleniumHQ/selenium/pull/1967) and was asked to open this spec bug to support it.

**Comment by andreastt** [comment]
James Reed:
> The error code I propose (and that is in my pull request) is: "element intercepting click".

**Comment by andreastt** [comment]
Brain Burg:
> A few questions
>
>  - What endpoints would be able to throw this error?
>  - In what circumstances would this be thrown? How is it computable?
>
> From a UA point of view, it doesn't make a whole lot of sense because clicks are specified in terms of coordinates, not a target element.
>
> In the WebDriver specification, the "Element Click" endpoint can already throw "element not visible" if the element is not displayed at all. (Without looking it up, I don't know how displayedness is related to full occlusion or translucent elements.)
>
> The terminology "intercepting click" assumes too much. If the occluded element is an ancestor of the visible element on top, then the ancestor will still receive a click event in the bubbling phase if propagation is not stopped earlier.

**Comment by andreastt** [comment]
James Reed:
> (In reply to Brian Burg from comment #2)
> A few questions
> 
>  - What endpoints would be able to throw this error?
>  - In what circumstances would this be thrown? How is it computable?
> 
> From a UA point of view, it doesn't make a whole lot of sense because clicks
> are specified in terms of coordinates, not a target element.
> 
> In the WebDriver specification, the "Element Click" endpoint can already
> throw "element not visible" if the element is not displayed at all. (Without
> looking it up, I don't know how displayedness is related to full occlusion
> or translucent elements.)
> 
> The terminology "intercepting click" assumes too much. If the occluded
> element is an ancestor of the visible element on top, then the ancestor will
> still receive a click event in the bubbling phase if propagation is not
> stopped earlier.
>
> Sorry if this wasn't clear - this isn't an error that is a precursor to being able to reliably tell when an element is being occluded or anything like that, I simply want to improve the existing functionality for what happens when you currently try to click an element that (according to webdriver) is visible but is blocked by another element (a header or footer are good examples).
>
> This is different to element not visible in that the element that is trying to be clicked has passed the test of whether it is visible or not according to webdriver, but when it has tried to be clicked, the "Unknown error" with the message "Other element would receive the click" is returned making it impossible to filter for this error without doing a much more broad filter on an error higher up the hierarchy.
>
> Again, apologies if this isn't all clear or concise, it's my first time contributing to selenium in general and as part of the contribution (see my pull request) I was requested to log a spec bug to add the new error code.
>
> Thanks,
>
> James

**Comment by shs96c** [comment]
I'm not sure if this could be implemented consistently between browsers. Perhaps it'd be better to use the "element not interactable" error with a meaningful message

**Comment by shs96c** [comment]
Adding a reference to #299 which this is all about.
