### ISSUE TITLE
"relevant Element Location Strategy" is undefined

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#396]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=29654

James Graham:

> "Let elements returned be the result of the relevant Element Location Strategy call with arguments all, start node, . "
> 
> The spec doesn't define how to go from a /location strategy/ string to a set of steps to run. It also doesn't define what to do when the /location strategy/ isn't one of the allowed ones.

**Comment by shs96c** [comment]
This has been fixed (refers to the "find" algorithm in section 11). Closing.
