### ISSUE TITLE
Specify error behaviour when the current browsing context does not exist

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#397]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=29691

Alan Jeffrey:

> The webdriver spec should say what to do in the case that the current browsing context no longer exists, for example if it is an iframe that is removed from the current document.
> 
> Some IRC chat on #servo: http://logs.glob.uno/?c=mozilla%23servo&s=10+Jun+2016&e=10+Jun+2016#c453675

**Comment by shs96c** [comment]
The behaviour in selenium is to leave the current browsing context unchanged until the user changes it. This means that if a frame or window is removed, subsequent calls should fail with a "no such window" error (which can probably be handled in the `Processing Model` section.

This mirrors what we do when an action causes a new window or frame to appear --- we leave the current browsing context alone until the user does something.

**Comment by shs96c** [comment]
I note that many commands already do a check for the current browsing context. I'll put together a diff to add the check to those commands that lack this check but should have it.

**Comment by andreastt** [comment]
We can’t handle this in the overall processing algorithm since certain commands are meant to work even if the current browsing context doesn’t exist. @shs96c is right that certain commands check for the current _top-level_ browsing context, but I do believe we are missing checks for the current browsing context for some commands.

For example if you’ve switched to a frame, the current top-level browsing context is now the owner document’s window’s context, but the current browsing context would be the context of the window of the `<iframe>`.

This would i.e. apply to those commands that directly interact with or manipulate the DOM, such as finding elements, clicking, sending keys, &c.

**Comment by shs96c** [comment]
I have a PR to fix the issue that @andreastt just raised.
