### ISSUE TITLE
WebDriver spec is a REST API spec and should be documented like one

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#399]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=29741

uchuugaka:
> As the WebDriver spec is fundamentally a REST API spec, it makes sense to use a documenting format to define the spec in a clear, unmistakable terms and format.
>
> I would propose using RAML 1.0 as the API spec for WebDriver.
> http://raml.org
>
> This makes it more consistent and clear and widely machine readable and human readable and maintainable.

**Comment by shs96c** [comment]
A machine readable format would be nice, but the spec as written is clear enough to be implemented.
