### ISSUE TITLE
Logging to be defined in writing

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#406]
Andreas Tolfsen:

> The logging API was discussed at the F2F in Boston, but not written down anywhere.  The section needs to be filled out.

**Comment by monolithed** [comment]
Google supports [performance logging](https://sites.google.com/a/chromium.org/chromedriver/logging/performance-log) as well. It would be nice to include one

**Comment by shs96c** [comment]
The design discussed in the F2F allowed multiple named log types. I think we included performance in that discussion.

**Comment by praveen4463** [comment]
Is there any update here after more than 1 year?

**Comment by shs96c** [comment]
Not yet.

**Comment by deepakbitragunta** [comment]
Is there any update/ETA for this change?

**Comment by andreastt** [comment]
I wrote a little bit about the state of things in the geckodriver issue tracker:
https://github.com/mozilla/geckodriver/issues/284#issuecomment-456073771

**Comment by duraki** [comment]
Any update on this? @andreastt

**Comment by shahjinav09** [comment]
Any plans to pick this up?

**Comment by whimboo** [comment]
@jgraham I assume that we can close this issue now given that WebDriver BiDi has the [`log.entryAdded`](https://w3c.github.io/webdriver-bidi/#event-log-entryAdded) event included.
