### ISSUE TITLE
Define minimise window

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#407]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26283

Luke Inman-Semerau:

> action item from February F2F

**Comment by andreastt** [comment]
David Burns :automatedtester:
> Ping John!

**Comment by andreastt** [comment]
John Jansen:
> Initial draft. Needs work. https://github.com/w3c/webdriver/compare/master...MicrosoftEdge:johnjan/minimizeWindow

**Comment by andreastt** [comment]
Andreas Tolfsen:
> This has still not been implemented.

**Comment by AutomatedTester** [comment]
landed in 4850eea
