### ISSUE TITLE
scrollIntoView section doesnt take into account overflow:scroll

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#408]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=29687

David Burns :automatedtester:

> Selenium scrolls elements that have a parent with overflow:scroll before interacting with that element.
> 
> We need to describe this in the specification as well otherwise people will not be able to click on elements.

**Comment by andreastt** [comment]
Andreas Tolfsen:
> But scrollIntoView appears to do the right thing when the parent has overflow: scroll set: https://sny.no/e/scrollparent

**Comment by AutomatedTester** [comment]
Looks like we do not take into account frames that we need to scroll to a containing frame.

See 

testShouldBeAbleToClickElementInATallFrame
testShouldBeAbleToClickElementInAFrameThatIsOutOfView

from Python Selenium tests

**Comment by shs96c** [comment]
@AutomatedTester are you working on this, or should we leave it unassigned?
