### ISSUE TITLE
Typing keys algorithm should special case input type=file elements where multiple files are allowed.

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#409]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=23876

Andreas Tolfsen:

> The typing keys section specifies key-based interaction with web elements that are interactable.  There's no special casing of input type=file elements which, from a driver perspective, requires special handling.
> 
> My suggestion is that we allow that to short-curcuit the algorithm and leave the steps to fill filename(s) into the field undefined since the widgets are radically different depending on user agent and operating system.
> 
> As we discussed at the F2F in Boston we also need to cover input type=file multiple elements.
> 
> Link to the section:
> 
>   https://dvcs.w3.org/hg/webdriver/raw-file/tip/webdriver-spec.html#typing-keys

**Comment by andreastt** [comment]
Andreas Tolfsen:
> Following up on the point about input type=file multiple:  The resolution from our F2F in Boston was to follow the logic that sendKeys, by default, appends.  Provided the user agent supports the concept of multiple, calling it a second time would append another file.  If the user agent doesn't understand this concept, it will replace the set file.
>
> Link to the resolution:
>
>     http://www.w3.org/2013/06/13-testing-minutes.html#item08

**Comment by andreastt** [comment]
Alexei Barantsev:
> Another aspect is: should we check presense of the file or not?

**Comment by andreastt** [comment]
Andreas Tolfsen:
> (In reply to Alexei Barantsev from comment #2)
>> Another aspect is: should we check presense of the file or not?
>
> This is out of scope for WebDriver and is enforced by the user agent.

**Comment by andreastt** [comment]
Alexei Barantsev:
> Unfortunately it is *not* enforced, see https://code.google.com/p/selenium/issues/detail?id=7276

**Comment by andreastt** [comment]
David Burns :automatedtester:
> This was put in in https://github.com/w3c/webdriver/commit/de28aa7427f4aea3e3d07e433ae58a8485a72c58
>
> Only missing piece is `<input type=file multiple>`.

**Comment by andreastt** [comment]
David Burns :automatedtester:
> subsequent calls to element.send_keys(path) to <input type=file multiple> would append. This needs to be added to the specification

**Comment by twalpole** [comment]
Having no way to set multiple files in one call means there is no way to properly test sites that allow for multiple file selections since the generated events will be for each file separately.  If the user can select multiple files and only get one change event shouldn't this API support the same behavior?

**Comment by andreastt** [comment]
I don’t think there is any way we can realistically change the spec at this point in time. I believe that edge case is a known problem.

**Comment by shs96c** [comment]
Perhaps one option would be to use the null character to separate paths.

**Comment by twalpole** [comment]
@shs96c chromedriver supports it with \n as the separator, but null could work too.

**Comment by andreastt** [comment]
I disagree quite strongly that we should change the API at this point.

**Comment by twalpole** [comment]
@andreastt How is this a change in the API?  The current webdriver spec states "Need to handle <input type=file multiple>"  as Issue 9.  If the parameter passed is a character array that gets split on \n or \0 during the handling of <input type=file multiple> the API is still the same.

**Comment by andreastt** [comment]
We agreed at the last F2F that it should not receive a character array, but a string of grapheme clusters. But more to the point, specifying an alternate way to break up input implies existing implementations must change.

**Comment by twalpole** [comment]
@andreastt Ok, so the current working draft of the WebDriver spec specifies a character array but that is going to be changing to a string of grapheme clusters at some point in the near future. So the API is actually going to be changing shortly, but allowing for a separator to be used at that time for multiple files is too big of change?

**Comment by shs96c** [comment]
There is now wording in the spec for using `Element Send Keys` to set multiple files, based on the existing chrome implementation of using `\n`. We should move further discussion to the mailing lists if we feel it's necessary.
