### ISSUE TITLE
Interactable elements displayed except <input type=file>

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#411]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26849

Leo Gallucci:
> As per discussion in https://code.google.com/p/selenium/issues/detail?id=7625#c15
>
> I suggest adding an exception to [14.1 Interactable elements](https://dvcs.w3.org/hg/webdriver/raw-file/tip/webdriver-spec.html#interactable-elements) for the case in which the element is an `<input type=file>` given the new html5 upload components that hide this input, enforcing that "The element must be displayed, as defined in section 10.1." just doesn't scale here.

**Comment by shs96c** [comment]
No longer valid since we don't handle displayed-ness in the spec.
