### ISSUE TITLE
Selenium Returns RGBA when it is giving a colour

### ISSUE THREAD

**Issue by AutomatedTester** [w3c/webdriver#417]
In chapter [11. Element State](https://w3c.github.io/webdriver/webdriver-spec.html#get-window-handle#h-element-state), section [11.4 Get Element CSS Value](https://w3c.github.io/webdriver/webdriver-spec.html#get-window-handle#h-get-element-css-value):

> Let body be a JSON Object with the "value" member set to computed value. 

We should probably say that we need to coerce it to RGBA if we just get RGB.

**Comment by andreastt** [comment]
I’m quite sure we decided at some earlier point not to coerce into RGBA and instead just return whatever the browser returns, which is RGB or RGBA depending on whether an alpha channel is set.

This is specced in CSSOM as [‘serializing a CSS component value’](https://drafts.csswg.org/cssom/#serialize-a-css-component-value).

The problem with coercion is that you need to predefine a list of properties that can grow in the future, making the spec future incompatible. Also I’m quite sure

**Comment by shs96c** [comment]
Can we not just say that "when serialising a CSS component value that is a colour, always serialise as rgba"? Linking to the part of CSSOM that you did?

**Comment by shs96c** [comment]
About to assign to a bunch of people for their input on this.

**Comment by jgraham** [comment]
I think we should just use the CSS algorithm directly. If specific clients want to provide a uniform representation that's not too hard to do (and might involve some langauge-specific representation).

**Comment by andreastt** [comment]
As I said in the issue above, I’m quite sure we decided to just return what the browser returns, which happens to be [‘serializing a CSS component value’](https://drafts.csswg.org/cssom/#serialize-a-css-component-value) instead of coercing it to an rgba value.

**Comment by shs96c** [comment]
Fair enough. Closing this issue.

**Comment by vmassol** [comment]
Related to this, I've opened https://github.com/w3c/webdriver/issues/1447

Thanks
