### ISSUE TITLE
Wrong math in the element center calculation

### ISSUE THREAD

**Issue by Dzenly** [w3c/webdriver#425]
In chapter [9. Elements
    ](https://www.w3.org/TR/webdriver/#h-elements), section [9.1 Element Interactability
      ](https://www.w3.org/TR/webdriver/#h-element-interactability)::

> An element’s in-view centre point is the centre point of the area of the first DOM client rectangle that is inside the viewport. It can be calculated this way:
> 
> Let rectangle be the first element of the DOMRect sequence returned by calling getClientRects on element.
> 
> Let visible width be the rectangle’s (max(x coordinate, x coordinate + width dimension)).
> 
> Let visible height be the rectangle’s (max(y coordinate, y coordinate + height dimension)).
> 
> Let vertical centre offset be (visible width / 2.0).
> Let horizontal centre offset be (visible height / 2.0).
> Let centre point be a pair of the rectangle’s (x coordinate + horizontal centre offset) and (y coordinate + vertical centre offset).
> Return centre point.

Let's omit typos vertical<-> horizontal.

let x = 1000, let width = 200.
Visible width = max(1000, 1000 + 200) = 1200.
Horizontal centre offset = 1200 / 2 = 600.
Horizontal centre point = 1000 + 600 = 1600.
Which is out of the element rectangle boundaries.
Such a math seems to be wrong.

I think the x center should be calculated as:

0.5 \* ( max(0, min(x, x + width)) + min(window.innerWidth, max(x, x + width)) )

**Comment by andreastt** [comment]
The vertical ~ horizontal issue appears to get addressed in https://github.com/w3c/webdriver/pull/426.

**Comment by andreastt** [comment]
@Dzenly Sorry to not get back to you sooner on this. I ran your maths against real-world tests and it seems correct.

Do you feel this is a reasonable interpretation of it?

```js
/**
 * Calculate the in-view centre point of the area of the given DOM client
 * rectangle that is inside the viewport.
 *
 * @param {DOMRect} rect
 *     Element off a DOMRect sequence produced by calling |getClientRects|
 *     on a |DOMElement|.
 * @param {Window} win
 *     Current browsing context.
 *
 * @param {Map.<string, number>}
 *     X and Y coordinates that denotes the in-view centre point of |rect|.
 */
element.getInViewCentrePoint = function(rect, win) {
  let x = {
    top: Math.max(0, Math.min(rect.x, rect.x + rect.width)),
    bottom: Math.min(win.innerWidth, Math.max(rect.x, rect.x + rect.width)),
  };
  let y = {
    top: Math.max(0, Math.min(rect.y, rect.y + rect.height)),
    bottom: Math.min(win.innerHeight, Math.max(rect.y, rect.y + rect.height)),
  };

  return {
    x: 0.5 * (x.top + x.bottom),
    y: 0.5 * (y.top + y.bottom),
  };
};
```

If you agree, either you or I can write that as prose and open a PR against the spec.

**Comment by Dzenly** [comment]
Yes. This is a reasonable interpretation. Though I would remove the 3rd parameter description, add the `@return` description instead, and rename top/bottom to left/right for X part calculation).

Feel free to open a PR, I not sure I have enough time for some iterations concerned with PR approving this month.

**Comment by andreastt** [comment]
@Dzenly Submitted https://github.com/w3c/webdriver/pull/442. Did I get your name correct for the acknowledgement?

**Comment by Dzenly** [comment]
@andreastt,
Oh, actually I am Aleksey Chemakin :) (updated my profile just now).
"Dzenly" is just a nick.

**Comment by andreastt** [comment]
Thanks, fixed!
