### ISSUE TITLE
Command Status: HTTP method STATUS

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#429]
In chapter [6. Sessions](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-status#h-sessions), section [6.3 Status](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-status#h-status)::
> 6.3 Status
> HTTP Method 	Path Template
> STATUS 	/status

Does the command `status` use the HTTP method `STATUS`? In  section [4.5 List of Endpoints](https://w3c.github.io/webdriver/webdriver-spec.html#list-of-endpoints#h-list-of-endpoints) it is defined as `GET`

In [Fetch](https://fetch.spec.whatwg.org), section [3.1.1 Methods](https://fetch.spec.whatwg.org/#methods) it notes that `There are no restrictions on methods.` So an HTTP method `STATUS` would be "perfectly acceptable". However, in this case it does feel like a typo?

**Comment by AutomatedTester** [comment]
PR merged
