### ISSUE TITLE
Clarify whether Element Retrieval should always respect the implicit wait timeout

### ISSUE THREAD

**Issue by qmfrederik** [w3c/webdriver#438]
When reading the WebDriver standard, it is not clear to us whether [11.2 Find Element](https://www.w3.org/TR/webdriver/#find-element) and [11.3 Find Elements](https://www.w3.org/TR/webdriver/#find-elements) should both respect the [session implicit wait timeout](https://www.w3.org/TR/webdriver/#dfn-session-implicit-wait-timeout).

Both Find Element and Find Elements reference the [Find](https://www.w3.org/TR/webdriver/#dfn-find) method, which merely references the element location strategy but does not reference the timeout.

We would _naively_ expect that Find Element respects the timeout and Find Elements does not, but this is not made explicit in the standard.

Would it be possible to make it explicit in the [Find](https://www.w3.org/TR/webdriver/#dfn-find) section that the implicit timeout should be respected, and to clarify whether this is the case for both Find Element and Find Elements or Find Element only?

Thanks!

**Comment by andreastt** [comment]
Note that there is an [ongoing discussion](https://lists.w3.org/Archives/Public/public-browser-tools-testing/2016OctDec/thread.html) about whether implicit waits should also apply to commands that do element interaction.

**Comment by qmfrederik** [comment]
@andreastt Thanks! Followed the discussion & and submitted feedback to the poll :)

**Comment by shs96c** [comment]
The result of the discussion were that implicit waits should be in the spec, and that they should be used for waiting for an element to be interactable. They should not be used for "find" and I'll update the spec accordingly.

**Comment by shs96c** [comment]
I've opened PR #488 to address this.

**Comment by InstyleVII** [comment]
I should note the spec does define that element retrieval should respect implicit wait already here:
https://w3c.github.io/webdriver/webdriver-spec.html#dfn-session-implicit-wait-timeout

> A session has an associated session implicit wait timeout that specifies a time to wait for the implicit element location strategy when retreiving elements. Unless stated otherwise it is zero milliseconds.

**Comment by qmfrederik** [comment]
@InstyleVII The problem with that paragraph is that the spec does not define what the "implicit element location strategy" is, nor does it give any details about how the implicit wait should work, especially in the context of wait - by polling? At what frequency?

@shs96c would it make sense to remove the paragraph @InstyleVII refers to from the spec as implicit wait no longer applies to "find"?

**Comment by InstyleVII** [comment]
@qmfrederik Interesting, I assumed the polling would be as fast as possible. So the code I would imagine would literally be on page load when running find element run in a loop for the time specified by the dev, so the frequency would be as fast as a while loop can process? It's somewhat of a stopgap for users writing their own loop using document.findElement and running it until it fails, just handled by the browser to save the dev some lines of code and have the commands be more implicit (hence the name).

**Comment by andreastt** [comment]
#489 seems wrong, since it involves the _page load_ strategy; not the _implicit search_ strategy.

What’s missing is the _definition_ of what to do when an implicit timeout duration is set. I don’t think we have to be specific what it means, just that the driver should not return before the element is either found or the timeout has elapsed.

**Comment by shs96c** [comment]
There was a thinko above: obviously implicit waits apply to finding elements, but they don't need to be interactable before the result is returned.
