### ISSUE TITLE
Missing reference to endpoint node

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#457]
In chapter [6. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#capabilities#h-capabilities), section [6.3 Processing Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#capabilities#h-processing-capabilities):
> When merging capabilities with JSON Object arguments primary and secondary, an endpoint node must take the following steps:

**Comment by shs96c** [comment]
All references to "endpoint node" appear to be correctly linked. Closing this issue.
