### ISSUE TITLE
Type check of pageLoadStrategy capability

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#460]
In chapter [6. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#capabilities#h-capabilities), section [6.3 Processing Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#capabilities#h-processing-capabilities)::
> If capability value is not a string, return error with error code invalid argument.
> 
> Otherwise, set the "pageLoadStrategy" entry in matched capabilities to capability value. 

We need to look up the `pageLoadStrategy` in a table of page load strategies and fail if it is not a recognised value.

**Comment by AutomatedTester** [comment]
This was fixed with the change from @jleyba
