### ISSUE TITLE
WebDriver spec seems to indicate `/element` can return multiple elements

### ISSUE THREAD

**Issue by qmfrederik** [w3c/webdriver#463]
Upon reading the spec:

[11.2 Find Element](https://www.w3.org/TR/webdriver/#find-element) states that `/element` returns the result of a find operation with `all` equal to `false`
[11 Element Retrieval](https://www.w3.org/TR/webdriver/#element-retrieval) states that `elements` is the result of the element location strategy (passing `all`), and that for each element in elements, the element is added to the result set.

This seems to indicate that if there is a element location strategy which returns multiple elements even when `all` is `false`, `/element` will return multiple elements.

Furthermore, element location strategies like [11.1.2 Link Text](https://www.w3.org/TR/webdriver/#link-text), [11.1.3 Partial Link Text](https://www.w3.org/TR/webdriver/#partial-link-text) and [11.1.4 Xpath](https://www.w3.org/TR/webdriver/#xpath) all ignore the `all` parameter, potentially returning multiple elements.

This does not seem to match the intent of the original Selenium protocol.

Suggestion: update [11.2 Find Element](https://www.w3.org/TR/webdriver/#find-element) so that it specifies what should be done if `all` is `false` and the element location strategy returns multiple elements. Should this result in an error, or should the first element be returned?

**Comment by andreastt** [comment]
Yes, you are right. This is incorrect. There should be no argument, and these should be separate endpoints. Thanks for noticing!

**Comment by andreastt** [comment]
Sorry, did not mean to close it.

**Comment by shs96c** [comment]
I think that a8e43b0f9fc306712ba2aeb4a20e7fdbedd870ba resolves this issue. Closing.
