### ISSUE TITLE
"JSON Object structure" used in cookie-related commands

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#467]
In chapter [15. Cookies](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-serialised-cookie#h-cookies):
> serialised cookie structure 

as well as

In chapter [15. Cookies](https://w3c.github.io/webdriver/webdriver-spec.html#cookies#h-cookies):
> JSON Object structure

Is the `JSON Object structure` different from a `JSON Object`, as put more simply in many other parts of the spec? If it doesn't have a special meaning, does it make the text simpler to read if it's omitted?

PS I know that small wording changes like that are a matter of taste as well, so I understand if this isn't considered an issue at all.

**Comment by vkatsikaros** [comment]
Changed the wording in branch https://github.com/vkatsikaros/webdriver/tree/467

**Comment by andreastt** [comment]
That should definitely just say `<a>JSON Object</a>`.
