### ISSUE TITLE
Missing JSON underlying specification

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#471]
Chapter [1. Conformance](https://w3c.github.io/webdriver/webdriver-spec.html#conformance#h-conformance), section [1.1 Dependencies](https://w3c.github.io/webdriver/webdriver-spec.html#conformance#h-dependencies)

JSON is used throughout the webdriver spec but I don't think I can see it as an underlying specification it relies on. TBH I am not sure on the status of [ECMA-404: The JSON Data Interchange Format](https://www.ecma-international.org/publications/standards/Ecma-404.htm) or [The JavaScript Object Notation (JSON) Data Interchange Format](https://tools.ietf.org/html/rfc7159) and which should be the underlying one, just noticed it was missing.

**Comment by AutomatedTester** [comment]
I don't think that this is necessary as we have the necessary pieces for JSON from ecmascript. closing for now
