### ISSUE TITLE
Missing definition for keyboard-interactable element

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#482]
In chapter [10. Elements](file:///home/vag/projects/webdriver/webdriver-spec.html#dfn-pointer-interactable-element#h-elements), section [10.1 Element Interactability](file:///home/vag/projects/webdriver/webdriver-spec.html#dfn-pointer-interactable-element#h-element-interactability)::
> keyboard-interactable

the section defines pointer-interactable element but not a keyboard one

**Comment by shs96c** [comment]
Fixed.

**Comment by andreastt** [comment]
New definition is good.
