### ISSUE TITLE
Global key state

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#500]
In chapter [16. Actions](https://w3c.github.io/webdriver/webdriver-spec.html#h-actions), section [16.4 Dispatching Actions](https://w3c.github.io/webdriver/webdriver-spec.html#h-dispatching-actions)::
> get a global key state

Does the "global" in "global key state" imply that there is another kind of "key state" (like "local"). If there isn't another kind of "key state", is it needed?

PS I search a bit to see if there is a similar definition elsewhere (example the selenuim docs) but I didn't [find something relevant](https://www.google.com/search?as_q=&as_epq=key+state&as_sitesearch=seleniumhq.org),

Edit: `s/if there is/if there isn't/`

**Comment by vkatsikaros** [comment]
I also noticed that instead of the concept of "key state" there are the concepts of "key input state" and "null input state", so it could be that something additional is needed here?

**Comment by andreastt** [comment]
@mjzffr @jgraham

**Comment by jgraham** [comment]
AFAICT this part of the spec is just broken; the pointer section should state which keys are considered depressed as part of the action.

**Comment by shs96c** [comment]
I think it's clear that this is to differentiate itself from the individual "key input state" objects in the "input state". I also note that the definition for "Global Key State" correctly refers to "key input state", so I'm guessing the other concern raised originally is handled.

@jgraham's comment about this part of the spec being broken is a separate matter. Raised #595

**Comment by mjzffr** [comment]
@shs96c @jgraham I ended implementing something along the lines of "global key state" to determine which modifier keys are pressed during a pointer action: See https://hg.mozilla.org/integration/autoland/rev/9c79509cd756 and 

Marionette needs to do perform these steps to dispatch the MouseEvent correctly, but I'm not sure whether that needs to be called out in the spec as well (e.g. "when dispatching pointer actions, determine which modifier keys are pressed from the input state of all active input sources.") It's perhaps more of an implementation detail. What do you think?

**Comment by jgraham** [comment]
You're quite right, this is a bug in the spec.

**Comment by mjzffr** [comment]
I'll open a PR to fix it when I get a chance.

**Comment by jgraham** [comment]
Thanks!

**Comment by jgraham** [comment]
Although it seems like that's #595  now.
