### ISSUE TITLE
Getting a global key pressed state

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#501]
In chapter [16. Actions](https://w3c.github.io/webdriver/webdriver-spec.html#h-actions), section [16.4 Dispatching Actions](https://w3c.github.io/webdriver/webdriver-spec.html#h-dispatching-actions)::
> getting a global key pressed state with argument "Alt".

This `<a>` is linking to an undefined concept. I understand this refers to `<dfn data-lt="key-state"> get a global key state`, which I could easily fix.

But the text confuses me a bit: is the "pressed state" an additional concept (can't find its definition)? Does it somehow refer to the "pressed property"?

**Comment by AutomatedTester** [comment]
@jgraham can you help with some clarification here.

**Comment by shs96c** [comment]
Is this not something to do with the combined values of all "key" input states for the current session?

**Comment by shs96c** [comment]
I also suspect that this text isn't necessary at all. #608
