### ISSUE TITLE
"processing keys" algorithm

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#506]
In chapter [13. Element Interaction](https://w3c.github.io/webdriver/webdriver-spec.html#h-element-interaction), section [13.3 Element Send Keys](https://w3c.github.io/webdriver/webdriver-spec.html#h-element-send-keys)::
> the result of processing keys with argument key

respec lib warns that the definition of "processing keys" is missing. I can't find something related in the text, so could it be a missing concept?

**Comment by andreastt** [comment]
I think this concept can be dropped entirely now that we can rely on the primitives in the actions chapter to type keys?

**Comment by shs96c** [comment]
I think that there may be a missing step where we convert a grapheme cluster to a series of events. The original selenium APIs also handled things like converting `\n` into the `Keys.RETURN`, and converting characters typed on the US keyboard using the shift key into more than one event.

Probably what we need to do is take the values from the user, and run the "processing keys" to generate the sequence of `keyDown`/`keyUp` actions in both `Element Send Keys`. We also need to add a check in `keyDown` and `keyUp` that the character is typeable (and provide a mechanism to do the equivalent of spamming the character into the input events if necessary)

**Comment by andreastt** [comment]
> I think that there may be a missing step where we convert a grapheme cluster to a series of events. The original selenium APIs also handled things like converting \n into the Keys.RETURN, and converting characters typed on the US keyboard using the shift key into more than one event.

Oh I see. Yes, that would be special to Element Send Keys. Thanks for reminding me.
