### ISSUE TITLE
Add missing top-level browsing context check to some commands

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver#508]
A couple of sections for commands are missing the the pre-condition for the top-level browsing context to be open:

> If the current top-level browsing context is no longer open, return error with error code no such window. 

Here an example for "Find Element" which will fail without this check:

In chapter [11. Element Retrieval](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-find-element#h-element-retrieval), section [11.2 Find Element](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-find-element#h-find-element)::
> Let start node be the current browsing context’s document element.

**Comment by whimboo** [comment]
I will work on this issue and provide a PR within the next days.

**Comment by andreastt** [comment]
Fixed by https://github.com/w3c/webdriver/pull/574.
