### ISSUE TITLE
Dispatch algorithm arguments

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#513]
In chapter [16. Actions](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-dispatch-a-pointerup-action#h-actions), section [16.4 Dispatching Actions](https://w3c.github.io/webdriver/webdriver-spec.html#h-dispatching-actions) algorithms of dispatch actions are defined.

`dispatch a keyDown action`, `dispatch a keyUp action`: mention only the arguments used in the algorithm:
* action object 
* input state

`dispatch a pause action`, `dispatch a pointerDown action`, `dispatch a pointerUp action`, `dispatch a pointerMove action`, `dispatch a pointerCancel action`: mention all of the possible arguments (regardless whether they are used or not in the algorithm):
* source id
* action object
* input state
* tick duration

Should the definition have a unified way of listing the arguments? 

PS If there is a decision, I could provide the patch.

Edit: fix markdown links to point to published webdriver url

**Comment by shs96c** [comment]
We should pass in the `source id` so that we can correctly create the events for the `input cancel list`. `duration` isn't currently required.

**Comment by andreastt** [comment]
Yes, that’s my interpretation too. But, yes, it would be good to have them all accept the same arguments.
