### ISSUE TITLE
Misleading note on implementing page load strategies

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#522]
In chapter [8. Navigation](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-normal#h-navigation):
> This can typically be implemented by registering an event handler for the DOMContentLoaded event, and comparing the document readiness state against readiness target whenever it fires. When it reaches its designated readiness target, return from the overall step of this algorithm. 

`DOMContentLoaded` fires once, and the readiness state at that time should always be `interactive`. The readiness state doesn't change to `interactive` until just before `load` fires. This note seems rather misleading.

**Comment by shs96c** [comment]
Is your suggestion to remove the note or reword it? Assigning to @jgraham for clarification.

**Comment by jgraham** [comment]
I don't care. I'm happy for it to be removed; I don't think this is an especially complex part of the spec to implement correctly.
