### ISSUE TITLE
Element Clear does not take into account elements which can't be cleared, e.g. Radiobuttons

### ISSUE THREAD

**Issue by AutomatedTester** [w3c/webdriver#523]
In chapter [13. Element Interaction](https://w3c.github.io/webdriver/webdriver-spec.html#element-clear#h-element-interaction), section [13.2 Element Clear](https://w3c.github.io/webdriver/webdriver-spec.html#element-clear#h-element-clear)::
> Otherwise
> 
>     Set the value to an empty string.

**Comment by shs96c** [comment]
The Selenium "[bot.action.clear](https://github.com/SeleniumHQ/selenium/blob/selenium-3.0.1/javascript/atoms/action.js#L83)" atom (which is used by the Selenium FirefoxDriver, which is the most widely used driver at present) makes it pretty clear that the behaviour users expect is that only editable elements may be "Element Cleared"

**Comment by shs96c** [comment]
This is addressed by #534

**Comment by shs96c** [comment]
Closing since #534 fixed this.
