### ISSUE TITLE
Readiness state for each node type

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#527]
In chapter [4. Nodes](https://w3c.github.io/webdriver/webdriver-spec.html#h-nodes) 4 types of nodes are defined. When it comes to `readiness state` the definition says `for each node type`

> A remote end’s  is for each node type said to be

but mentions only 2 of the four.

Should the wording be different, or a table should contain all 4 node types and a description of the `readiness state` for each of them?

**Comment by shs96c** [comment]
Now fixed.
