### ISSUE TITLE
Cookie deletion, else step missing?

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#528]
In chapter [15. Cookies](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-json-clone#h-cookies):
> For each cookie among all associated cookies of the current browsing context’s active document, if: 

Cookie deletion (<dfn> "delete cookies"), doesn't mention what happens if neither `name is undefined` or `name is equal to cookie name ` are met. Is it simply missing an "Otherwise: do nothing", which implies that command `Delete Cookie` with argument `name` always returns success?

PS If so I can provide a patch for this.

**Comment by shs96c** [comment]
Existing implementations silently pass if the cookie doesn't exis. It's simply missing an "otherwise: do nothing"
