### ISSUE TITLE
Wording for text in CSS class `.switch`

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#529]
Some parts of the document are defined with `document.querySelectorAll('.switch')`. The wording of these parts is not uniform.

> A remote end’s readiness state is for each node type said to be: 

Filed https://github.com/w3c/webdriver/issues/527

> For each cookie among all associated cookies of the current browsing context’s active document, if: 

Filed https://github.com/w3c/webdriver/issues/528

if - else if / switch
-----------------------

The following define the equivalent of `if - else if` or `switch` 

### Non explicit wording

Even if one can understand the meaning of the `switch`, the wording is not explicit (unlike the sentences mentioned in "Explicit wording")

> Switch on capability name: 

> Match case-insensitively on the element's tag name: 

> Match on element’s type attribute:

> Match on the user prompt handler: 

> Match on current user prompt: 

Could they be reworded like the sentences below? A patch will follow.

### Explicit wording

These explicitly mention it a `switch`, but the wording is not uniform:

> When asked to run the post-navigation checks, run the substeps of the first matching statement: 

> Run the substeps of the first matching condition: 

> Let selected be the value corresponding to the first matching statement: 

> When required to run the internal JSON clone algorithm with arguments value and seen, a remote end must return the value of the first matching statement, matching on value: 

> Let result be the result of the first appropriate step below: 

> Let result be the value of the first matching statement, switching on value:

The 2 above could be reworded for uniformity. A patch will follow.

**Comment by shs96c** [comment]
@vkatsikaros Can we close this now?

**Comment by vkatsikaros** [comment]
@shs96c currently these are "open" 
* #527
* #528 
* and a patch I can provide for the "Non explicit wording" mentioned above.

In retrospect, it seems I didn't make clear all the sub-issues related to this.

**Comment by shs96c** [comment]
The dependent bugs are now closed. Closing this container issue too.
