### ISSUE TITLE
Both window/rect methods (GET/POST) don't work

### ISSUE THREAD

**Issue by igrishaev** [w3c/webdriver#533]
I'm implementing my own web driver HTTP api and I found that none of drives support methods for setting/getting window size. I tried Chomedriver, Phantomjs and Geckodriver, they all return 400 or 404 responses:

```
"{\"error\":\"unknown command\",\"message\":\"GET /session/bd51f7eb-d58f-f94b-8a2e-b2fe49b79327/window/rect did not match a known command\"}"
```

That seems I'm doing something wrong. Any ideas? Thanks.

**Comment by vkatsikaros** [comment]
@igrishaev `w3c/webdriver` is the project for the webdriver specification (the specification's text), not webdriver specification implementations by browsers. Also, the spec is currently under development so there might be parts of it not yet implemented by the browser implementations. From the history, I see that these are very very new additions to the spec, so it is highly possible that this endpoint isn't implemented in the browser drivers.

I suggest that you first check each browser's webdriver support status at their [respective](https://github.com/mozilla/geckodriver/) [projects](https://sites.google.com/a/chromium.org/chromedriver/downloads).

**Comment by igrishaev** [comment]
@vkatsikaros thank you for your reply. Sure I understand that project is just a spec but not a code. Just wanted to know the reason. Currently I'm reading the source code of that projects.

**Comment by vkatsikaros** [comment]
@igrishaev it looks like [this commit](https://github.com/w3c/webdriver/commit/36c45c2405de65c1da6c5e3fa4f766ad576046d9) modified the behavior of endpoints related to what you are using. Without having tested it, may I suggest you look whether the drivers had added, in the past, support for the old endpoints `/window/size` and `/window/position`?

**Comment by igrishaev** [comment]
@vkatsikaros you are right, those methods work! I'll examine the git history to find out more. Thanks you so much!

**Comment by andreastt** [comment]
If geckodriver doesn’t support this, that is a bug in geckodriver since it is the only specification conforming implementaiton. Can you please file one?

**Comment by igrishaev** [comment]
@andreastt you are right, I spent yesterday examining [geckodriver Rust code][url], there aren't such methods. Will submit a bug then.

[url]: https://github.com/mozilla/webdriver-rust/blob/7ec65451c99b638655c72e7b9718a374ff60de87/src/httpapi.rs#L66
