### ISSUE TITLE
Missing definition of 'element command'

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#550]
In chapter [5. Protocol](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-delete-cookies#h-protocol), section [5.6 Handling Errors](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-delete-cookies#h-handling-errors)::
> element command

The term `element command` is used 3 times in the text, without having a definition.

**Comment by shs96c** [comment]
It's safe to reword each of these as just "command"

**Comment by vkatsikaros** [comment]
Thanks, will do
