### ISSUE TITLE
URL path element

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#551]
In chapter [5. Protocol](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-url#h-protocol), section [5.7 Protocol Extensions](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-url#h-protocol-extensions)::
> URL path element

I am not sure what "URL path element" refers to? From the context, it doesn't look like an HTML path element.

**Comment by shs96c** [comment]
The definition of `URL` is linked to, and it quickly leads you to this [part](https://url.spec.whatwg.org/#concept-url-path) of the URL standard. It seems clear to me that this is what the text is referring to.

Closing this, as I think the spec is already clear enough, but feel free to reopen if you disagree.

**Comment by vkatsikaros** [comment]
@shs96c I was wondering if the word "element" could be avoided since:
* it's used throughout the spec with a well defined (and different) meaning
* "element" isn't used in any of the [URL](https://url.spec.whatwg.org/) definitions

So, rephrasing the question, is the word "element" used here with the meaning "part", "segment", "substring", ie not a whole [URL path](https://url.spec.whatwg.org/#concept-url-path)? Or is it that  the `extension command prefix` is a valid "URL path" on its own, so the "element" could be removed completely? 

An additional  question (and irrelevant to the above): should the webdriver spec be more precise on the types of strings it can accept as prefixes, as the range U+0000 to U+007F, includes U+002E FULL STOP that can be used to form relative paths?

**Comment by andreastt** [comment]
Sure. Go ahead and change this to “URL path part” or “URL path segment” when referring to elements of the array that makes up the URL path.

> [S]hould the webdriver spec be more precise on the types of strings it can accept as prefixes, as the range U+0000 to U+007F, includes U+002E FULL STOP that can be used to form relative paths?

I don’t particularly care about full stop, but we should definitely exclude the encode sets that can produce invalid URLs. Filed https://github.com/w3c/webdriver/issues/566.
