### ISSUE TITLE
`Element Send Keys`: allow resetting keyboard state in command

### ISSUE THREAD

**Issue by shs96c** [w3c/webdriver#553]
The Selenium WebDriver APIs offers Keys.NULL (`'\uE000'`) which releases all currently held modifier keys. It's therefore possible to use a command like this:

  element.sendKeys(Keys.SHIFT, "h", Keys.NULL, "ello");

to type "Hello". Without this special character, two `sendKeys` calls would need to be made.

**Comment by twalpole** [comment]
Due to the 'set selection range' portion of the sendKeys spec it's not always possible to split into multiple sendKeys calls. It would be great if the NULL behavior or equivalent made it into the spec.

**Comment by lmtierney** [comment]
Do these two lines not indicate that the carat would be put at the end of the current text in the element?

```
Let current text length be the Node Length.

Set the text insertion caret using set selection range with using current text length as the 2 parameters passed in.
```

**Comment by twalpole** [comment]
@lmtierney Yes - so if one of the segments separated by nulls has moved that position (ctrl-left arrow for instance) - it will be reset to the end before the next set of keys is sent.
