### ISSUE TITLE
Unspecified input event used for key interaction

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#561]
In chapter [13. Element Interaction](https://w3c.github.io/webdriver/webdriver-spec.html#h-element-interaction), section [13.2 Element Clear](https://w3c.github.io/webdriver/webdriver-spec.html#h-element-clear):
> Fire an input event.

But also under ‘clear an editable element’ and Element Send Keys.

The input events that occur when e.g. using Element Send Keys normally are:

1. Before sending keys:
   1. focus
2. Sending keys:
   1. keydown
   2. keypress
   3. textInput
   4. input
   5. keyup
3. Upon interaction with another element:
   1. change
   2. blur

For `<input type=file>`, none of the steps under 2 takes place.

**Comment by shs96c** [comment]
I don't think the "key" events make sense for a file input since I can't think of a browser that doesn't allow selecting files from a file selection dialog. My assumption is that's how we want sending keys to a file input to (pretend to) work too.

**Comment by andreastt** [comment]
> For `<input type=file>`, none of the steps under 2 takes place.
