### ISSUE TITLE
Missing definition for "browser chrome"

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#565]
"browser chrome" is used in a few places in the spec, but it's not defined.

Kind of related is https://github.com/w3c/webdriver/issues/564

**Comment by andreastt** [comment]
It’s not entirely clear to me we that we _can_ come up with a better definition of that.

**Comment by vkatsikaros** [comment]
Thanks, will add a note.

**Comment by ltetzlaff** [comment]
Just in case somebody stumbles upon this seeking a definition https://www.w3.org/TR/wsc-ui/#def-chrome also defines the term.

**Comment by andreastt** [comment]
@ltetzlaff I like that definition, perhaps we can repurpose it.

**Comment by andreastt** [comment]
Submitted https://github.com/w3c/webdriver/pull/845.
