### ISSUE TITLE
The pointer section should state which keys are considered depressed as part of the action

### ISSUE THREAD

**Issue by shs96c** [w3c/webdriver#595]
From a comment by @jgraham in #500. 

Assigning to him to either flesh-out or close.

**Comment by shs96c** [comment]
No more references to global key state. Closing.

**Comment by jgraham** [comment]
I'm very confused now. How can we avoid referencing the global key state somehow whilst still making this work?

**Comment by mjzffr** [comment]
Yeah, that's what I was confused about in https://github.com/w3c/webdriver/issues/500#issuecomment-306882155 and I ultimately decided I have to compute a global key state from the device input state to make things work.

**Comment by andreastt** [comment]
And we ended up patching Marionette to share the key modifier state: https://hg.mozilla.org/mozilla-central/rev/9c79509cd756

**Comment by shs96c** [comment]
`MouseEvent` has a reference to the modifier keys: https://www.w3.org/TR/DOM-Level-3-Events/#interface-mouseevent
