### ISSUE TITLE
Need a definition of non-transparent. 

### ISSUE THREAD

**Issue by shs96c** [w3c/webdriver#617]
In chapter [10. Elements](https://w3c.github.io/webdriver/webdriver-spec.html#h-elements), section [10.1 Element Interactability](https://w3c.github.io/webdriver/webdriver-spec.html#h-element-interactability):
> non-transparent

**Comment by andreastt** [comment]
The definition is under [get the first pointer-interactable element](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-get-the-first-pointer-interactable-element), which says the CSS property "opacity" must have the computed value of "1".

But we should make this clearer and define non-transparent, indeed.
