### ISSUE TITLE
Waiting after scroll into view element for clicking

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#624]
In chapter [14. Element Interaction](https://w3c.github.io/webdriver/webdriver-spec.html#interface#h-element-interaction), section [14.1 Element Click](https://w3c.github.io/webdriver/webdriver-spec.html#interface#h-element-click):
> Wait in an implementation-specific way up to the session implicit wait timeout for the container to become pointer-interactable. 

It’s not clear to me as an implementor what it means to wait for the element to become pointer-interactable after it has been scrolled into view before we click it.

Is the intention here to make the command synchronous by waiting for the scroll to complete?

I understand the desire to make Element Click a do-what-I-mean high-level command that is nice to use for end-users, but there is a danger that if the element is still obscured (i.e. not pointer-interactable) after scrolling, which happens in very trivial cases, that we sit there idle doing nothing while the browser does nothing.

So I’m raising the question about this: Can we be more clever?

**Comment by shs96c** [comment]
The intention is to make the command block until after the scrolling is complete. The danger of sitting idle is one of the reasons that the selenium project advocates people avoid relying on the implicit wait timeout. 

One possible solution would be to iterate over each of the element client rects of the element and test if the centre point of each is obscured, using the first unobscured rect for the calculations of where to click. If there are no unibscured rects then fail.

**Comment by shs96c** [comment]
I think we now do something more clever. The scrolling is broken up into "scrolling the container in view". The definition of "[in view](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-in-view)" precludes the waiting you've raised as an issue (if I understand it correctly)

Closing this issue, as I think it's resolved, but please reopen if this is not the case.
