### ISSUE TITLE
Indistinguishable from a remote end

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#627]
In chapter [5. Nodes](https://w3c.github.io/webdriver/webdriver-spec.html#terminology#h-nodes):

>  Intermediary nodes must be black-box indistinguishable from a remote end from the point of view of local end

>  An endpoint node must be, like intermediary nodes, indistinguishable from a remote end. 

Does the wording in the different way the two node types are `indistinguishable from a remote end` mean they are somehow different?

**Comment by andreastt** [comment]
I think probably the last quote is a bit confusing.

**Comment by shs96c** [comment]
The spec should make clear that the following is true:

```
local-end -> intermediary -> intermediary -> end-point
             \_______________________________________/
                      all kinds of remote-ends
```

There need not be any intermediary nodes, and so to a local end, both intermediary nodes and end point nodes appear identical (in the same way that a browser can't necessarily tell if it's talking to a proxy or the actual HTTP server)

**Comment by shs96c** [comment]
I think this is okay now. Closing, but please reopen if you disagree.
