### ISSUE TITLE
Get Alert Text: contradictory language

### ISSUE THREAD

**Issue by jugglinmike** [w3c/webdriver#631]
The "Get Alert Text" command's description states that in the absence of any current user prompt, the return value is "null". The algorithm steps dictate that a "no such alert" error be returned instead.

I'm happy to write a patch to unify these two parts of the documentation, but I'll need a spec author to determine which is the intended behavior.

In chapter [17. User Prompts](https://w3c.github.io/webdriver/webdriver-spec.html#get-alert-text#h-user-prompts), section [17.4 Get Alert Text](https://w3c.github.io/webdriver/webdriver-spec.html#get-alert-text#h-get-alert-text):
> The Get Alert Text command returns the message of the current user prompt. If there is no current user prompt, it returns with null.
> 
> The remote end steps are:
> 
>     If the current top-level browsing context is no longer open, return error with error code no such window.
> 
>     If there is no current user prompt, return error with error code no such alert.
> 
>     Let message be the text message associated with the current user prompt, or otherwise be null.
> 
>     Return success with data message.

**Comment by shs96c** [comment]
Both conditions are acceptable. If there's no modal dialog, then "no such alert" is returned, but it's entirely possible that the alert doesn't have any text, though perhaps the empty string would be better.

**Comment by jugglinmike** [comment]
Hi Simon! The contradiction I was referencing is between the command's non-normative description and step 2 of the algorithm. The former reads:

> If there is no current user prompt, it returns with null.

While the latter reads:

> 2. If there is no current user prompt, return error with error code no such
>    alert.

(I'm elaborating here because your comment about a dialog without text seems to be in reference to step 3, which isn't related to the contradictory language.)

I suspect step 2 is the intended behavior given that the "no such alert" error is clearly defined for this condition. Would you agree?

**Comment by shs96c** [comment]
Step 2 is the intended behaviour.

**Comment by jugglinmike** [comment]
Got it
