### ISSUE TITLE
Naming and precedence of unexpectedAlertBehaviour capability

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#632]
In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#h-capabilities):
> unexpectedAlertBehaviour

@shs96c Is `unexpectedAlertBehaviour` a concept currently in use by existing drivers? Or can we change its name and behaviour?

If we have free choice, I would like it to be named `promptHandler`, `promptBehavior`, or `unexpectedPromptHandler`.

It would also be nice if it took a string as input: "accept" (accept state), "dismiss" (dismiss state), or null/undefined (default boolean attribute missing state).

**Comment by AutomatedTester** [comment]
> @shs96c Is unexpectedAlertBehaviour a concept currently in use by existing drivers? Or can we change its name and behaviour?

Yes, as was mentioned in the PR that added it.

> It would also be nice if it took a string as input: "accept" (accept state), "dismiss" (dismiss state), or null/undefined (default boolean attribute missing state).

This is already there.

**Comment by andreastt** [comment]
> Yes, as was mentioned in the PR that added it.

Which drivers? In the danger of sounding self-righteous, I find it a bit surprising that it’s in use as defined here, since the user prompt handler as defined in the specification is of my own invention and I haven’t implemented it anywhere.

>> It would also be nice if it took a string as input: "accept" (accept state), "dismiss" (dismiss state), or null/undefined (default boolean attribute missing state).
>
> This is already there.

The specification only defines that `unexpectedAlertBehaviour` exists in the [table of standard capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-table-of-standard-capabilities),a nd not how it is deserialised from a JSON Object to the [user prompt handler](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-user-prompt-handler) state.

**Comment by shs96c** [comment]
The selenium [firefoxdriver](https://github.com/SeleniumHQ/selenium/blob/selenium-3.0.1/javascript/firefox-driver/js/modals.js) implements this, and there are references in the [IEDriver](https://github.com/SeleniumHQ/selenium/blob/selenium-3.0.1/cpp/iedriver/IECommandHandler.h#L35) that imply it's also working there.

We're perfectly at liberty to define a new capability. If we do so, we need to consider what we should do if an unexpected `window.prompt` appears (that is, is there some kind of default answer string we should supply).

A better name would be "unexpected modal behavior".

**Comment by AutomatedTester** [comment]
> Yes, as was mentioned in the PR that added it.

>> Which drivers? In the danger of sounding self-righteous, I find it a bit surprising that it’s in use as defined here, since the user prompt handler as defined in the specification is of my own invention and I haven’t implemented it anywhere.

It was added to FirefoxDriver in Q1 2012. Perhaps you saw it in the code and forgot about it.

**Comment by shs96c** [comment]
Closing again.
