### ISSUE TITLE
What to do if request cannot be decoded as an HTTP request

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#661]
In chapter [6. Protocol](https://w3c.github.io/webdriver/webdriver-spec.html#maximize-window#h-protocol), section [6.3 Processing Model](https://w3c.github.io/webdriver/webdriver-spec.html#maximize-window#h-processing-model):
> Should mention what happens if it can’t be decoded as HTTP. Note that Fetch isn’t quite right because it doesn’t specify how to construct a request from network data, or serialize a response. 

Maybe this is implicit, as we say earlier that the implementation must provide a good HTTP implementation.

**Comment by shs96c** [comment]
Surely any conforming HTTP server would send a 400 (malformed request) error? Or perhaps a 500 if that's how the server works. I think both would be valid, though 500 maps cleanly to an "unknown error" in most local-end implementations.

If we want to spell this out, perhaps changes "acts as an" to "is an"

> The remote end acts as an HTTP server reading requests from the client and writing responses, typically over a TCP socket
