### ISSUE TITLE
Are meta tag redirects handled?

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#662]
In chapter [9. Navigation](https://w3c.github.io/webdriver/webdriver-spec.html#maximize-window#h-navigation), section [9.1 Go](https://w3c.github.io/webdriver/webdriver-spec.html#maximize-window#h-go):
> Issue 3
> 
> Figure out if next paragraph is actually required:
> 
>     When a page contains a META tag with the "http-equiv" attribute set to "refresh", a response MUST be returned if the timeout is greater than 1 second and the other criteria for determining whether a page is loaded are met. When the refresh period is 1 second or less and the page loading strategy is "normal" or "conservative" implementations MUST wait for the refresh to complete before responding. 

I don’t think they are?

**Comment by shs96c** [comment]
That behaviour with the refresh meta tag is desirable, and was implemented in the selenium firefoxdriver (I'd need to read the code to figure out if the same is true for the iedriver, but ISTR it is)

**Comment by shs96c** [comment]
Reading the spec, this not covered yet.
