### ISSUE TITLE
Use terminology from RFC 6570 on URI templates

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#673]
From the discussion in https://github.com/w3c/webdriver/pull/667 it became clear that we are not reusing terminology from the [URI Templates standard](https://tools.ietf.org/html/rfc6570) when we talk about ‘parameters’ for command endpoints.

**Comment by shs96c** [comment]
I think that this is clear. The definition of `url parameters` in the `Processing Model` are:

> Otherwise, let command and url variables be request match’s data.

This makes it clear that the url parameters are those returned from `match a request`. This makes it clear that the variables being referred to are from the URI Template.

`parameters` in the processing model are derived from the POST data:

> If request’s method is POST:
>
>Let parse result be the result of parsing as JSON with request’s body as the argument.
>
>If parse result is an error or if it is a success but its associated data is not an Object, send an error with error code invalid argument and jump back to step 1 in this overall algorithm.
>
>Otherwise, let parameters be parse result’s data.
>
>Otherwise, let parameters be null.

I believe that all this is clear. Closing this issue, but please reopen if you disagree.
