### ISSUE TITLE
ftpProxy and "If a URL is passed through this property"

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#678]
In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#h-capabilities), section [7.1 Proxy](https://w3c.github.io/webdriver/webdriver-spec.html#h-proxy):
> ftpProxy

Is the description of this one missing a 

>  If a URL is passed through this property [...]

**Comment by shs96c** [comment]
Yes it is.

**Comment by vkatsikaros** [comment]
@shs96c happy to have this assigned to me.
