### ISSUE TITLE
POST request parameters

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#680]
In chapter [6. Protocol](https://w3c.github.io/webdriver/webdriver-spec.html#h-protocol), section [6.3 Processing Model](https://w3c.github.io/webdriver/webdriver-spec.html#h-processing-model):
> If request’s method is POST:
> 
> Let parse result be the result of parsing as JSON with request’s body as the argument.
> 
> If parse result is an error or if it is a success but its associated data is not an Object, send an error with error code invalid argument and jump back to step 1 in this overall algorithm.
> 
> Otherwise, let parameters be parse result’s data. 
> 
> Otherwise, let parameters be null.
> 
> ...
> 
> Let response result be the return value obtained by running the remote end steps for command with url variables as arguments. 

I see that `parameters` (JSON in the request’s body) is not used anywhere in the algorithm. Should it be one of the arguments passed to `running the remote end steps for command`?

Many of the commands that consume the parameters, do mention it as a `<var>` argument, but it's not defined somewhere in their respective algorithm. Example:

section [10.7 Resizing and Positioning Windows](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-set-window-rect#h-resizing-and-positioning-windows): 
> 4. If the properties width or height or x or y from the parameters are not integers, or less than 0 or greater than 264 – 1, return error with error code invalid argument.

**Comment by andreastt** [comment]
I think probably we need to have a clearer distinction between the matches from the URI template parsing, which is sometimes referred to as ‘parameters’, and the request body/data.

**Comment by vkatsikaros** [comment]
I can start working on a patch based on your comments, unless there is some ongoing work for this.

**Comment by andreastt** [comment]
@vkatsikaros I haven’t made any stabs at this. Please feel free to pick it up.

**Comment by shs96c** [comment]
Can I ask why we don't just say that for each command, variables in the URL template are to be treated as named variables in the algorithms for that command? That handles the case where we refer to them in the middle of the algorithm without a lot of additional boiler-plate text in the spec.

It's entirely possible I'm missing something here….

**Comment by andreastt** [comment]
I think it’s the intention of this bug to fix that. As @vkatsikaros points out, we currently mix up body parameters and URI template parameters.

**Comment by vkatsikaros** [comment]
Yep, my goal is to:

1. Clearly mention somewhere that `url variables` refer to the the URL template and `parameters` refer to the POST request body, and that they are the arguments to the algorithm described by the command's remote end steps.
2. In order to ease the reader and be consistent with the rest of the algorithms, to mention the arguments it accepts in each of the remote end steps, ie: 

go from 

> The remote end steps are:

to

> The remote end steps with arguments url variables and parameters are:

**Comment by vkatsikaros** [comment]
It looks like #673 handles this issue and can be closed
