### ISSUE TITLE
"JSON Object" dependency

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#683]
`JSON <a>Object</a>` is mentioned many times in the text. Should:
* a missing  [JSON Object](http://www.ecma-international.org/ecma-262/5.1/#sec-15.12) dependency be added
* and then  `JSON <a>Object</a>` be converted to `<a>JSON Object</a>`

If you agree, I am happy to work on it.

**Comment by shs96c** [comment]
We correctly link to the definition of `Object` every time, and the use of JSON disambiguates this type of Object from other kinds. I think the current text is good, though if you have a readable alternative for "JSON" that correctly captures the intent please feel free to suggest it.
