### ISSUE TITLE
Restructure Proxy reference table

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#689]
In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#h-proxy#h-capabilities), section [7.1 Proxy](https://w3c.github.io/webdriver/webdriver-spec.html#h-proxy#h-proxy):
> 7.1 Proxy

the reference table has some issues:
* https://github.com/w3c/webdriver/pull/677#issuecomment-275642627 (confusing language) 
* https://github.com/w3c/webdriver/pull/677#issuecomment-275665514 (uses normative language)
* missing a definition to refer to
* `Defines the URL for a proxy auto-config file if proxyType is equal to "pac". [URL]` couldn't understand what `[URL]` should reference.

**Comment by shs96c** [comment]
The PAC files don't appear to have a normative spec to link to. Removing the URL seems like the best bet, and we'll have to rely on the fact it's a widely understood term.

Closing this, since I think we've addressed all the issues that I think we can address, but please reopen if you disagree.
