### ISSUE TITLE
Term "input state"

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#691]
In chapter [17. Actions](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-input-state#h-actions), section [17.2 Input State](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-input-state#h-input-state):
> Each session has an associated input state table. This is a map between input id and the device state

I apologize if some of these points sound unclear to me, due to the lack of understanding some of the concepts involved:
* it is referenced as `object` in:
> As with real devices, virtual devices are stateful; this state is recorded in an input device state object associated with each device. 

Some related terms are also refered to as objects "null input state", "key input state".

* I am not sure I understand the definition: 
> This is a map between "input id" and the "device state" for that input source... 

as "device state" refers back to the "input state" table ie the map.

**Comment by shs96c** [comment]
Each of `key`, `pointer`, and `null` input sources have a related state. `device state` is the general term to refer to these in the general sense (in OO, I'd say that `key input state`, `pointer input state` and `null input state` "*is a*" `device state`

I think we're just seeing some of the evolution of this part of the spec poking through. We could do with refining the language a little more.

It seems like everyone is happy with `key input source`, `pointer input source` and `null input source`, and these can be referred to in the general sense as types of `input source`. Each `input source` has an associated `id`, and some persistent state (`device state` in this text, but probably we'd be okay with `source state` too)

The `input state table` is a mapping between `input source` IDs and `input source` instances. It's used to provide an efficient way of finding the right `input source`, but you could imagine a different data structure being used to hold the information --- all we need to be able to do is find the right `device state` given a particular `input source` ID.

Does that help clear things up?

**Comment by vkatsikaros** [comment]
Thank you for the clarifications!

If I understood you comment correctly, `input state table` and `device state` seem intertwined but shouldn't, and the reasons are:
* `key input state`, `pointer input state` and `null input state` are types of  `device state`, but this isn't mentioned somewhere
* at the same time `device state` links to `input state table` which is incorrect.
* and the definition of term `input state table` is leaving "table" out of the definition.

**Comment by shs96c** [comment]
I think this is now done. Closing.
