### ISSUE TITLE
New Session command delays returning errors until the capabilites are used.

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#701]
In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-process-capabilities#h-capabilities), section [7.3 Processing Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-process-capabilities#h-processing-capabilities):
> For each current desired capabilities corresponding to an indexed property in desired capabilities until matched capabilities is no longer null or there are no longer any entries to process:
> 
>     If current desired capabilities is not a JSON Object, return error with error code invalid argument.
> 
>     Let merged capabilities be the result of merging capabilities with required capabilities and current desired capabilities as arguments.
> 
>     If merged capabilities is an error, return the merged capabilities error.
> 
>     Set matched capabilities to the result of matching capabilities with merged capabilities as an argument. 

The way that this is phrased something like

    {"capabilities" {
        "alwaysMatch": {"browserName": "foo"},
        "firstMatch": [{"version": 1}, {"browserName": "bar"}]
        }
    }

Will only throw an error in the case that the browser isn't version 1 of foo. Similarly putting something other than a json object as a value in `firstMatch` would only throw an error if the earlier entries didn't match. This prevents reasonable implementation choices like storing the `firstMatch` as a `Vec<BTreeMap<Sring, Json>>`, and is user hostile since "working" code may suddenly break.

I also assume it's not what's intended.

This section should be refactored to ensure the structure is correct first.

**Comment by shs96c** [comment]
So you're suggesting that the algorithm should first create every possible merged capability, validate those, and only continue if everything looks valid?

That only makes sense for capabilities named in this specification. Anything outside of that scope (such as the chrome and firefox capability objects) would still cause the same lazy evaluation failure as we see today. Given that the capabilities might contain profile objects many 100s of MB large, this seems inefficient for remote end implementors to do, and doesn't actually catch all the possible errors.

**Comment by jgraham** [comment]
Well that depends. Is it obviously a conformance error to validate implementation-specific capabilities? If it is we should fix that.

Doing the validation doesn't seem particularly inefficient since you have to ship everything over the wire anyway (which is certainly the slow part) and a clever implementation could even avoid a copy by making the merged capabilities consist of pointers to the input data.

**Comment by jgraham** [comment]
In fact you don't even need to merge, you can always just iterate and typecheck. I can't see any reasonable way to make this slow :)
