### ISSUE TITLE
Too many syntaxes for universal matching capabilities.

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#711]
In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-process-capabilities#h-capabilities), section [7.3 Processing Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-process-capabilities#h-processing-capabilities):
> If capability value is null, undefined, or equal to the string "*", it is considered a match for the entry in matched capabilities. 

What's the point of allowing both `"*"` and `null`? This adds pointless implementation complexity. Also `undefined` can't happen here since json doesn't have an undefined value and we only iterate over properties that exist.

**Comment by shs96c** [comment]
`*` is a fairly well understood wildcard pattern which is why it's included. I guess we could make sure that local ends never send null values or `*`, but it'll take some hacking.

**Comment by jgraham** [comment]
I think what I would like is there just not to be three ways to say the same thing. I don't really mind about `null` vs `"*"`, but we should pick one and go with it.

**Comment by shs96c** [comment]
I think in this case, a local-end should strip "*" capabilities --- it's the same as not setting it in the first place.
