### ISSUE TITLE
It's very unclear what values capabilites can have

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#712]
In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-process-capabilities#h-capabilities), section [7.3 Processing Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-process-capabilities#h-processing-capabilities):
> "platformName"
>     Lowercase name of the current platform. 

I have no idea what this should be. "linux" (presumably not "ubuntu"?), "windows" ("windowsxp"?). "osx"? "macos"? What about various bsds?

**Comment by AutomatedTester** [comment]
@jgraham 

We now have 6e038ac2d1079af9b9eb8745a51eb1c98c55146f, is this sufficient to have this bug closed?

**Comment by jgraham** [comment]
Notes can't have RFC2119 keywords, so that patch is buggy. But otherwise that seems OK, but the same question applies to `platformVersion`.

**Comment by AutomatedTester** [comment]
ok cool, I will fix.

**Comment by AutomatedTester** [comment]
fixed in 60787c54940e12c0896e8ad99d6a3a4ec5d3ad70
