### ISSUE TITLE
Is the behaviour for wrong-type arguments intended?

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#716]
In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-process-capabilities#h-capabilities), section [7.3 Processing Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-process-capabilities#h-processing-capabilities):
> Otherwise, if capability value is not a string equal to the "browserName" entry in matched capabilities, return null. 

In this case if `browserName` has the value `2` or `["foo"]`, we simply ignore the entry. Is that intended? Should we throw an error instead?

**Comment by shs96c** [comment]
We should throw an error
