### ISSUE TITLE
Current session and session id on some commands

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#721]
[Processing Model](https://w3c.github.io/webdriver/webdriver-spec.html#processing-model) sets the "current session" to the session with ID "session id"
from the url variables. However, I don't see how some commands, with `{session id}`
in their Path Template, manage to find the session on which they will run.

I apologize, if I have missed something in the definitions that clarifies this.

Examples:

> The Get Timeouts command gets timeout durations associated with the current session. 

The remote steps are running against a known session, the [current session](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-current-session). Cool.

> The Go command is used to cause the user agent to navigate the current top-level browsing context a new location. 

However, the [current top-level browsing context](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-current-top-level-browsing-context) belongs to _a_ session, not
necessarily the [current session](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-current-session). 

Other similar commands: Get Current URL, Get Window Handle, Close Window, ...

> The Find Elements command is used to find elements in the current browsing context that can be used for future commands. 

Again, the [current browsing context](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-current-browsing-context) belongs to _a_ session, not
necessarily the [current session](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-current-session). 

Other similar commands: Get Active Element, Is Element Selected, Element Click, ...

**Comment by shs96c** [comment]
I'm not sure that this is a problem. Each end-node can only have one session at any given time, and an intermediary node can have any number of sessions: https://w3c.github.io/webdriver/webdriver-spec.html#dfn-maximum-active-sessions

Since this is the case, and the [processing model](https://w3c.github.io/webdriver/webdriver-spec.html#processing-model) (step 5) says that we'll have stopped processing if the session isn't active, we can't execute any command on a session that isn't active.

We may need to tighten up the language to say that end nodes are expected to perform these steps, but then from a local-end view, all kinds of [remote end](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-remote-end) are equivalent.

**Comment by vkatsikaros** [comment]
Ah, I get it now. I apologize as I failed to notice it when going through the definitions.

I looked at the text to see if there was something that assisted my own oversight & stupidity. I feel that the beginning of the chapter introduction has some entangled spots:
* mixing definitions and non-normative language
* some repetitions "A session is created with a New session request"
* the `A remote end that is not an intermediary node has at most one active session at a given time.` is actually mentioned twice, but not alongside the definition of "active sessions".

The correct meaning is there and the definitions are good, but I feel the text flow might confuse the reader. I'll put together a proposal to improve the text flow.

**Comment by vkatsikaros** [comment]
Feel free to close if you think that the above suggestion reflects personal taste, rather than an actual text flow improvement.

**Comment by andreastt** [comment]
vkatsikaros <notifications@github.com> writes:

> Feel free to close if you think that the above suggestion reflects
> personal taste, rather than an actual text flow improvement.

I don’t think the suggestions in https://github.com/w3c/webdriver/pull/739
are particularly invasive, and I think it makes the beginning of the
Sessions chapter better, so I have accepted it.

**Comment by vkatsikaros** [comment]
Suggestion merged, so I am closing
