### ISSUE TITLE
Generated action sequence id cannot be reused

### ISSUE THREAD

**Issue by mjzffr** [w3c/webdriver#723]
In chapter [17. Actions](https://w3c.github.io/webdriver/webdriver-spec.html#actions#h-actions), section [17.3 Processing Actions Requests](https://w3c.github.io/webdriver/webdriver-spec.html#actions#h-processing-actions-requests):
> If id is undefined let id be a new UUID. Otherwise if id is not a String return error with error code invalid argument. 

When the action sequence id is generated by the remote end, that id is not returned to the local end, so the local end can't reuse it in later commands.

Example: let's say we send a command A for `(keyDown, "m")` without specifying an id. The remote end creates a new input state with id "1" and `inputStateTable["1"].pressed = ["m"]`. Then if we send another command B for `(keyDown, "f")`, again a new id is generated so the remote end has another input state for that, say "2", and we have `inputStateTable["2"].pressed = ["f"]`.  Commands A and B resulted in two independent input states although the actions might all be dispatched for the same keyboard because there's only one such device.

That seems odd. A client can unintentionally send "anonymous" action sequences in a way that makes a single input device _appear_ stateless.

If the local end wants to send many actions commands for one device, it has to create an id so that it can reuse that id in subsequent commands. 

So maybe the local end should be able to GET input source ids and types to determine what's what?

**Comment by shs96c** [comment]
The way that the spec is written, the two keyboards would be considered separate (as if someone had plugged in a new USB keyboard for each set of interactions). It's true that clients could send "anonymous" action sequences --- the `Element Send Keys` command effectively does this --- but local ends are expected to set the action sequence name if they want to reuse a device.

I think that there's potentially an argument for saying that all sequences need an ID.
