### ISSUE TITLE
<datalist> handling 

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#735]
The Element Click command currently has a notion of _container elements_, which for `<option>` is `<select>` or `<datalist>`. However, a `<datalist>` element can be associated with any `<input>` in the document: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

The handling of `<datalist><option>foo</option></datalist>` in the spec right now is obviously incorrect, but it’s not clear to me how we can determine which element is `<option>`’s container when its context `<datalist>` can be arbitrarily associated with any unrelated `<input>` elsewhere in the document.

Thoughts?

**Comment by shs96c** [comment]
Hmmm... I think our definition of container isn't correct for `datalist`, but otherwise we're in pretty good shape. The container is easy to locate: it's the first element in the document with the `list` attribute set to the `id` of the `datalist` containing the `option`.

**Comment by andreastt** [comment]
But there may be multiple `<input list=mylist>` in the document:

```html
<datalist id=mylist>
 <option id=foo>foo</option>
 <option id=bar>bar</option>
</datalist>

<input list=mylist>
<input list=mylist>
```

When calling Element Click on `option#foo`, which of the `<input>`’s should have their text set?

This also brings into question another curiosity: Why is Element Click being used to type text into a text field?

**Comment by shs96c** [comment]
In answer to your question: the first matching element.

In answer to your second question, they're selecting an option with the mouse, not typing. Another option (no pun intended) we could follow is to return an error if the user tries to click an option in a datalist. As long as the behaviour is defined, we're in a reasonable position (though it does open up the question of how to test datalists populate things properly)

**Comment by andreastt** [comment]
Simon Stewart <notifications@github.com> writes:

> In answer to your question: the first matching element.

I think this is mildly surprising behaviour.  How would you test
selecting an option on the second <input>?  Is there any precedent for
this in existing driver implementations?

> In answer to your second question, they're selecting an option with
> the mouse, not typing.

OK.

> Another option (no pun intended) we could follow is to return an
> error if the user tries to click an option in a datalist. As long as
> the behaviour is defined, we're in a reasonable position (though it
> does open up the question of how to test datalists populate things
> properly)

I guess my point here is that interacting with a <datalist> does not
make any sense, since it is a sort of backing data store for different
<input>s to use.  What I’m missing is a way to specify _which_
<input>’s value should be set from interacting with <option>, but I
can’t think of any way to do that without changing the API.

**Comment by andreastt** [comment]
It also turns out that you can have `<select>` elements inside `<datalist>` for backwards compatibility, and these are not rendered if the browser knows how to deal with `<datalist>`:

```html
<input list=my-list>

<datalist id=my-lis>
 <label>Select one:
  <select>
   <option>foo</option>
   <option>bar</option>
  </select>
 </label>
</datalist>
```

This means we need to make ‘getting an element’s container’ handle when the element is an `<option>` but inside a `<datalist>` that itself may contain `<select>`. In this case `<select>` should be ignored completely.
