### ISSUE TITLE
Negate transparent element definition

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#738]
In chapter [11. Elements](https://w3c.github.io/webdriver/webdriver-spec.html#h-elements), section [11.1 Element Interactability](https://w3c.github.io/webdriver/webdriver-spec.html#h-element-interactability):
> An element is considered transparent if its opacity style property has the computed value of "1". 

This should say that “if its opacity style property _does not have_ the computed value of "1".”

**Comment by whimboo** [comment]
Transparent should really be the value `0`. Anything in between is translucent.

**Comment by whimboo** [comment]
To correct myself... if we don't talk about fully transparent but only transparent, it shouldn't make a difference. So I concur @andreastt.

**Comment by andreastt** [comment]
According to WebDriver, anything that is not fully opaque is not pointer-interactable. That means an element with opacity set to 0.9 is not considered pointer-interactable. We have a F2F decision on this from our meeting in Boston many years ago.

**Comment by AutomatedTester** [comment]
I have removed this as part of the work in #747

**Comment by AutomatedTester** [comment]
#747 has been landed
