### ISSUE TITLE
Determine whether removing opacity check was "correct"

### ISSUE THREAD

**Issue by shs96c** [w3c/webdriver#749]
No-one can remember precisely why #747 needed to change the check for opacity. Current theories suggest that it was because of a need to test click-jacking (handled by the check for "click intercepted" and the Actions commands), but it would be best to understand completely.

Raising this so that we don't forget to discuss.

**Comment by shs96c** [comment]
Also @jleyba and @jimevans.

**Comment by jleyba** [comment]
If an element has `opacity:0` you can still click on it, so opacity should not factor into whether you may interact with an element.

**Comment by jimevans** [comment]
I echo @jleyba's comment. And since we've codified the "other element would receive the click" behavior, my other main reasons for wanting it included have been resolved.

**Comment by shs96c** [comment]
Then there doesn't appear to be a need for this check. Closing the issue.

If this was a horror film, assuming everything alright would lead to _disastrous consequences_ later in the movie. Life is not a horror film….

Oh! This mogwai needs feeding, and it's not even midnight yet....
