### ISSUE TITLE
Inconsistent treatment of `null`

### ISSUE THREAD

**Issue by jugglinmike** [w3c/webdriver#760]
The specification references the null value in three different ways: plain
text, monospaced-formatted text (via `<code>`), and as a reference to the term
as defined by the ECMAScript specification (via `<a>`). The distinction does
not seem to be intentional, so I'd like to normalize on one treatment. The
ECMAScript reference seems like the most precise, but I'd appreciate input from
an editor before following up with a patch.

**Comment by shs96c** [comment]
I think `<a><code>null</code></a>` is appropriate --- that highlights that it's a code value, but links to the correct reference too.

**Comment by shs96c** [comment]
This may need to be done for `undefined` as well.
