### ISSUE TITLE
Close Window description

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#762]
In chapter [10. Command Contexts](https://w3c.github.io/webdriver/webdriver-spec.html#h-command-contexts), command [Close Window](https://w3c.github.io/webdriver/webdriver-spec.html#h-close-window) is the only command that doesn't follow the convention, of having a short description. Its name describes accurately what it does, so I submit this mostly as a note.

> 10.2 Close Window
> 
> HTTP Method 	Path Template
> 
> ... template ...
> 
> The remote end steps for the Close Window command are: 

Example of convention:
> 10.1 Get Window Handle
>
> HTTP Method 	Path Template
>
> ... template ...
>
> The Get Window Handle command ...blah blah blah...
>
> The remote end steps are:

**Comment by shs96c** [comment]
I agree that the name alone is probably sufficient for this command. The only thing that might be useful to have in a descriptive block would be the subtlety that closing the last window causes the session to end.

**Comment by shs96c** [comment]
But the steps are so short, I don't feel this explanation is necessary.
