### ISSUE TITLE
Resize/reposition capability

### ISSUE THREAD

**Issue by jugglinmike** [w3c/webdriver#765]
Chapter [10. Command Contexts](https://w3c.github.io/webdriver/webdriver-spec.html#resizing-and-positioning-windows#h-command-contexts), section [10.7 Resizing and Positioning Windows](https://w3c.github.io/webdriver/webdriver-spec.html#resizing-and-positioning-windows#h-resizing-and-positioning-windows) reads:

> WebDriver provides commands for interacting with the operating system window
> containing the current top-level browsing context. Because different
> operating system’s window managers provide different abilities, not all of
> the commands in this section can be supported by all remote ends. Where a
> command is not supported, an unsupported operation error is returned.

It may be that an application developer wishes to test some behavior based on window resizing/repositioning. Those tests are irrelevant in some contexts, but allowing failure on a test-by-test basis (by conditionally accepting the "unsupported operation" error as it is returned) can be cumbersome and tends to clutter test bodies.

If the developer could instead formally request this as a capability when starting the session, then the relevant branching could happen in advance of the tests themselves.

So I'm wondering: would it make sense to extend the Capabilities API with properties describing support for these operations?

**Comment by shs96c** [comment]
It probably makes sense, and this follows in the same footsteps as `acceptInsecureCerts`.

**Comment by andreastt** [comment]
I don’t understand how this is similar to `acceptInsecureCerts`. Configuring a session to

**Comment by shs96c** [comment]
Exactly. And a test that relies on that capability shouldn't have to wait until an `unsupported operation` error comes back to find out. Because it's a capability that might not be supported, it should be possible to require it explicitly when setting up the session. As you point out, some browsers that normally support resizing may not depending on the system they're running on (there are tile-based WMs that prohibit resizing to arbitrary sizes, for example)

That's exactly like the case with `acceptInsecureCerts` where a user requests this capability, and a remote end may decide, for whatever reason, to support it or not.

**Comment by andreastt** [comment]
OK, it sounds like we’re on the same page!

> As you point out, some browsers that normally support resizing may not depending on the system they're running on (there are tile-based WMs that prohibit resizing to arbitrary sizes, for example)

FWIW I don’t think that’s something we can test for on a browser level. The only realistic check would be if you needed to `alwaysMatch` on a browser that was resizable and the remote end was a mobile browser that already knew the characteristics of the system it was running on.

**Comment by shs96c** [comment]
Alright. I suggest that the capability be named "`canSetWindowRect`", "`supportsSetWindowRect`", or simply  "`setWindowRect`" and be a simple `boolean`.

**Comment by shs96c** [comment]
If anyone wants to run with this, please assign yourself and go for it :)

**Comment by jugglinmike** [comment]
@shs96c I'd love to give it a shot! Would you mind assigning it to me?

**Comment by jugglinmike** [comment]
I've submitted a patch over at gh-775, but now that I've written it up, I'm starting to wonder if the proposed implementation is scalable. I'm not familiar with the project's long-term plans for various browser APIs, but if it is to include commands for, e.g. [DeviceOrientation](https://w3c.github.io/deviceorientation/spec-source-orientation.html), then this same "conditionally implemented" behavior will be relevant there, too.

A `setWindowRect` capability describes "all or nothing" support for multiple commands. A finer-grained approach would make this feature more rich today, and it would provide a natural extension point for future commands. Maybe something like a `supportedCommands` capability would avoid this, as in:

```json
{
  "supportedCommands": {
    "Set Window Rect": true,
    "Minimize Window": true
  }
}
```

**Comment by shs96c** [comment]
The capabilities are the supported command structure you talk about :) When sent to the new session command, they describe a set of capabilities the remote end must match. When sent as a response they enumerate the commands that can safely be called. Local ends can use this information to either fail commands quickly, or to provide mixin-based functionality, or do something even more clever. 

As such, any command that MAY be implemented (as opposed to MUST) needs a capability. The granularity is up to us. I think it's safe to assume that we only need one "resize window" capability: we may need language in some of the related commands about making a "best effort" (e.g.  "Full screen" might be aliased to "maximise")

**Comment by jugglinmike** [comment]
I think we're on the same page there, but what I'm suggesting is extending the
"table of standard capabilities" with a new entry whose key is
`supportedCommands` and whose value type is "JSON object". My thinking is that
by introducing a configuration object whose keys map directly to command names,
we can formalize a pattern for future commands that "MAY be implemented." This
makes extensions more predictable, and it namespaces what might be a growing
list of related key/value pairs.

**Comment by shs96c** [comment]
I hear what you're suggesting, but it's not be necessary in selenium's history to date. Should we need that additional granularity, we should be adding new capbilities: the processing algorithm for new sessions doesn't handle recursing into values, and adding the additional complexity to avoid top-level keys seems unnecessary. 

We have the protocol extension section that handles how to add new capabilities (namespaced by vendor) so there's already a pattern for people who want to extend the capability set in a safe way.

**Comment by shs96c** [comment]
Also, command names are a convenient fiction. The spec is defined in terms of URLs and HTTP verbs, and local ends are left undefined giving them freedom to implement the APIs they deem most appropriate.

**Comment by jugglinmike** [comment]
Understood. Thanks for the background!
