### ISSUE TITLE
Commands back/forward should check if history items are available before going to navigate

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver#776]
While working on the back/forward implementation in Marionette I noticed that we actually don't have anything in the spec which allows both commands to actually check if history items are available at all. It means that with the current steps we will try to navigate even in those situations when no history items are available. As result we end-up with a timeout of 300s.

https://w3c.github.io/webdriver/webdriver-spec.html#back

I would propose that we add another step before step 3 which allows the browser to check if history items to navigate to are available. If there is none, we can immediately return with a specific error (maybe "unsupported operation"). It would safe around 300s.

**Comment by AutomatedTester** [comment]
This is already handled with step 3.

in [traverse the history by delta](https://html.spec.whatwg.org/#traverse-the-history-by-a-delta) it says that if there is no history abort.

That way if there is no history, step 4 won't be invoked and we head all the way to the last step to return success. I don't feel `unsupported operation` would be useful to be returned here.

**Comment by whimboo** [comment]
Which means that the back/forward command will return early without giving any indication that the requested action has not been executed. As result a followup command which eg. relies on an element of the expected page will fail, and it would not be clear why. 

Also when we are trying to click a non-reachable element we raise an exception and mark the command as failing. Why should this not be done for back and forward?
