### ISSUE TITLE
Steps for back/forward are missing page load strategy

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver#777]
https://w3c.github.io/webdriver/webdriver-spec.html#back

Right now in step 4 we should expect a pagehide and pageshow event. 

In regards of page load strategies it means we always wait for the "complete" readyState. But for page load strategy "eager" we would have to already return for "interactive".

**Comment by whimboo** [comment]
Beside that we also miss that a "hashchange" event can occur in cases when we navigate between different hashes of the same document. In such a case we wouldn't have to wait for the page being loaded at all, because the readyState is "complete" immediately.

**Comment by whimboo** [comment]
While further implementing this feature for Firefox I noticed the following missing items. Here everything which I collected so far:

- [ ] Handling of the page load strategy
- [ ] Events differ for "unload" given if it's a hashchange or not: pagehide vs. hashchange event
- [ ] Events differ for "load" given if the target page is an error page or not: pageshow vs. DOMContentLoaded (interactive readyState)

**Comment by whimboo** [comment]
We talked about this today with @AutomatedTester and @andreastt. Given the different events based on where the page gets loaded (bfcache or not) from, we figured out it might be better to also run the `post-navigation checks` and `wait for navigation to complete` similar to the get() command. But that would require to add the hashchange and pageshow events to the latter.

Also for the refresh command we would have to wait for pageHide or hashchange too. Which is identical to the back/forward command.

**Comment by whimboo** [comment]
Something else I have encountered while creating a testcase for navigating frames inside a frameset is that the goBack and goForward commands will result in DOMEvents happening for the browsing context but not for the  top browsing context. This is fine if you switched to the appropriate frame before. 

But if another goBack/goForward command is issued it can happen that the top level browsing context switches away from the frameset while the browsing context is still set to the frame. Here it's not clear in the spec what should be done.

As it looks like the callee has to know to which browsing context will change and as such select the correct one on its own.

**Comment by shs96c** [comment]
All event checking should be happening in the current browsing context. The user will have switched to this before performing the `go back` or `go forward` command. If they haven't, then the processing algorithm will mean that before they can issue any commands to that frame, any loading requests must have already matured.

Which is a really long way of saying that it may not matter.

**Comment by whimboo** [comment]
So what about the following steps:

1. Load page 1 without frames
2. Load page 2 with frames
3. Switch to frame 1
4. Perform `go back`

In this case the current browsing context is set to `frame 1`, but the `go back` command will actually issue a navigation to page 1. The load events we are expecting for the document for `go back` can not be seen because we are not in the top-level browsing context.

**Comment by AutomatedTester** [comment]
Looking at Selenium, the legacy FirefoxDriver never waited for page load on Forward or back. I suggest we do the same seeing the extent of the edge cases involved.

https://github.com/SeleniumHQ/selenium/blob/master/javascript/firefox-driver/js/firefoxDriver.js#L685-L693

**Comment by AutomatedTester** [comment]
Going to close this bug since it's not missing, its just not done in this case.
