### ISSUE TITLE
"Wait for navigation to complete" Step 2.2 and page loading strategy "none"

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#795]
I apologize if I have completely missed the answer from other parts of the spec.

In definition [wait for navigation to complete](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-wait-for-navigation-to-complete#h-navigation):

> 2.1 Let readiness target be the document readiness state tied to the current session’s page loading strategy, which can be found in the table of page load strategies.
>
> 2.2 Wait for the the current browsing context’s document readiness state to reach readiness target, or for the session page load timeout to pass, whichever occurs sooner. 

When the `page loading strategy` is "none", the `document readiness state` is not defined (or it's equal to an empty string?) in the [table of page load strategies](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-table-of-page-load-strategies#h-navigation). 

My question is what it means for `document readiness state` to reach the `readiness target` when the  `page loading strategy` is "none".

**Comment by shs96c** [comment]
Any `document readiness state` is acceptable when `page loading strategy` is `none` --- we don't bother checking it, and just return ASAP.

**Comment by andreastt** [comment]
When we have no page loading strategy, we should avoid comparing the document’s ready state.

**Comment by shs96c** [comment]
Fixed in 87fc5017
