### ISSUE TITLE
Should proxyType be case-insensitive?

### ISSUE THREAD

**Issue by juangj** [w3c/webdriver#803]
In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-process-capabilities#h-capabilities), section [7.1 Proxy](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-process-capabilities#h-proxy):
> "pac", "noproxy", "autodetect", "system", or "manual"

These are the legal values for the "proxyType" capability. This value is currently case-sensitive. For example, Geckodriver/Marionette won't set the proxy if the capabilities specify {"proxyType": "MANUAL"}.

The Java Selenium bindings currently send proxyType in all-caps -- the implementation detail is that there is an enum, with values named in all-caps, that is converted to a JSON string.

Should the spec call for case-insensitive matching, or should local ends be fixed to send only lowercase strings?

**Comment by shs96c** [comment]
I'll fix the local end.
