### ISSUE TITLE
Getting the XPATH for an element

### ISSUE THREAD

**Issue by morkeleb** [w3c/webdriver#816]
I'm writing [a small tool that stresses webpages with random input](https://github.com/morkeleb/clickmonkey).

The randomness of the tool means that it doesn't really care what it does. However. I'd like to be able to replay what the tool has done.

Today when you get an element you get an ELEMENT id. The id is internal to the selenium process. This is fine, but id like to be able to ask selenium for an XPath to that specific element.

If I had such an XPath my monkey could write a log to retrace it's steps. Allowing it to produce reproduction steps bugs it finds ( for example javascript errors or 404s).

**Comment by AutomatedTester** [comment]
I really think this is not in scope for the webdriver specification. If your code is walking the dom, it can log all the necessary information of the element it has just interacted with so that you could rebuild what you needed

**Comment by shs96c** [comment]
Agreed. Finding elements by xpath is fragile and prone to breakage, and yet it's trivial to calculate using a small amount of javascript. Both of these facts mean that this is out of scope for the spec.

If you're interested in heuristically determining a locator for an element, Oren Rubin has been doing some work in this area and has presented at Selenium Conference. The videos are online.
