### ISSUE TITLE
New Session payload example is wrong

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#818]
In chapter [8. Sessions](https://w3c.github.io/webdriver/webdriver-spec.html#new-session#h-sessions), section [8.1 New Session](https://w3c.github.io/webdriver/webdriver-spec.html#new-session#h-new-session):
> `{ "user": "alice", "password": "pw1234", "capabilities": {…} }`

The payload example under _New Session_ is wrong as it does not describe the reality of the new capabilities format.

**Comment by shs96c** [comment]
I'm not sure I agree. The spec says that the format will be something like:

`{
  capabilities: {
    alwaysMatch: {
    },
    firstMatch: []
  }
}`

In this context, the elided `capabilities` value is correct. The example is being used to highlight how authentication of intermediary nodes could happen, so omitting the structure of capabilities seems like a sensible thing to do.

Perhaps I misunderstand the report?

**Comment by shs96c** [comment]
Closing. I believe that the payload is correct for the `New Session` command (as defined by step 1 of the "[processing capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#processing-capabilities)" algorithm), and correctly demonstrates the point being made about authentication parameters being passed as top-level properties of the payload.
