### ISSUE TITLE
This should also just be /capabilities/

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#833]
In chapter [8. Sessions](https://w3c.github.io/webdriver/webdriver-spec.html#new-session#h-sessions), section [8.1 New Session](https://w3c.github.io/webdriver/webdriver-spec.html#new-session#h-new-session):
> Let body be a JSON Object initialised with:
> 
> sessionId
>     session id 
> capabilities
>     capabilities result

Sorry for the spam

**Comment by AutomatedTester** [comment]
duplicate of #830
