### ISSUE TITLE
We seem to lowercase the proxy object keys for no reason

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#835]
In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-proxy-configuration-object#h-capabilities), section [7.1 Proxy](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-proxy-configuration-object#h-proxy):
> Let key be the result of lowercasing key. 

This seems to be a mistake as the table actually has the keys in camel case, so if you do this they will never match (in general I would much prefer we don't try to correct case here since we don't elsewhere).

**Comment by juangj** [comment]
I think this was a mistake introduced in the process of addressing https://github.com/w3c/webdriver/issues/803; you are correct that it does not make sense to lowercase the key.

**Comment by andreastt** [comment]
As I understand it https://github.com/w3c/webdriver/commit/a17c66a2a78bf649fafc29d2d7fb7e102c08508c should be reverted, and local ends fixed to send `{proxyType: "manual"}`.
