### ISSUE TITLE
Normative requirements in the "description" column are never invoked

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#838]
In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-proxy-configuration#h-capabilities), section [7.1 Proxy](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-proxy-configuration#h-proxy):
>  If ftpProxyPort is defined in ftpProxy and from this property, return error with error code invalid argument. 

It's not clear at what point these requirements are supposed to apply.

**Comment by shs96c** [comment]
They're applied in step 3.4 of "[deserialize as a proxy](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-deserialize-as-a-proxy)". Is this a request to refer to this section in the table header?

**Comment by shs96c** [comment]
Assigning to @jgraham for clarification

**Comment by shs96c** [comment]
I believe that we are using these values properly. Please reopen this issue if you disagree.
