### ISSUE TITLE
Ports should be defined as more than just integers

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#840]
In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-proxy-configuration#h-capabilities), section [7.1 Proxy](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-proxy-configuration#h-proxy):
> ftpProxyPort 	number 	Defines the proxy port for FTP traffic when the proxyType is equal to "manual". If ftpProxyPort is defined in ftpProxy and from this property, return error with error code invalid argument. 	An integer

They should be in the range `0-2**16-1`

**Comment by andreastt** [comment]
We could probably just refer to URL’s [port definition](https://url.spec.whatwg.org/#concept-url-port).

**Comment by shs96c** [comment]
Closing: we do refer to URL's port definition.
