### ISSUE TITLE
Actions examples: Ticks or Batches

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#842]
In chapter [17. Actions](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-tick#h-actions):
> Example 9

In the 3 out of 4 visual representation of actions, the actions are grouped together by "Batch" whereas in the other they are grouped by "Tick". However, in the diagram explanations, the "batches" are not referred to.

**Comment by shs96c** [comment]
`Ticks` is the appropriate term
