### ISSUE TITLE
Unregognised extension capabilites must be ignored

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#844]
In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-merging-capabilities#h-capabilities), section [7.2 Processing Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-merging-capabilities#h-processing-capabilities):
> Let value be the result of trying implementation-specific steps to match on name with value. If the match is not successful, return success with data null. 

This should make it clear that if the capability is an extension capability and it's not recognised then it must be ignored (similarly in the validation section).

**Comment by shs96c** [comment]
Step 3 if the algorithm for validating a capability name means an end-node will return an error if the name is not an extension capability. There's no way to get to `matching capabilities` without first validating, so (other than emphasis) there's no need for the additional stricture.

**Comment by shs96c** [comment]
Reading the spec more closely, I think you're talking about the case where someone passes in an extension capability meant for another browser:

```
{
  moz:options: {},
  se:screenshotOnError: true,
}
```

This would pass validation, but would currently cause matching to fail. I believe that you're suggesting that, instead, we pretend that a match was made, yet never return that in the capabilities returned by the `New Session` command. Is that correct?

If so, this seems to be the exact situation we were trying to avoid with the move away from Selenium's "desired capabilities" model. My understanding from the F2F sessions was that the behaviour we wanted was "all or nothing".

**Comment by shs96c** [comment]
I opened #758 so that intermediary nodes could filter out information that they considered important (`se:screenshotOnError` in the example above) to allow the "all or nothing" behaviour of capability matching by end nodes.

**Comment by shs96c** [comment]
Assigning to @jgraham for clarification. Feel free to assign back to me later.
