### ISSUE TITLE
Expand Action examples

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#847]
In chapter [17. Actions](https://w3c.github.io/webdriver/webdriver-spec.html#actions#h-actions) the note
> Expand these examples 

refers to the short "pressing a key" and " pinch-zoom" in the 1st paragraph of the Actions chapter or to the 4 examples with the diagrams below?

CC @andreastt who initially marked this issue

**Comment by vkatsikaros** [comment]
If the note is still relevant and it refers to "pressing a key" and " pinch-zoom", I'd be happy to convert the examples to diagrams like the rest of the action examples.

**Comment by andreastt** [comment]
I think probably that issue can be removed. The example in that chapter is already quite thorough, but it probably needs some editing.

**Comment by shs96c** [comment]
Closing, as per @andreastt's comment. I'd like to add that there are now multiple local-end implementations of these commands, and they appear to work (or at least "not fail") with the latest versions of geckodriver --- presumably this implies the spec is comprehensible.

**Comment by vkatsikaros** [comment]
I apologize for just seeing this was closed. In case I misunderstood that the "note" can be removed, please ignore the pull request.

**Comment by shs96c** [comment]
No worries. Thank you for the PR!
