### ISSUE TITLE
Proposal to return toJSON if it exists on object

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#849]
I’d like to propose to return `res.toJSON`’s return value if an own property named `toJSON` exists and it is a `typeof == "function"` on the result of _Execute Script_ and _Execute Async Script_.

This would avoid nasty surprises such as attempting to serialise recursive objects such as `window.performance`:

https://github.com/mozilla/geckodriver/issues/328#issuecomment-273571833

Currently you have to `execute_script("return JSON.stringify(window.performance)")` to get the JSON representation of `window.performance`. It would be nicer if we could return the result’s provided JSON representation if it exists.

This would be harmonious with the behaviour of `JSON.stringify`, which looks at whether the argument provides a `toJSON` property that is a function, and returns this if it exists.

**Comment by shs96c** [comment]
Seems reasonable to me. I'd approve that PR, since I'd imagine some implementations are already calling `JSON.stringify`
