### ISSUE TITLE
Refresh doesnt need to wait for page load for file://

### ISSUE THREAD

**Issue by AutomatedTester** [w3c/webdriver#864]
In chapter [9. Navigation](https://w3c.github.io/webdriver/webdriver-spec.html#refresh#h-navigation), section [9.5 Refresh](https://w3c.github.io/webdriver/webdriver-spec.html#refresh#h-refresh):
> Run the post-navigation checks and return its value if it is an error.

**Comment by shs96c** [comment]
If the algorithm is run, it should return instantly (as the command could not have begun execution until after the page loading strategy's criteria are met). Is it harmful to do this? Or are you trying to avoid an unnecessary step? If the latter, can this be left to implementations to implement, as the observable result would be identical in both cases?

**Comment by whimboo** [comment]
@AutomatedTester why shouldn't we? From what I see (at least for Firefox) we clearly get correct events raised to abort early given the set page load strategy.

```
1503676874052	Marionette	TRACE	6 -> [0,22,"refresh",{}]
1503676874062	Marionette	DEBUG	Received DOM event "beforeunload" for "file:////Volumes/data/code/gecko/testing/marionette/harness/marionette_harness/tests/unit/data/test.html"
1503676874070	Marionette	DEBUG	Received DOM event "pagehide" for "file:////Volumes/data/code/gecko/testing/marionette/harness/marionette_harness/tests/unit/data/test.html"
1503676874070	Marionette	DEBUG	Received DOM event "unload" for "file:////Volumes/data/code/gecko/testing/marionette/harness/marionette_harness/tests/unit/data/test.html"
1503676874080	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "file:////Volumes/data/code/gecko/testing/marionette/harness/marionette_harness/tests/unit/data/test.html"
1503676874085	Marionette	DEBUG	Received DOM event "pageshow" for "file:////Volumes/data/code/gecko/testing/marionette/harness/marionette_harness/tests/unit/data/test.html"
```
