### ISSUE TITLE
Matching capabilities algorithm rejects some valid capabilities

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#867]
In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-matching-capabilities#h-capabilities), section [7.2 Processing Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-matching-capabilities#h-processing-capabilities):
> Otherwise
> 
>     If name is not the key of an extension capability and the remote end is an endpoint node return success with data null. 

By this point we have already validated capabilities, so it shouldn't be neccessary to do any more validation. More importantly, if you pass in e.g. `timeouts` this will cause it to be rejected since that doesn't appear anywhere on the list of capabilities above. I'm not sure if the intent is that those things don't get returned even if they were set? In any case I think the current wording is broken.

**Comment by shs96c** [comment]
Fixed by #868. Thanks @jgraham
