### ISSUE TITLE
Link targets not taken into account when waiting for navigation to complete

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#871]
The [‘wait for navigation to complete’](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-wait-for-navigation-to-complete) algorithm looks at the current browsing context when testing if the readiness target has been reached. This works for normal links where the default link target is `_self`, meaning the resource should be loaded into the same browsing context as the current one.

The number of “special targets” that can be provided to `<a target=…>` are many. Quoting liberally from MDN’s article on the [`<a>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target):

- `_self`: Load the URL into the same browsing context as the current one. This is the default behavior.
- `_blank`: Load the URL into a new browsing context. This is usually a tab, but users can configure browsers to use new windows instead.
- `_parent`: Load the URL into the parent browsing context of the current one. If there is no parent, this behaves the same way as `_self`.
- `_top`: Load the URL into the top-level browsing context (that is, the “highest” browsing context that is an ancestor of the current one, and has no parent). If there is no parent browsing context, this behaves the same way as `_self`.

WebDriver consequently needs to expect a different browsing context when interacting with a link that has one of `_blank`, `_parent`, or `_top` targets set. `_self` is fine since that operates on the current browsing context.

**Comment by shs96c** [comment]
If the target for the page to load isn't the current browsing context, we should be okay, as [step 7 of the Processing Model](file:///Users/shs/src/selenium/spec/webdriver-spec.html#processing-model) says that we should wait for loading to complete before continuing. 

I think we're even covered in the case of frame-busting code, though this would require a user to switch to the `null` frame before issuing more commands (which sounds nasty, but isn't unreasonable)

**Comment by shs96c** [comment]
Put another way, switching browsing context is always an action that users need to initiate.

**Comment by shs96c** [comment]
Closing this. I hear the concerns, but the expected usage is something like:

```
# Cause a new window to open
element.click()
# Identify new window handle
driver.switch_to.window(handle)
driver.find_element("id", "cheese")
```

We're not attempting to track what the browser believes to be the current active browsing context, and the way the spec is written means that we don't try and execute commands in a context that doesn't meet the criteria of the page loading strategy.

**Comment by andreastt** [comment]
> If the target for the page to load isn't the current browsing context, we should be okay, as step 7 of the Processing Model says that we should wait for loading to complete before continuing.

It’s the Element Click command that should wait for the page to finish loading before returning; not the next command that is requested.

But even if the processing model calls ‘wait for navigation to complete’, you still have the inherent problem that it looks at the _current browsing context_:

> If there is an ongoing attempt to navigate the current browsing context that has not yet matured, wait for navigation to mature. 

To be clear: It is not the current browsing context that is being navigated when clicking `<a target=_top>`: it is the top-level browsing context the current browsing context is associated with.

> Put another way, switching browsing context is always an action that users need to initiate.

This is true, and I’m not suggesting we change the WebDriver-defined state of the current browsing context. What I’m saying is that the ‘wait for navigation to complete’ algorithm needs to look at the document readiness of the browsing context associated with the `target` attribute instead of the selected current browsing context.

> Closing this. I hear the concerns, but the expected usage is something like:
>
>     # Cause a new window to open
>     element.click()
>     # Identify new window handle
>     driver.switch_to.window(handle)
>     driver.find_element("id", "cheese")

Again, I’m not suggesting that Element Click is made to automatically switch the user to the new browsing context. But it needs to wait for the navigation to finish before returning, which means listening for the `DOMContentLoaded` event and looking at the `document.readyState` of another browser context, since it is not the current browsing context that is being navigated.

**Comment by shs96c** [comment]
I disagree about the need to track the `target`: all our commands only focus on the current browsing context, and the click command should do the same thing while waiting for the click to finish. This makes the implementation a lot simpler and keeps the model consistent.

In addition, as far as I'm aware, no existing implementation looks at the `target` of a click in order to figure out when to return control to the local end. Maybe I'm wrong?

**Comment by andreastt** [comment]
This isn’t about whether you disagree or not: the spec is _wrong_ the way it is written now.

> all our commands only focus on the current browsing context, and the click command should do the same thing while waiting for the click to finish. 

This isn’t about changing the current browsing context, but about making the wait-for-page-to-load algorithm wait for the _navigation_ to complete in the correct browsing context.

> In addition, as far as I'm aware, no existing implementation looks at the target of a click in order to figure out when to return control to the local end. Maybe I'm wrong?

I’m not sure what existing implementations do, but I suspect they handle, and wait for the navigation to complete, in the case where a click in a nested browsing context causes the top browsing context to navigate. At least there is a test for that in the Ruby bindings.

**Comment by shs96c** [comment]
It's been a while since I looked at this. Here's what I think will happen with the way the spec is currently written:

- Target is `_self`: we attempt to detect the navigation and wait for it to complete:
- Target is `_blank`: there's no navigation event detected, since it's not happening in our browsing context. Should we switch to the new context, then the processing model means we'll wait for it to finish loading before executing commands.
- Target is `_parent`: the current browsing context may go away, and we have a bug in the spec sine this is not handled in the algorithm.
- Target is `_top`: If the current browsing context is actually `_top`, then we have correct behaviour. Otherwise, we have the same bug as with `_parent`.

I think we'll have valid behaviour if we amend the [wait for navigation to complete](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-wait-for-navigation-to-complete) algorithm to handle the case where the current context has disappeared.

**Comment by whimboo** [comment]
@shs96c your PR #932 got merged about 2 months ago. As claimed it should fix all the items in this issue. Does it mean that we can finally close it?

**Comment by shs96c** [comment]
@ato seemed to have strong opinions. If he's happy, we can close this.
