### ISSUE TITLE
Wrong use of hasAttribute for editable element

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#884]
In chapter [11. Elements](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-editable#h-elements):
> element is an input element for which hasAttribute "checked" is false and for which the input event applies. 

We should reuse the definitions from the HTML spec to refer to what it means for an element not be editable. That `<input checked>` `hasAttribute` "checked" does not make it a checkbox.

**Comment by shs96c** [comment]
This check excludes both radio buttons and checkboxes. Looking at [this (non-normative) table](https://html.spec.whatwg.org/#input-type-attr-summary), it seems that this definition captures every element that we could clear. But your point is taken. I'll try and rephrase.
