### ISSUE TITLE
Resettable element does not include elements that are contenteditable

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#885]
In chapter [14. Element Interaction](https://w3c.github.io/webdriver/webdriver-spec.html#element-clear#h-element-interaction), section [14.2 Element Clear](https://w3c.github.io/webdriver/webdriver-spec.html#element-clear#h-element-clear):
> If element is not editable and is not resettable return an error with error code invalid element state. 

It doesn’t make sense to exclude contenteditable elements from those that can be cleared.  [Resettable](https://html.spec.whatwg.org/#category-reset) elements are in HTML limited to:

> Resettable elements
> Denotes elements that can be affected when a form element is reset.
> `input`, `output`, `select`, `textarea`

**Comment by shs96c** [comment]
Subtle. I think we need to change step 3 of the algorithm. The intent was to allow clearing of both contenteditable and resettable fields (as evidenced by step 8), but that's not how it reads now:

> 3. If element is not editable and is not resettable return  an error with error code invalid element state.

Clearly that should be something along the lines of `if neither editable nor resettable`
