### ISSUE TITLE
<body> element should only be keyboard-interactable in HTML or XHTML

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#888]
In chapter [11. Elements](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-keyboard-interactable-element#h-elements), section [11.1 Element Interactability](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-keyboard-interactable-element#h-element-interactability):
> A keyboard-interactable element is defined to be any element that has a focusable area, or is the body element.

The `<body>` element should only be considered keyboard-interactable when the document is in HTML- or XHTML mode. It does not make sense for it to be keyboard-interactable in SVG, for example.

**Comment by shs96c** [comment]
I suspect that we might need language to say something about being able to process keyboard events. I note that the HTML spec defines BODY as having the "[GlobalEventHandlers](https://html.spec.whatwg.org/#globaleventhandlers)", which include ones for `keyDown`, `keyPress`, and `keyUp`, so perhaps we might be able to rely on the presence of these handlers, or their equivalents, in other contexts?

@jgraham, I'd appreciate your input on this.

**Comment by andreastt** [comment]
The intention of the keyboard interactable check is for the high-level Element Send Keys command to check if form control elements and contenteditable elements are possible to reach using the keyboard, so something like that makes sense to me.
