### ISSUE TITLE
Reason for choosing random uuid as element identifier

### ISSUE THREAD

**Issue by christian-bromann** [w3c/webdriver#900]
In chapter [11. Elements](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-web-element#h-elements):
> The web element identifier is the string constant "element-6066-11e4-a52e-4f735466cecf".

I am just wondering why the element identifier has changed from `ELEMENT` to this random uuid? What is the reason behind that? Thanks!

**Comment by andreastt** [comment]
If you were to return `{"ELEMENT": "foobar"}` from an injected script in Selenium, it would be attempted unmarshaled as a web element. WebDriver returns a UUID key to avoid key collision in the absence of a more sophisticated serialisation format.

**Comment by christian-bromann** [comment]
Makes sense. However the problem you are describing would also apply if you would return `{"element-6066-11e4-a52e-4f735466cecf": "foobar"}`, right? So it is chosen more randomly to try to avoid this.

**Comment by andreastt** [comment]
Yes, that’s a correct observation.

If we wanted to avoid this entirely, we would have to invent a JSON serialisation for the JS type system. For what it is worth, I do think that we ought to look into that in the future. Perhaps we could derive something of existing remote devtools protocols.

**Comment by christian-bromann** [comment]
Thanks for the info!
