### ISSUE TITLE
Consider making navigator.webdriver non-configurable

### ISSUE THREAD

**Issue by shekyan** [w3c/webdriver#914]
In chapter [4. Interface
    ](https://www.w3.org/TR/webdriver/#interface#h-interface):
> partial interface Navigator {
>     readonly attribute boolean webdriver;
> };

In browser implementations that I observed, navigator, as well as navigator properties are configurable. However, I don't see a use-case off top of my head why webdriver property should follow that pattern and do not have [Unforgeable] attribute.

**Comment by shs96c** [comment]
I didn't realise that was an option. Excellent idea.

**Comment by annevk** [comment]
FYI: I filed #922 on reverting this.
