### ISSUE TITLE
Broken handling of script `args` argument

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#919]
In chapter [15. Document Handling](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-extracting-the-script-arguments-from-a-request#h-document-handling), section [15.2 Executing Script](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-extracting-the-script-arguments-from-a-request#h-executing-script):
> If args is not an Object or its [[Class]] internal property is not Array or Object, return error with error code invalid argument.
> 
> Let arguments be a List consisting of a json deserialization of each item in args with the order preserved. 

I think those steps should just read:
```
* If `args` is not an [Arrsy]() return [error]() with error code [invalid argument]().
```

It's already been deserialized and can't be an Object.

**Comment by shs96c** [comment]
I can't think when it would be valid to pass an `Object` as the `args` anyway.

**Comment by shs96c** [comment]
In step 6 of the [Processing Model](https://w3c.github.io/webdriver/webdriver-spec.html#processing-model) we've simply [deserialized the JSON](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-json-deserialization). This won't have expanded things like WebElement references. I think we're missing a call to the [JSON deserialize](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-json-deserialize) algorithm, which is subtly different.
