### ISSUE TITLE
Why Unforgeable

### ISSUE THREAD

**Issue by annevk** [w3c/webdriver#922]
In chapter [4. Interface](https://w3c.github.io/webdriver/webdriver-spec.html#interface#h-interface):
> [Unforgeable]

I don't see how this makes sense, since navigator itself can be manipulated easily.

**Comment by andreastt** [comment]
This was suggested in https://github.com/w3c/webdriver/issues/914. I thought the idea of `[Unforgeable]` was to prevent it from being manipulated, but does that not have the desired effect on `navigator`?

**Comment by bzbarsky** [comment]
It has the desired effect, _if_ you have your hands on a `Navigator` object.

But nothing prevents `window.navigator` from being some random object script decides to put there, instead of an actual `Navigator` object, because the `navigator` property on `Window` is configurable.

**Comment by domenic** [comment]
We're planning to rename [Unforgeable] to [LegacyUnforgeable] in Web IDL, which should hopefully make this kind of misunderstanding less common...

**Comment by annevk** [comment]
Sounds good. After we investigated the usage on `Location` it does indeed seem to the benefit of legacy plugins and not much else.

**Comment by andreastt** [comment]
Thanks all for the input! I will address this and https://github.com/w3c/webdriver/issues/923 to drop `[Unforgeable]` and use a `WorkerNavigator` mixin.

**Comment by shekyan** [comment]
Uh, thanks for taking care of this. It was my idea to propose make it [Unforgeable], and being aware that `navigator` is configurable *now*, my thought was that it won't hurt and things will align when `navigator` become non-configurable.

**Comment by bzbarsky** [comment]
There are no plans to make `navigator` non-configurable, and in fact I'm fairly sure that would not be web-compatible.
