### ISSUE TITLE
Extend Navigator through a mixin

### ISSUE THREAD

**Issue by annevk** [w3c/webdriver#923]
In chapter [4. Interface](https://w3c.github.io/webdriver/webdriver-spec.html#interface#h-interface):
> partial interface Navigator

The way you extend Navigator doesn't work for workers, which use WorkerNavigator. You need to define a [NoInterfaceObject] interface that is implemented by both Navigator and WorkerNavigator, similar to how the HTML Standard does it.

**Comment by cdumez** [comment]
Do we really want to expose this attribute to workers?

**Comment by annevk** [comment]
I don't really have an opinion on that, though if not it would still be good to extend Navigator through a mixin I think since that's how we always extend it. And then just point out it's intentionally not exposed on workers.
