### ISSUE TITLE
New Session command doesn't set the current browsing context

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#924]
In chapter [8. Sessions](https://w3c.github.io/webdriver/webdriver-spec.html#new-session#h-sessions), section [8.1 New Session](https://w3c.github.io/webdriver/webdriver-spec.html#new-session#h-new-session):
> 8.1 New Session

Typically implementations start a new browsing context when the session is created and set that as the new [top-level] browsing  context. I don't think that creating a new one should be required, but it should either create a new one, or make an existing UA-specific browsing context the current browsing context (e.g. one that has focus).

**Comment by asajeffrey** [comment]
This came up in the context of Servo, trying to make our webdriver implementation line up with the specification.

**Comment by andreastt** [comment]
The current expectation in the available corpus of drivers, is that the current top-level browsing context should become the current browsing context of WebDriver, i.e. that it’s not expect a new one be opened, although I’m not against leaving that decision to the discretion of the implementor.
