### ISSUE TITLE
User prompt handler should not dismiss prompts unless specifically configured

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#925]
In chapter [18. User Prompts](https://w3c.github.io/webdriver/webdriver-spec.html#dismiss-alert#h-user-prompts):
> missing value default state
> not in the table of simple dialogs
> 
>         Dismiss the current user prompt. 

This means that you can never get an unexpected user prompt error and then use the /alerts/ endpoints to interact with it.

**Comment by shs96c** [comment]
This is intended. The rationale is that people will write code that expects everything to work properly, and won't be expecting the unexpected alert, and so won't have error handling code in there. Returning the error allows these users to be aware that something untoward happens, and the dimissal of the prompt means that the _next_ command will work as expected.

For example

```
@Test
public void thisHasAnAlert() {
  driver.get("http://example.com");
  WebElement element = driver.findElement(By.name("q"));
  // Alert opens because of this interaction
  element.click();
  element.getText();  // Exception thrown here. 
}

@Test
public void shouldReuseTheDriver() {
  // Test runs as expected because the user prompt is already dismissed.
  driver.get("http://example.com");
}

```

**Comment by jgraham** [comment]
It seems like there ought to at least be an opt-in method of not auto-handling alerts. AFAICT the alert API is mostly useless; it relies on you doing a thing that you know opens an alert and then carefully not running any other commands. You can't be notified that an alert was opened and then inspect it.

**Comment by shs96c** [comment]
If the user doesn't specify an unhandled prompt handler, then you can interact with things. If the above example had been written the user will have interacted with things properly:

```
@Test
public void thisHasAnAlert() {
  driver.get("http://example.com");
  WebElement element = driver.findElement(By.name("q"));
  // Alert opens because of this interaction
  element.click();
  Alert alert = driver.getAlert();
  System.out.println(alert.getText());
  alert.dismiss();
}
```

**Comment by shs96c** [comment]
But we could add a new prompt handler of "leave in place"

**Comment by shs96c** [comment]
I'm getting married and in the final days before the wedding. I'm going to replying very slowly to this issue until I return to the UK.

**Comment by shs96c** [comment]
@jgraham's comment about needing to be aware that an alert would open and then interacting with it is correct (though, logically, no different from any other command --- you need to know what's happening to interact with things). I'm totally on-board with adding a "throw an exception, but leave it in place" option to the [prompt handler table](https://www.w3.org/TR/webdriver/#dfn-known-prompt-handling-approaches-table).

**Comment by andreastt** [comment]
Right, thanks for your explanation in https://github.com/w3c/webdriver/issues/925#issuecomment-303728008. I now understand how it’s supposed to work.

> But we could add a new prompt handler of "leave in place"

I think this is a good idea. And it’s pluggable into what we have currently.

> I'm getting married and in the final days before the wedding. I'm going to replying very slowly to this issue until I return to the UK.

In totally off-topic way, that is great news! Congratulations!
