### ISSUE TITLE
we explicitly decided not to match innertext

### ISSUE THREAD

**Issue by thejohnjansen** [w3c/webdriver#933]
at TPAC we decided to follow the Selenium code for v1 and revisit in the future[1]. Calling this out as "similar to innertext" here seems misleading.

[1] http://www.w3.org/2016/09/20-webdriver-minutes.html

**Comment by shs96c** [comment]
The only reference I can find in the spec to `innerText` is in the description of [Get Element Text](https://w3c.github.io/webdriver/webdriver-spec.html#get-element-text), where we use the language: 

```
This is approximately equivalent to calling element.innerText.
```

Are you suggesting we remove this reference?

**Comment by thejohnjansen** [comment]
Sorry for the delay in responding. And also apologies for the ambiguous link. I thought that by clicking to "file an issue" with the spec, it would link my issue back to the actual line number where I clicked. 

Yes, I think referring to two things here is risky (and confusing): "approximately equivalent to calling element.innerText" is ambiguous. My first question was "how is it different from doing that?" and how close is "approximately"? I then see a link to the Selenium source code, but I don't think that can be normative - the source code could change and/or people might not have permission to read it.

**Comment by andreastt** [comment]
I am happy to remove the “approximately equivalent to innerText”. It is totally unnecessary and only of historical value.
