### ISSUE TITLE
Timeout-based behavior may be untestable

### ISSUE THREAD

**Issue by jugglinmike** [w3c/webdriver#950]
While working on WebDriver tests in the Web Platform Tests project, I've
started to identify aspects of certain algorithms that appear to be untestable.
Specifically, it seems as though any behavior based on waiting/timing out
cannot be reliably observed from either the process issuing driver commands or
from the browsing context itself.

For example, from [the find algorithm](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-find):

> 1. Let end time be the current time plus the session implicit wait timeout.
>
> [...]
>
> 4. Let elements returned be the result of the relevant element location
>    strategy call with arguments start node, and selector.
> 5. If a DOMException, SyntaxError, XPathException, or other error occurs
>    during the execution of the element location strategy, return error
>    invalid selector.
> 6. If elements returned is empty and the current time is less than end time
>    return to step 4. Otherwise, continue to the next step. 

The element retrieval operation in step 4 is not directly observable. Tests can
only verify the result of the overall command--they cannot determine how many
retrieval attempts were made to reach that result (i.e. whether polling has
taken place).

It is possible to issue a "find element" command for a non-existent element and
subsequently execute a script to define that element. If the "find element"
command then returns the correct element reference, it seems likely that the
implementation is correct. However, this is not guaranteed. That's because of
the unobservable nature of the retrieval operation--such a test would only be
effective if the element were inserted *after* at least one attempt to retrieve
were made.

A "best effort" approach might involve setting a long (e.g. 3000 ms) implicit
wait timeout and deferring element insertion until half of that time had
passed.  Practically speaking, it seems likely that polling would be in
progress after 1.5 seconds... But this is still fundamentally a race condition.
And although longer timeouts would make expression of the race less likely,
WebDriver tests are already among the slowest in WPT; relying on such long
delays will make them even more so.

I believe this general problem applies to most (if not all) algorithm steps
that involve "waiting" (e.g. "wait for navigation to complete" in [the "Go"
command](https://w3c.github.io/webdriver/webdriver-spec.html#go)).

If this assessment is accurate, I can think of four possible responses:

1. Accept the functionality as untestable and do not make any attempt to verify
   it within WPT
2. Parameterize all timeout intervals such that test consumers can select a
   value that is appropriate for their environment
3. Approximate appropriate delays by issuing parallel "simulation" commands.
   For "find element," this would mean a second "find element" command for an
   element that is known to be present. It seems likely that by the time this
   command returned, the first command (i.e. the one under test) would be in
   the process of polling.
4. Extend the WebDriver operations to be observable (likely from the browsing
   context)

Option 1 is the most convenient for folks writing specification tests, but it
obviously doesn't help implementers or application developers.

Option 2 doesn't really address the problem; it just kind of forces test
consumers to take some ownership.

Option 3 involves a delay that is more contextual and likely shorter than
option 2, but due to the nature of HTTP (and in the absence of any assurance
regarding scheduling of concurrent commands), it would still be subject to a
race. It is also awkward to author tests like this, particularly for navigation
operations.

Option 4 would certainly solve the problem, but it would also require
standardizing behavior that is really only relevant for conformance testing and
has little value for application developers (and which itself would be subject
to bugs an require testing).

...so I'm hoping that either my problem definition is flawed or that there is a
fifth solution.

**Comment by andreastt** [comment]
Sorry for the delayed response, but thank you for a thoughtful and
well-balanced write up.

Also sprach jugglinmike:

> The element retrieval operation in step 4 is not directly
> observable. Tests can only verify the result of the overall
> command--they cannot determine how many retrieval attempts were made
> to reach that result (i.e. whether polling has taken place).

This seems sufficient to me.  After all, we are writing an integration
test suite which purpose it is to assert conformance.  Lower-level unit
tests that it is harder to share between vendos, could be seen as the
responsibility of individual implementations.

> It is possible to issue a "find element" command for a non-existent
> element and subsequently execute a script to define that element. If
> the "find element" command then returns the correct element reference,
> it seems likely that the implementation is correct. However, this
> is not guaranteed. That's because of the unobservable nature of the
> retrieval operation--such a test would only be effective if the
> element were inserted *after* at least one attempt to retrieve were
> made.

But the Execute Script command can’t be issued whilst another, such as
Find Element, is in process.  The blocking nature of the main event loop
ensures this.  It is of course possible that an element gets created
in the DOM due to the nature of the document, and we should test this
eventuality.

> A "best effort" approach might involve setting a long (e.g. 3000 ms)
> implicit wait timeout and deferring element insertion until half of
> that time had passed.  Practically speaking, it seems likely that
> polling would be in progress after 1.5 seconds... But this is still
> fundamentally a race condition.

It can cause flakiness, and I’ve certainly seen this in the past with
slower builds.  We probably want the timeout value to be one of the
multiplied timeout values that wptrunner already provides, or possibly a
new timeout value for the single purpose of testing implicit waits.

E.g. with an optimised build of Firefox you could expect the behaviour
you’re describing, but with an non-optimised Firefox you’re likely
looking at 30s+ just to start the browser, let alone finding an element.

> And although longer timeouts would make expression of the race less
> likely, WebDriver tests are already among the slowest in WPT; relying
> on such long delays will make them even more so.

This is also the way all existing WebDriver implementations are
tested.  We have some more low-level unit tests for element retrieval in
Marionette, but these are not sharable in the context of WPT.  I agree
this necessarily needs to be a best effort approach.

> Option 1 is the most convenient for folks writing specification tests,
> but it obviously doesn't help implementers or application developers.
>
> Option 2 doesn't really address the problem; it just kind of forces
> test consumers to take some ownership.
>
> Option 3 involves a delay that is more contextual and likely shorter
> than option 2, but due to the nature of HTTP (and in the absence of
> any assurance regarding scheduling of concurrent commands), it would
> still be subject to a race. It is also awkward to author tests like
> this, particularly for navigation operations.

I am in favour of option 3.  I think we by necessity have to write these
kind of tests.  In reality, we have not had so many issues with this
approach.

Not related to navigation or element retrieval, but there are also other
conditions in the document that we may have to wait for.  With the
Marionette functional tests we use a polling wait utility to wait for
such situations:

	https://searchfox.org/mozilla-central/source/testing/marionette/client/marionette_driver/wait.py

Mozilla would be happy to relicense this under CC-0 and donate it WPT.

**Comment by jugglinmike** [comment]
> But the Execute Script command can’t be issued whilst another, such as Find
> Element, is in process. The blocking nature of the main event loop ensures
> this.

As far as I am aware, WebDriver commands do not generally\* interact with any
particular event loop in the browsing context. If that's right, then "waiting"
in a command algorithm does not influence browsing contexts or the remote end's
processing model.

This has certainly been the case with my local testing in Firefox (where it's
possible to have multiple commands processing in parallel), but that's only
anecdotal. I may have missed some important spec text.

\* - some affordances are made in the current specification of Actions.

> I am in favour of option 3. I think we by necessity have to write these kind
> of tests. In reality, we have not had so many issues with this approach.

I'm willing to be pragmatic about this, but I also wonder if we can/should
formally document this "tolerable flakiness," wherever we recognize it. That
would help implementers reason about failures when they do occur. My worry is
that without such documentation, consumers may "discover" intermittent failures,
reducing their confidence in the test suite overall. Maybe a simple convention
like a dedicated sigil (e.q. `@volatile`) in the Python docstring would be
sufficient...

> Not related to navigation or element retrieval, but there are also other
> conditions in the document that we may have to wait for.

For sure! These other considerations seem a little more tractable to me since
they concern observable conditions. But I will keep that implementation in mind
in case re-licensing it would save us some time.

Thanks for getting back to me, Andreas!

**Comment by andreastt** [comment]
Also sprach jugglinmike:

>> But the Execute Script command can’t be issued whilst another, such
>> as Find Element, is in process. The blocking nature of the main event
>> loop ensures this.
> 
> As far as I am aware, WebDriver commands do not generally\* interact
> with any particular event loop in the browsing context. If that's
> right, then "waiting" in a command algorithm does not influence
> browsing contexts or the remote end's processing model.

Maybe we are talking past one another.  What I meant is that a command
sent _from the client_ is queued until the WebDriver main loop is done
processing the current one, which means that a user can’t modify the
DOM using Execute Script whilst e.g. Find Element is running.

I’m not really sure what point you’re trying to make here.

> This has certainly been the case with my local testing in Firefox
> (where it's possible to have multiple commands processing in
> parallel), but that's only anecdotal. I may have missed some important
> spec text.

It is only possible to have multiple commands processing in parallel if
you use Marionette directly. geckodriver should not allow this, and if
it does then it is a bug.

>> I am in favour of option 3. I think we by necessity have to write
>> these kind of tests. In reality, we have not had so many issues with
>> this approach.
> 
> I'm willing to be pragmatic about this, but I also wonder if we
> can/should formally document this "tolerable flakiness," wherever we
> recognize it.

I don’t have any notable reservations against that, but I am curious
what this would be used for in practice.

**Comment by jugglinmike** [comment]
> a command sent _from the client_ is queued until the WebDriver main loop is
> done processing the current one

I haven't been able to find the text that dictates this. I've been mostly looking at [the section titled "Processing Model"](https://w3c.github.io/webdriver/webdriver-spec.html#processing-model), but it may be implemented elsewhere. Can you point me in the right direction?

> It is only possible to have multiple commands processing in parallel if you
> use Marionette directly. geckodriver should not allow this, and if it does
> then it is a bug.

I think this ties back to the confusion described above.

> I don't have any notable reservations against that, but I am curious what
> this would be used for in practice.

I suppose test runners *could* consume such a denotation programatically, perhaps marking such tests as "allowed failures" in their build system. Realistically though, I doubt anyone would wire up such process on our bespoke test annotation system.

The truth is, I have pretty strong reservations about publishing tests which are known to be unstable, even if the instability seems negligible. I'm hoping formal documentation will limit the confusion these tests cause and help others understand that this was an intentional trade off. This documentation should be as close to the volatile tests as possible, and I think a succinct annotation scheme stands the best chance of being maintained by others into the future.

**Comment by shs96c** [comment]
On Thu, Jun 22, 2017 at 11:30 PM, jugglinmike <notifications@github.com>
wrote:

> a command sent *from the client* is queued until the WebDriver main loop
> is
> done processing the current one
>
> I haven't been able to find the text that dictates this. I've been mostly
> looking at the section titled "Processing Model"
> <https://w3c.github.io/webdriver/webdriver-spec.html#processing-model>,
> but it may be implemented elsewhere. Can you point me in the right
> direction?
>

There's the text in the preamble for Section 6 that says that
implementations must be HTTP compliant. An intermediary node is welcome to
handle more than one command at a time. The only caveat is that each
session should only have one command issued against it at a time, though we
never spell this out in the spec.

**Comment by shs96c** [comment]
> The only caveat is that each
session should only have one command issued against it at a time

Actually, this is also incorrect. It should always be possible to execute the "Delete Session" command even if another command is running for that session.

**Comment by jugglinmike** [comment]
I'd be happy to submit a patch to implement this. Do you think the state should be tracked as a property of the session (e.g. "A session has an associated **is processing flag** [...]") or a collection on the remote end (e.g. "A remote end has an associated list of **processing sessions** [...]")? Or maybe something else entirely?

**Comment by shs96c** [comment]
I think it's enough to modify the processing model. There are three possible conditions that need to be tracked for an endpoint node:

1/ Sessionless commands can be processed regardless of whether or not there's a currently active session.
2/ Delete Session can (optionally) be executed immediately
3/ All other commands should be pleased in a queue per session and executed serially.

I'm not aware of any implementations that don't merge those last two branches, as that hugely simplifies the implementation.

**Comment by jugglinmike** [comment]
Understood. I've submitted gh-965 as a first attempt to formalize that behavior.
