### ISSUE TITLE
Define the expiry for a session cookie.

### ISSUE THREAD

**Issue by florentbr** [w3c/webdriver#957]
The specification doesn't define what the expiry should be when a session cookie is returned.

The former behavior was to omit the field:

https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol

> 1 When returning Cookie objects, the server should only omit an optional field if it is incapable of providing the information.

There's only this rule for adding a cookie:

https://w3c.github.io/webdriver/webdriver-spec.html#dfn-table-for-cookie-conversion

> When the cookie expires, specified in seconds since Unix Epoch. Defaults to 20 years into the future if omitted when adding a cookie.

I recommend to omit the field when a session cookie is returned to make it clear that there's no expiration  date.

I also think that setting the expiry to 20 years into the future when adding a cookie is a mistake, first because 20 years in the future is a valid expiry date and second because it will prevent the cookie from being deleted once the browser is closed.

**Comment by shs96c** [comment]
The spec already says that optional values may be omitted when [serialising a cookie](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-serialised-cookie). You're right about the 20 year thing. That's quirky. I'll prepare a patch for it.
