### ISSUE TITLE
confusion about window handles

### ISSUE THREAD

**Issue by jlipps** [w3c/webdriver#958]
In chapter [10. Command Contexts](https://www.w3.org/TR/webdriver/#dfn-window-handle#h-command-contexts), we see this:

> Each browsing context has an associated window handle (string) uniquely identifying it. It must not be "current".
> 
> The web window identifier is the string constant "window-fcc6-11e5-b4f8-330a88ab9d7f".
> 
> The web frame identifier is the string constant "frame-075b-4da1-b6ba-e579c2d3230a".
> 
> The JSON Serialization of the WindowProxy object is the JSON Object obtained by applying the following algorithm to the given WindowProxy object window:
> 
> 1. Let identifier be the web window identifier if the associated browsing context of window is a top-level browsing context.
> 
>     Otherwise let it be the web frame identifier.
> 
> 2. Return a JSON Object initialised with the following properties:
> 
>     *identifier*
>     Associated window handle of the window’s browsing context.

Here's what I'm confused about:

1. how do window handle strings get generated? Is that up to the remote end?
2. what is the relevance of the discussion about "web window identifier" and "web frame identifier"? I see an algorithm to serialize the WindowProxy object, but I don't see this used anywhere. I.e., in step 2 ("Return a JSON object..."), I don't see the `identifier` referred to in step 1 as being used anywhere. What I take step 2 to be saying is, "build a JSON object that looks like `{"identifier": "<WINDOW_HANDLE>"}`. So where does the variable `identifier` come into play?

**Comment by andreastt** [comment]
Also sprach Jonathan Lipps:

> 1. how do window handle strings get generated? Is that up to the
> remote end?

Under the definition of ‘window handle’ it says:

> Each browsing context has an associated window handle (string)
> uniquely identifying it. It must not be "current".

It is implied from this that the remote end may choose what it looks
like.  For example, Marionette currently uses the <xul:browser>
element’s outerWindowID.

> 2. what is the relevance of the discussion about "web window
> identifier" and "web frame identifier"? I see an algorithm to
> serialize the WindowProxy object, but I don't see this used anywhere.

It is used in the ‘internal JSON clone algorithm’.  It looks at
each value to be marshalled and when it sees a WindowProxy object, it
asks for the “JSON Serialization of value”, which is the ‘JSON
serialization of the WindowProxy object’, defined in chapter 10.

There are two bugs here, however:

1. It should be “serialization” in lower casing.

2. The link should take you to the ‘JSON serialization of the
WindowProxy object’ definition in chapter 10.

**Comment by andreastt** [comment]
The issue described here isn’t really a bug, so closing. We could continue the discussion on the mailing list.

**Comment by jlipps** [comment]
@andreastt thanks, i see. so the algorithm I quoted isn't actually used at all in the `Get Window Handle` command. do you think it would be good to make it explicit that the remote end generates the unique window handle string however it pleases?

and i think having the link you mentioned would probably have provided additional context that made it more clear.

**Comment by andreastt** [comment]
> do you think it would be good to make it explicit that the remote end generates the unique window handle string however it pleases?

No, because a new top-level browsing context may appear at any time. The existing implementations don’t assign window handles when the Get Window Handles command is called, but when the windows appear.

The current language ensures you _could_ implement it that way if you wanted, but is non-specific enough to support both architectures.

**Comment by jlipps** [comment]
👍
