### ISSUE TITLE
Allow extensions to specify session-based commands

### ISSUE THREAD

**Issue by jugglinmike** [w3c/webdriver#961]
Currently, the requirements on extension commands are too constrained to allow
for specification of algorithms tied to a specific session. This is due to the
following definition:

> The extension command’s extension command URL is a URL composed of the
> extension command prefix, followed by "/", and the extension command’s name.
> The extension command URL, along with the HTTP method and extension command,
> is added to the table of endpoints and thus follows the same rules for
> request routing as that of other built-in commands. 

...where "extension command prefix" and "extension command name" are both ASCII
lower alpha strings.

(Note that the text quoted above is erroneous because it the value named
"extension command URL" is described as a URL, but the constructed value is
actually a URI. In addition, the value is inserted into a table that includes
URI template values but does not include either URLs or URIs. The intent of the
text is clear, though, and the types may be corrected independently from a
resolution of the larger issue.)

Initially, I interpreted this definition as erroneously omitting text to insert
the "session id" URI template parameter. I learned that interpretation was
wrong in gh-952, where @shs96c wrote:

> not all extensions are going to be at the session level. As an example, the
> selenium server has an extension command that allows new drivers to be
> registered at the server level ("Add Config"), and Grid has a number of
> extensions that allow users to figure out the health of the grid as a whole.

But while some extensions may not require an active session, others will, and
the current text makes it impossible for these to be defined. The section
currently includes an example of such a command:
`/session/5d376174-36f0-11e5-9b9a-6bdf200a3f7f/ms/edge/context`.

I have two ideas for resolving this:

- Allow extension commands to specify URI template variables, either by
  defining compete URI templates, or by extending the character sets of
  "extension command prefix" and "extension command name" with the necessary
  characters
- Introduce a boolean attribute "requires session" (or similar) for extension
  commands, and insert `session/{ session id }` into the URI template for those
  commands that specify this as "true".

The latter approach may be easier to use since it does not require
specification editors to discover the implicit session-detecting logic of the
remote end's processing model. It also tends to make extensions more explicit:
the intention of a boolean attribute is more obvious than a pattern in a URI
template.

The former approach is much more powerful because it allows extensions to
specify additional URL parameters, e.g. `/session/{ session id }/bluetooth/{
device id }`.  There is no current use case for that functionality as far as
I'm aware, but it seems likely to be useful for some specifications.

I'd be happy to follow up with a patch implementing either of these changes,
or some third approach that I haven't considered.

**Comment by shs96c** [comment]
The first solution (using a URI template) is the way to go, and was the original intent.

**Comment by jugglinmike** [comment]
@shs96c I believe this was resolved by gh-962.

**Comment by shs96c** [comment]
Agreed. Closing this issue. Thank you, @jugglinmike!
