### ISSUE TITLE
Should pointer actions scroll the target element into view?

### ISSUE THREAD

**Issue by juangj** [w3c/webdriver#963]
In chapter [17. Actions](https://w3c.github.io/webdriver/webdriver-spec.html#pointer-actions#h-actions), section [17.4 Dispatching Actions](https://w3c.github.io/webdriver/webdriver-spec.html#pointer-actions#h-dispatching-actions):
> An object that represents a web element
> Let element be equal to the result of trying to get a known element with argument origin.
> 
> Let x element and y element be the result of calculating the in-view center point of element.
> 
> Let x equal x element + x offset, and y equal y element + y offset.

When moving the pointer to an element, the element is not first scrolled into view. If the target element is outside of the viewport (or even partially outside it), this can result in a "move target out of bounds" error.

The analogous command in the OSS wire protocol does scroll the element into view first: https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidmoveto

Was this an intentional change? I think it's probably correct to say that the "low-level" Actions API shouldn't be implicitly scrolling, while the do-what-I-mean element click command does implicitly scroll. (In which case, this probably becomes a Selenium bug -- the existing APIs should scroll the element into view.)

**Comment by shs96c** [comment]
This change was discussed by @jgraham and myself on the IRC channel, and elsewhere, though I can't remember if it was at the F2F sessions, on the mailing lists, or in person.

The conclusion we came to was the same as yours: implicit behaviour in the section meant to describe explicit control of interactions doesn't seem wise. OTOH, the implicit commands absolutely should scroll elements into view.

It does mean that we're missing a "scroll into view" primitive in the Actions.

**Comment by shs96c** [comment]
Closing. This was an intentional change, and we know that there's a missing "scroll into view" primitive.
