### ISSUE TITLE
incorrect language in Switch to Frame? child window vs new window.

### ISSUE THREAD

**Issue by jlipps** [w3c/webdriver#973]
In chapter [10. Command Contexts](https://www.w3.org/TR/webdriver/#switch-to-frame#h-command-contexts), section [10.5 Switch To Frame](https://www.w3.org/TR/webdriver/#switch-to-frame#h-switch-to-frame):

> 4. Let child window be the WindowProxy object obtained by calling [[GetOwnProperty]] of a Window object window with argument id.
> 
> 5. Set the current browsing context to new window’s browsing context.

Should step 5 instead read:

> 5. Set the current browsing context to child window's browsing context

?

**Comment by andreastt** [comment]
First of all: Never link to a document under `/TR` because there is a significant delay between when it and the [Editor’s Draft](https://w3c.github.io/webdriver/webdriver-spec.html) is updated.

It appears “new window” used in substep 5 is not defined at all. This should indeed be “child window”.

**Comment by andreastt** [comment]
Some more background: It is possible to enumerate and access `WindowProxy` as an indexed array and we use this to allow access to `<iframe>`s in the order they are defined in tree order. We assign the nth frame’s `WindowProxy` object to _child window_ and want to set the _current browsing context_ to the browsing context _associated_ with said `WindowProxy`.

**Comment by jlipps** [comment]
> First of all: Never link to a document under /TR because there is a significant delay between when it and the Editor’s Draft is updated.

Thanks, I didn't realize there were these two versions. I'll double-check the editor's draft before posting.

**Comment by andreastt** [comment]
Also sprach Jonathan Lipps:

>> First of all: Never link to a document under /TR because there is
>> a significant delay between when it and the Editor’s Draft is
>> updated.
> 
> Thanks, I didn't realize there were these two versions. I'll
> double-check the editor's draft before posting.

Generally, documents published under /TR can be thought of as the
“lawyer’s version” of the specification.  What implementors
and specification authors actually look at, is the Editor’s Draft
(ED).
