### ISSUE TITLE
question about integer range restriction in set window rect

### ISSUE THREAD

**Issue by jlipps** [w3c/webdriver#974]
In chapter [10. Command Contexts](https://www.w3.org/TR/webdriver/#set-window-rect#h-command-contexts), section [10.7 Resizing and Positioning Windows](https://www.w3.org/TR/webdriver/#set-window-rect#h-resizing-and-positioning-windows):
> If x or y is neither null nor an integer from −(2^63) to 2^63 − 1, return error with error code invalid argument.

I'm curious why we are dealing with a 126-bit range rather than a 128-bit range? (particularly when the width is a more natural 64-bit positive integer range)

**Comment by andreastt** [comment]
It describes a 64-bit signed integer range; not 126 or 128. It is bounded by a minimum value of –2<sup>63</sup> and a maximum value of 2<sup>63</sup>–1, in other words from -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807.

It is equivalent to a `int64_t` (or `long`) definition in C, or u64 in Rust. See https://en.wikipedia.org/wiki/Integer_%28computer_science%29 for more information.

**Comment by jlipps** [comment]
Thanks for setting me straight on basic CS :-) I forgot how signed ints worked in binary representation and assumed we were dealing with 2 64-bit ranges (one positive, one negative), rather than 1 63-bit range plus a sign bit, which makes an awful lot more sense.
