### ISSUE TITLE
Cookie domain default value

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#979]
The cookie fields default values are described in 2 places. In the "Add Cookie" command as well as in the description column of the "table for cookie conversion". I would like to ask if the is a subtle distinction between the two, or if they both have the same meaning.

In chapter [16. Cookies](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-unable-to-set-cookie#x16.-cookies), section [16.3 Add Cookie](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-unable-to-set-cookie#x16.3-add-cookie):
> current browsing context’s active document’s 

In chapter [16. Cookies](https://w3c.github.io/webdriver/webdriver-spec.html#cookies#x16.-cookies):
>  current browsing context’s document’s URL domain

**Comment by andreastt** [comment]
Also sprach vkatsikaros:

> The cookie fields default values are described in 2 places. In the
> "Add Cookie" command as well as in the description column of the
> "table for cookie conversion". I would like to ask if the is a
> subtle distinction between the two, or if they both have the same
> meaning.
>
>> current browsing context’s active document’s

…

>> current browsing context’s document’s URL domain

These are supposed to be equal.  Arguably, the more correct
terminology is the former.
