### ISSUE TITLE
Go command and url "is special"

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#982]
In chapter [9. Navigation](https://w3c.github.io/webdriver/webdriver-spec.html#x9.-navigation), section [9.1 Go](https://w3c.github.io/webdriver/webdriver-spec.html#x9.1-go):
> If url is special except for file and ...

The form of the url is checked in step 4 of the algorithm and the algorithm returns early if url doesn't have the proper form. In step 8 the algorithm navigates to the URL if the url is _special_ (ie the schema is ftp, http, etc - [as special is defined in URL](https://url.spec.whatwg.org/#is-special)) and other conditions are met. In case the URL is not _special_, does webdriver silently ignore the Go command by not navigating to the url?

PS I don't have a specific behavior in mind, just wondering about the non _special_ case.

**Comment by AutomatedTester** [comment]
@vkatsikaros 

If the conditional in step 8 is not met then we don't do the substeps, we carry on but we don't do any of those specific checks.

Does that make sense?

**Comment by vkatsikaros** [comment]
@AutomatedTester hm, I think I misread something and completely missed step 7 where the navigation to the url does happen :( I apologize for the noise

**Comment by AutomatedTester** [comment]
@vkatsikaros no worries at all, thanks for looking into it.
