### ISSUE TITLE
Stale Element distinction

### ISSUE THREAD

**Issue by titusfortner** [w3c/webdriver#989]
Shouldn't this example throw a stale element reference error and not an invalid element state error?

In chapter [6. Protocol](https://w3c.github.io/webdriver/webdriver-spec.html#handling-errors#x6.-protocol), section [6.6 Handling Errors](https://w3c.github.io/webdriver/webdriver-spec.html#handling-errors#x6.6-handling-errors):
> A command could not be completed because the element is in an invalid state, e.g. attempting to click an element that is no longer attached to the document.
>

**Comment by andreastt** [comment]
Yes, or more precisely: the example for the _invalid element state_ error is wrong.
