### ISSUE TITLE
element location strategies do not return data key

### ISSUE THREAD

**Issue by vkatsikaros** [w3c/webdriver#993]
In chapter [12. Element Retrieval](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-element-location-strategy#x12.-element-retrieval):
> trying to call the relevant element location strategy 

It seems that the element location strategies themselves do not return with a "data" key as required for them to be used under trying. Moreover, there isn't something to cover the "data" key in the definition of "element location strategy". So, the element location strategies simply "Return something". 

Suggestion: if this was converted to "Return success with data something." it should not change the output of the algorithm and it would cover the "trying". If so, I am happy to provide a patch.

**Comment by shs96c** [comment]
SGTM. I'd be happy to review.
